% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\usepackage{lmodern}
\usepackage{amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
  \usepackage{amssymb}
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Crime Mapping in R},
  pdfauthor={Reka Solymosi and Juanjo Medina},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{amsthm}
\makeatletter
\def\thm@space@setup{%
  \thm@preskip=8pt plus 2pt minus 4pt
  \thm@postskip=\thm@preskip
}
\makeatother
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}

\title{Crime Mapping in R}
\author{Reka Solymosi and Juanjo Medina}
\date{2021-02-03}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{prelude}{%
\chapter*{Prelude}\label{prelude}}
\addcontentsline{toc}{chapter}{Prelude}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

This workbook contains the lab materials for our Crime Mapping module in Department of Criminology at the University of Manchester. This module is an optional unit open to 3rd year undergraduate and postgraduate students.

It makes use of R, as it is a free, open source tool, that has tremendous community support, and great versatility in mapping applications. You can find more details about the advantages of R for geospatial work \href{https://geocompr.robinlovelace.net/intro.html}{here}

Crime Mapping introduces students to the concepts of spatial data analysis. The aim is to familiarise students with basic concepts of GIS, and get acquainted with spatial statistics to be able to talk about data about crime, policing, and criminal justice topics situated in the places they occur. Details can be found in the Syllabus.

\hypertarget{disclaimer}{%
\section{Disclaimer}\label{disclaimer}}

Please beware that:

\begin{itemize}
\tightlist
\item
  In making these notes, while we briefly cover some concepts, students are expected to do the weekly reading, and attend the weekly lectures, as well as participate in lab disucssions to receive a complete course experience. These notes are \emph{not} intended to be a stand-alone reference or textbook, rather a set of exercises to gain hands-on practice with the concepts introduced during the course.
\item
  These pages are the content of the university course mentioned above. They are meant to (very gently) introduce students to the concept of spatial data analysis, and cover descriptive statsitics and the key concepts required to build an understanding of quantitative data analysis in crime research.
\item
  The handouts below use, among other data sets, dara from the UK data service such as the Crime Survey for England and Wales that is available under a Open Government Licence. This dataset is designed to be a learning resource and should not be used for research purposes or the production of summary statistics.
\end{itemize}

\hypertarget{a-first-lesson-about-r}{%
\chapter{A first lesson about R}\label{a-first-lesson-about-r}}

In this lesson, you will be introduced to the programming language, \texttt{R}. After installing the related software and getting a basic idea of the R Studio interface, you will learn three \texttt{R} basics: operators, objects, and packages.

Unlike other statistical software like SPSS and STATA, \texttt{R} is a free, open-source software for performing statistical analysis and data visualization. In addition, \texttt{R} offers more analytical solutions, flexibility, and customization than these commonly used statistical software, and its popularity has increased substantially over the years.

We learn \texttt{R} because we hope that this is an important tool that you will continue to use in future. As it is free and has a community feel to it where anyone can create and upload new techniques, the idea is that you can use \texttt{R} long after this course. Even if data analysis is not in the future for you, learning how to conduct and interpret statistical output is a good skill to have -- much of our knowledge of the world includes statistics, so understanding the numbers and how they were derived are advantages. \texttt{R} uses a language called \textbf{object-oriented programming}, and though it may seem daunting at first, practice makes familiarity. Also, you can impress your friends with all your coding.

\hypertarget{install-r-r-studio}{%
\section{Install R \& R Studio}\label{install-r-r-studio}}

As \texttt{R} and \texttt{R\ Studio} are free software, you should be able to install these on your own machines at home. You may be working with different IT, so there are different options to allow a successful install. Our first activity will be to decide what approach to working with \texttt{R} and \texttt{R\ Studio} will be best for you.

\hypertarget{activity-1-identifying-your-operating-system}{%
\subsection{Activity 1: Identifying your operating system}\label{activity-1-identifying-your-operating-system}}

In this activity, you need to answer a question about your computer/IT that you will be working with for this class. That question is:

\begin{itemize}
\item
  \textbf{What is your operating system}? Operating system refers to the software that your computer is running to deliver the basic functions. You may have, for example:

  \begin{itemize}
  \tightlist
  \item
    \emph{Windows or Linux} - if you have these, you are most likely going to have an easy time installing \texttt{R} and \texttt{R\ Studio}, so you should give the installation instructions below a try
  \item
    \emph{Apple} - if you have a Mac, there are some extra steps to install \texttt{R} and \texttt{R\ Studio}. Specifically, there will be an additional programme to download called Xcode, and additional steps to take.\\
  \item
    \emph{Chromebook} - Installing \texttt{R} and \texttt{R\ Studio} on a Chromebook involves installing Linux. Like with a Mac, there are some additional steps you will need to take, and some patience.
  \end{itemize}
\end{itemize}

In your group google sheets, write down which operating system you have. This will guide which directions to follow later.

\hypertarget{activity-2-install-r-r-studio}{%
\subsection{Activity 2: Install R \& R Studio}\label{activity-2-install-r-r-studio}}

\hypertarget{some-notes-specific-to-your-operating-system.}{%
\subsubsection{Some notes specific to your operating system.}\label{some-notes-specific-to-your-operating-system.}}

Before you move on to the installation steps, look at your answer from Activity 1, and read or watch the advice specific to your operating system:

\begin{itemize}
\tightlist
\item
  Windows: click \href{https://www.youtube.com/watch?v=VLWaED9jTiA}{here} for instructions
\item
  Chromebook: read the tutorial \href{https://blog.sellorm.com/2018/12/20/installing-r-and-rstudio-on-a-chromebook/}{here}
\item
  Mac, follow the guidance in the video \href{https://www.youtube.com/watch?v=cX532N_XLIs\&list=PLqzoL9-eJTNDw71zWePXyHx3_cm_fMP8S}{here} and then, you will also need to install command line tools, for that you can watch another video \href{https://www.youtube.com/watch?v=3Yd9J_dhSfY}{here}
\item
  Linux: for ubuntu see the video \href{https://www.youtube.com/watch?v=kF0-FH-xBiE}{here} and if you have questions, let the teaching team know!
\end{itemize}

Once you have watched or read the instructions for your relevant operating system, you are now ready to actually have a go at downloading the software for yourself. Before you start, write in the google doc any questions or concerns, and once ready, install!

\hypertarget{install-r}{%
\subsubsection*{\texorpdfstring{Install \texttt{R}:}{Install R:}}\label{install-r}}
\addcontentsline{toc}{subsubsection}{Install \texttt{R}:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Go to \url{https://www.r-project.org/}
\item
  Click the \href{https://cran.r-project.org/mirrors.html}{download R} link under the \emph{Getting Started} heading
\item
  You will be asked to select a Comprehensive R Archive Network (CRAN) mirror. Click the URL closest to your location
\item
  Click whichever download link is appropriate for your operating system (see above).
\item
  Then click the \emph{install R for the first-time} link and proceed to install \texttt{R}
\end{enumerate}

\hypertarget{install-r-studio}{%
\subsubsection*{Install R Studio:}\label{install-r-studio}}
\addcontentsline{toc}{subsubsection}{Install R Studio:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Go to \url{https://rstudio.com/}
\item
  Click the \emph{Download} link
\item
  Scroll down and then click the DOWNLOAD button for the free version of
  \texttt{RStudio}
\item
  You will be taken to a website to download the free version of \texttt{RStudio} that is appropriate for your computer. Download and then install it.
\end{enumerate}

\hypertarget{plan-b-accessing-r-studio-remotely-throught-a-web-browser}{%
\subsubsection{Plan B: accessing R Studio remotely throught a web browser}\label{plan-b-accessing-r-studio-remotely-throught-a-web-browser}}

It might be that the above does not work and you find that there are some issues specific to your computer, or something just is not working. In that case, you have two options:

\begin{itemize}
\item
  \emph{Option 1:} You can remotely access one of the university PCs from your browser (Firefox, Chrome, Safari, etc). You can find instructions how to do this \href{https://www.itservices.manchester.ac.uk/students/pc-on-campus/remote-cluster-access/}{here} , and the university IT helpdesk can help you access this too. If you do this, you will be able to use the version of \texttt{RStudio} installed in the computer clusters.
\item
  \emph{Option 2}: You can access an online version of \texttt{R\ Studio}, which you can access through any web browser (Firefox, Chrome, Safari, etc). To do this, you visit \url{https://rstudio.cloud/}, click on `get started for free', choose the free account, and click on `sign up'. Then you can always visit this website and log in to use \texttt{R\ Studio} in the cloud. Note that you should start a \texttt{New\ Project} and name it \emph{Modelling Crime Data}, and then all your work will be saved in this project.
\end{itemize}

\hypertarget{open-up-and-explore-rstudio}{%
\section{Open up and explore RStudio}\label{open-up-and-explore-rstudio}}

In this session we will focus in developing basic familiarity with R Studio. You can use R without using R Studio, but R Studio is an app that makes it easier to work with R.

R Studio is what we call an IDE, an \textbf{integrated development environment}. It is a fancy way of saying that it is a cool interface designed to write programming code. Every time you open up R Studio you are in fact starting a R session. R Studio automatically runs R in the background. We will be interacting with R in this course unit via R Studio.

\includegraphics{img/rstudio.png}

When you first open R Studio, you will see (as in the image above) that there are 3 main windows. The bigger one to your left is the console. If you read the text in the console you will see that R Studio is indeed opening R and you can see what version of R you are running. Since R is constantly being updated the version you installed is likely more recent that the one we used at time of writing.

\hypertarget{activity-3-opening-up-the-script-pane}{%
\subsubsection{Activity 3: Opening up the script pane}\label{activity-3-opening-up-the-script-pane}}

The view in R Studio is structured so that you have 4 open windows in a regular session. However when you first open, you might be starting with only 3. To open the script pane (the one missing) click in the \emph{File} drop down Menu, select \emph{New File}, then \emph{R Script}.

\includegraphics{img/openscript.png}

You will now see the 4 window areas in display. On each of these areas you can shift between different views and panels. You can also use your mouse to re-size the different windows if that is convenient.

\includegraphics{img/the4views.png}

\hypertarget{the-four-panes-of-r-studio}{%
\subsection{The four panes of R Studio}\label{the-four-panes-of-r-studio}}

The purposes of the four panes in Figure above are the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Script and data view}: where you type your programming code that tells \texttt{R} what you want to do. These are essentially instructions that you type and save as a \textbf{script}, so that you can return to it later to remember what you did and to share it with others so that they can reproduce what you did.
\item
  \textbf{Environment and history view}:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\item
  \emph{2.1 Environment} tab- gives you the names of all the (data) objects that you have defined during your current \texttt{R} session, including number of observations and rows in those objects. We learn more about objects later.
\item
  \emph{2.2 History} tab- shows you a history of all the code you have previously evaluated in the main console. One of the key advantages of doing data analysis this way - with code versus with a point and click interface like Excel or ArcGIS is that you are producing a written record of every step you take in the analysis. First time around it will take you time to write these instructions, it may be slower than pointing and clicking. And unlike with pointing and clicking you need to know the ``words'' and ``grammar'' of this language.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\item
  \textbf{Main console}: this is considered \texttt{R\textquotesingle{}s} heart, and it is where \texttt{R} evaluates the codes that you run. You can type your codes directly in the console, but for the sake of good habits, type them in the script and data view so you can save a record of them. Only type and run code from here if you want to debug or do some quick analysis.
\item
  \textbf{File directory, Plots, Packages, Help}:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\roman{enumi})}
\item
  \emph{4.1 Files} tab- allows you to see the files in the folder that is currently set as your working directory.
\item
  \emph{4.2 Plots} tab- you will see any data visualizations that you produce here. You have not produced any yet, so it is empty now.
\item
  \emph{4.3 Packages} tab- you will see the packages that are currently available to install. We will explain what these are soon, but know that they are an essential feature when working with \texttt{R}.
\item
  \emph{4.4 Help} tab- you can access further information on the various packages.
\end{enumerate}

\hypertarget{activity-4-interacting-with-the-4-panes}{%
\subsubsection{Activity 4: Interacting with the 4 panes}\label{activity-4-interacting-with-the-4-panes}}

In the previous activity, you opened up the `script' pane. We now write some code in it, and see what happens.

To do this, go to your open version of \texttt{R\ Studio}, and type in the script pane the following:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"Hello world!"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

When you have typed this, you will have typed your first bit of code. Yet nothing is happening? That is because you also have to \textbf{RUN} the code.

You can do this by highlighting the code you wish to run, and clicking on `run' in the top right hand corner:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{include\_graphics}\NormalTok{(}\StringTok{\textquotesingle{}img/run\_hello\_world.gif\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=400px]{img/run_hello_world}

When you `run' the code, it will print the text `Hello World!' in the bottom pane, which is the \textbf{console}. That means you have written and executed your first line of code.

In the rest of the session, we will be unpacking how this all works, and getting more familiar and comfortable with using \texttt{R\ Studio}.

To recap: the \textbf{script} is where you write your programming code. A script is nothing but a text file with some code on it. Unlike other programs for data analysis you may have used in the past (Excel, SPSS), you need to interact with R by means of writing down instructions and asking R to evaluate those instructions. R is an \emph{interpreted} programming language: you write instructions (code) that the R engine has to interpret in order to do something. And all the instructions we write can and should be saved in a script, so that you can return later to what you did.

One of the key advantages of doing spatial data analysis this way - with code versus with a point and click interface like ArcGIS or MapInfo (or even QGIS) is that you are producing a written record of every step you take in the analysis. First time around it will take you time to write these instructions, it may be slower than pointing and clicking. And unlike with pointing and clicking you need to know the ``words'' and ``grammar'' of this language.

The advantage of doing analysis this way is that once you have written your instructions and saved them in a file, you will be able to share it with others and run it every time you want in a matter of seconds. This creates a \emph{reproducible} record of your analysis: something that your collaborators or someone else anywhere (including your future self, the one that will have forgotten how to do the stuff) could run and get the same results than you did at some point earlier. This makes science more transparent and transparency brings with it many advantages. For example, it makes your research more trustworthy. Don't underestimate how critical this is. \textbf{Reproducibility} is becoming a key criteria to assess good quality research. The University of Manchester \href{https://www.staffnet.manchester.ac.uk/news/display/?id=25496}{just joined the UK Reproducibility Network}, and is promoting this good practice. If you're interested you can join \href{https://research-it.manchester.ac.uk/news/2019/05/30/uom-open-science-working-group/}{the Open Science working group} or the reading club \href{https://reproducibilitea.org/journal-clubs/\#Manchester}{ReproducibiliTea}. You can read up on reproducibility and its importance \href{http://theconversation.com/the-science-reproducibility-crisis-and-what-can-be-done-about-it-74198}{here} or get Stuart Richie's book \href{https://www.goodreads.com/book/show/52199285-science-fictions}{Science Fictions} for an engaging further read.

\hypertarget{customising-the-rstudio-look}{%
\section{Customising the RStudio look}\label{customising-the-rstudio-look}}

R Studio allows you to customise the way it looks. Working with white backgrounds is not generally a good idea if you care about your eyesight. If you don't want to end up with dry eyes not only it is good you follow the 20-20-20 rule (every 20 minutes look for 20 seconds to an object located 20 feet away from you), but it may also be a good idea to use more eye friendly screen displays.

Click in the \emph{Tools} menu and select \emph{Global options}. This will open up a pop up window with various options. Select \emph{Appearance}. In this section you can change the font type and size, but also the kind of theme background that R will use in the various windows.

\includegraphics{img/tools_global_options.png}

You can make any changes you'd like to here, including the theme background that \texttt{R} will use as the interface.

For example, you may choose a darker theme like `tomorrow night bright'.

\includegraphics{img/appearance_choose_tomorrow_night_bright.png}

\includegraphics{img/consoleresults.png}
As indicated above, the window in the bottom left corner is the main \textbf{console}.You will see that the words ``I love maps'' appear printed there. If rather than using R Studio you were working directly from R, that's all you would get: the main console where you can write code interactively (rather than all the different windows you see in R Studio). You can write your code directly in the main console and execute it line by line in an interactive fashion. However, we will be running code from scripts, so that you get used to the idea of properly documenting all the steps you take,

\hypertarget{functions}{%
\subsection{Functions}\label{functions}}

\textbf{Functions} \emph{do} things. They are called by a certain name, usually a name which represents what they do, and they are followed by brackets \texttt{()}. Within the brackets, you can put whatever it is that you want the function to work with. For example, the code we wrote in Activity 4 was the \texttt{print()} function. This function told \texttt{R} to print into the console whatever we put in the brackets (``Hello World!'').

Same idea with a personalised greeting: if you want to print `Hello Reka', you will need to have ``Hello Reka'' inside the brackets:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\StringTok{"Hello Reka"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Hello Reka"
\end{verbatim}

There are so many functions in \texttt{R}. We will be learning many of them throughout our class. \texttt{Print} is fun, but most of the time, we will be using functions to help us with our data analysis. For example, getting the minimum, maximum, or mean of a list of numbers. \texttt{R} does this using functions in a very similar way.

For example, if we have a bunch of numbers, we just find the appropriate function to get the summary we want:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{77}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{77}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{77}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 77
\end{verbatim}

How can you find the function you need? Throughout this class, you will learn a list that appears at the top of each lesson. A recommendation is to also create a `function cookbook', where you write down a list of functions, what the functions do, and some examples. Here is an example:

\includegraphics{img/fn_cookbook.png}

You can use google to make your cookbook, and the website \href{https://stackoverflow.com/}{stackoverflow}, in particular, can help you find the function you need. But be wary, especially in the beginning, that you understand what the function does. There can be several different functions for the same action. One good approach is to add a function of interest to your cookbook and ask the teaching team about what it does, and how it might be different to other functions that do the same thing.

\hypertarget{activity-5-play-around-with-functions}{%
\subsubsection{Activity 5: Play around with functions}\label{activity-5-play-around-with-functions}}

Have a guess (or google) about what you think is the function to get the median. Once you have your answer, write it in the shared google docs. Then, use it to get the median of the numbers 10, 34, 5, 3, 77.

Write the answer in your shared google doc (or note it down for yourself if in the quiet room).

The answer is further below, after the note:

\textbf{NOTE:} \texttt{R} is case-sensitive! For example:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calculating the logarithm }
\FunctionTok{Log}\NormalTok{(}\DecValTok{100}\NormalTok{)}

\CommentTok{\# ERROR!}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Instead, it should be:}
\FunctionTok{log}\NormalTok{(}\DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.60517
\end{verbatim}

Okay, now you know these, the answer to Activity 6 was\ldots{}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{median}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{77}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

Now let us move on to our second key topic: objects!

\hypertarget{objects}{%
\subsection{Objects}\label{objects}}

Everything that exists in \texttt{R} is an \textbf{object}. Think of objects as boxes where you put things in. Imagine a big, empty cardboard box. We can create this big empty box in R by simply giving it a name. Usually, you want your object/box to have a good descriptive name, which will tell people what is in it. Imagine moving house. If you have a cardboard box full of places, you might want to label it ``plates''. That way, when carrying, you know to be careful, and when unpacking, you know its contents will go in the kitchen. On the other hand, if you named it ``box1'', then this is a lot less helpful when it comes to unpacking.

\hypertarget{activity-6-creating-an-object}{%
\subsubsection{Activity 6: Creating an object}\label{activity-6-creating-an-object}}

Let us create an object called `plates'. To do this, you go to your script, and type `plates'.

\includegraphics{img/plates.png}

But if you run this code, you will get an error. Let's see:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{include\_graphics}\NormalTok{(}\StringTok{\textquotesingle{}img/error\_no\_plates.gif\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=400px]{img/error_no_plates}

You see the error `Error! Object plates not found'. This is because you have not yet put anything inside the plates `box'. Remember objects are like boxes,so there must be something inside our object `plates'. In order for this object to exist, you have to put something inside it, or in \texttt{R}-speak \emph{assign it some value}.

Therefore, we make an object by using an \emph{assignment operator} ( \texttt{\textless{}-} ). In other words, we assign something to an object (i.e., put something in the box). For example:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plates }\OtherTok{\textless{}{-}} \StringTok{"yellow plate"}
\end{Highlighting}
\end{Shaded}

Now if we run this, we will see no error message, but instead, we will see the \texttt{plates} object appear in our \emph{environment pane}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\FunctionTok{include\_graphics}\NormalTok{(}\StringTok{\textquotesingle{}img/assign\_plates.gif\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=400px]{img/assign_plates}

Here are some more examples to illustrate:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Putting \textquotesingle{}10\textquotesingle{} in the \textquotesingle{}a\textquotesingle{} box}
\NormalTok{a }\OtherTok{\textless{}{-}} \DecValTok{10}

\CommentTok{\# Putting \textquotesingle{}Hello!\textquotesingle{} in the \textquotesingle{}abc123\textquotesingle{} box}
\NormalTok{abc123 }\OtherTok{\textless{}{-}} \StringTok{"Hello!"}
\end{Highlighting}
\end{Shaded}

In these examples, we are putting the value of \texttt{10} into the object \texttt{a}, and the value of `Hello!' into the object \texttt{abc123}.

Earlier, we introduced you to the Environment and History pane. We mentioned that it lists objects you defined. After making the `a' and `abc123' objects, they should appear in that very pane under the \texttt{Environment} tab.

\hypertarget{types-of-objects}{%
\subsubsection{Types of objects}\label{types-of-objects}}

Why are objects important? We will be storing everything in our data analysis process in these objects. Depending on what is inside them, they can become a different type of object. Here are some examples:

\textbf{Data structures} are important objects that store your data, and there are five main types but we focus on three for this course:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \emph{(atomic) vector}: an ordered set of elements that are of the same \emph{class}. Vectors are a basic data structure in \texttt{R}. Below are five different classes of vectors:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. numeric vector with three elements}
\NormalTok{my\_1st\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\FloatTok{8.9}\NormalTok{, }\FloatTok{0.6}\NormalTok{) }

\CommentTok{\# 2. integer vector with addition of L at the end of the value}
\NormalTok{my\_2nd\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(1L, 2L, 3L)  }

\CommentTok{\# 3. logical vector}
\NormalTok{my\_3rd\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\ConstantTok{TRUE}\NormalTok{, }\ConstantTok{FALSE}\NormalTok{, }\ConstantTok{FALSE}\NormalTok{) }
\CommentTok{\# \textquotesingle{}my\_4th\_vector\textquotesingle{} creates a logical vector using abbreviations of True and False, but you should use the full words instead}
\NormalTok{my\_4th\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(T, F) }

\CommentTok{\# 4. character vector}
\NormalTok{my\_5th\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"a"}\NormalTok{, }\StringTok{"b"}\NormalTok{, }\StringTok{"c"}\NormalTok{) }

\CommentTok{\# 5. complex vector (we will not use this for our class)}
\NormalTok{my\_6th\_vector }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{+}\NormalTok{0i, }\DecValTok{2}\SpecialCharTok{+}\NormalTok{4i) }
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \emph{lists}: technically they, too, are vectors but they are more complex because they are not restricted on the length, structure, or class of the included elements. For example, to create a list containing strings, numbers, vectors and a logical, use the \texttt{list()} function, and inside the brackets, put everything tat you want to combine into a list:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{list\_data }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\StringTok{"teal"}\NormalTok{, }\StringTok{"sky blue"}\NormalTok{, }\FunctionTok{c}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{10}\NormalTok{), }\ConstantTok{TRUE}\NormalTok{, }\FloatTok{68.26}\NormalTok{, }\FloatTok{95.46}\NormalTok{, }\FloatTok{99.7}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

Above, we created \texttt{list\_data}, an object that contains all those things that we put inside the \texttt{list()} function. This function serves to create a list from combining everything that is put inside its brackets.

Use the \texttt{class()} function to confirm that the objects have been defined as a list

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(list\_data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "list"
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  \emph{data frames}: also stores elements but differ from lists because they are defined by their number of columns and rows; the vectors (columns) must be of the same length. Data frames can contain different classes but each column must be of the same class. For example, if you want to combine some related vectors to make a data frame on violent American cities, use the function \texttt{data.frame()}:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Making some relevant vectors}
\NormalTok{TopVioCities }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"St. Louis"}\NormalTok{, }\StringTok{"Detroit"}\NormalTok{, }\StringTok{"Baltimore"}\NormalTok{) }\CommentTok{\# some violent US cities}
\NormalTok{VioRatePer1k }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\FloatTok{20.8}\NormalTok{, }\FloatTok{20.6}\NormalTok{, }\FloatTok{20.3}\NormalTok{) }\CommentTok{\# their violence rates per 1,000 persons}
\NormalTok{State }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Missouri"}\NormalTok{, }\StringTok{"Michigan"}\NormalTok{, }\StringTok{"Maryland"}\NormalTok{) }\CommentTok{\# in what states are these cities found}

\CommentTok{\#Join them to make a data frame called \textquotesingle{}df\textquotesingle{}}
\NormalTok{df}\OtherTok{\textless{}{-}}\FunctionTok{data.frame}\NormalTok{(TopVioCities, VioRatePer1k, State)}
\end{Highlighting}
\end{Shaded}

We can then view the data frame, `df', with the \texttt{View()} function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(df)}
\end{Highlighting}
\end{Shaded}

\hypertarget{activity-7-doing-things-to-objects}{%
\subsubsection{Activity 7: Doing things to objects}\label{activity-7-doing-things-to-objects}}

We have learned what functions are (i.e., things that do things) and what are objects (i.e., the boxes that hold things). We also saw some functions which helped us create objects. Functions can also do things to objects. For example, we saw the function \texttt{class()} that told us about what kind of object list\_data was, and \texttt{View()} which allowed us to have a look at our dataframe we called \texttt{df}.

Let us look back at our \texttt{plates} object. Remember it was the object that held our kitchen items. We added `yellow plate' to it. Now let us add some more items and let us use the concatenate \texttt{c()} function for this again:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plates }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"yellow plate"}\NormalTok{, }\StringTok{"purple plate"}\NormalTok{, }\StringTok{"silver plate"}\NormalTok{, }\StringTok{"orange bowl"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let us say that we suddenly forgot what was in our object called `plates'. Like what we learned earlier, we use the function \texttt{print()} to see what is inside this object:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(plates)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "yellow plate" "purple plate" "silver plate" "orange bowl"
\end{verbatim}

This can apply to obtaining the mean, the minimum, and maximum. You could assign those statistics to an object this time:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nums }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{10}\NormalTok{, }\DecValTok{34}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{77}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now if we want to know the mean, we can take the mean of the object \texttt{nums}, which we just created:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(nums)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 25.8
\end{verbatim}

The object we will use most frequently though is data frames. These hold your data in a format whereby each column represents a variable, and each row an observation.

Just earlier, we had created a dataframe called \texttt{df} previously. If you have not yet copied this over into your own \texttt{R\ Studio}, do this now. You should have the object \texttt{df} in your environment. When you run \texttt{View(df)}, you should see this dataset:

\includegraphics{img/df_view.png}

To do something to an entire dataframe, we would use the name of the object (\texttt{df}) to refer to it. In the case of the \texttt{View()} function, we want to see the whole thing, so we will call \texttt{View(df)}. On the other hand, if we want to refer to only one variable in the data, (remember back to term 1 - each varible is held in each column) there is a special notation to do this.

To refer to a variable (column) inside a dataframe, you use:

\(dataframe name + \$ + variable name\)

For example, to refer to the variable \texttt{VioRatePer1k}, we use the notation \texttt{df\$VioRatePer1k}.

And if we wanted to View only that column, we use:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{VioRatePer1k)}
\end{Highlighting}
\end{Shaded}

You should see:

\includegraphics{img/view_col_only.png}

Say we wanted to know the mean violence rate across our units of analysis, the cities, for example, we would take the numeric column to calculate this:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{VioRatePer1k)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20.56667
\end{verbatim}

\hypertarget{packages}{%
\section{Packages}\label{packages}}

\textbf{Packages} are a very important element of \texttt{R}.

Packages are elements that add the functionality of R. What most packages do is they introduce new functions that allow you to ask R to do new different things. Anybody can write a package, so consequently R packages vary on quality and complexity. You can find packages in different places, as well, from official repositories (which means they have passed a minimum of quality control), something called Git Hub (a webpage where software developers post work in progress), to personal webpages (danger danger!).

Throughout the course, and hopefully afterwards, you will find yourself installing numerous open source software packages that allow \texttt{R} to do new and different things. There are loads of packages out there. In early 2020, there were over 150,000 packages available. Anyone can write one, so you will need to be careful on which ones you use as the quality can vary. Official repositories, like \href{https://cran.r-project.org/}{CRAN}, are your best bet for packages as they will have passed some quality controls.

You can see what packages are available in your local install by looking at the \emph{packages} tab in the \emph{File directory, Plots, Packages} pane.

\includegraphics[width=0.35\textwidth,height=\textheight]{img/packages.png}

A number of the packages we will use belong to a set of packages called \textbf{tidyverse}. These packages help make your data tidy. According to Statistician and Chief Scientist at \texttt{RStudio}, Hadley Wickham, transforming your data into \emph{tidy data} is one of the most important steps of the data analysis process. It will ensure your data are in the format you need to conduct your analyses. We will also be using the simple features package \textbf{sf} and many more associated with spatial data analysis.

Packages can be installed using the \texttt{install.packages()} function. Remember that while you only need to install packages once, they need to be loaded with the \texttt{library()}function each time you open up \texttt{RStudio}. Let us install the package \texttt{dplyr} from \texttt{tidyverse} and load it:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

A lot of code and activity appears in the console. Warnings may manifest. Most of the time, the warnings explain what is being loaded and confirm that the package is successfully loaded. If there is an error, you will have to figure out what the warnings are telling you to successfully load the package. This happens and is normal.

To double check that you have actually installed \texttt{dplyr}, go to that \emph{File Directory, Plots, Packages} pane and click on the \emph{Packages} tab. The list of packages is in alphabetical order and \texttt{dplyr} should be there. If there is a tick in its box, it means that this package is currently loaded and you can use it; if there is no tick, it means that it is inactive, and you will have to bring it up with \texttt{library()}, or just tick its box (Figure 1.6).

\includegraphics[width=0.35\textwidth,height=\textheight]{img/dplyr.png}

On \emph{masking}: sometimes packages introduce functions that have the same name as those that are already loaded into your session. When that happens, the newly loaded ones will override the previous ones. You can still use them but you will have to refer to them explicitly by bringing them up by specifying to which package they belong with \texttt{library()}.

How do you find out what a package does? You look at the relevant documentation. In the Packages window scroll down until you find the new package we installed listed. Here you will see the name of the package (dplyr), a brief description of what the program is about, and the version you have installed (an indication that a package is a good package is that it has gone through several versions, that means that someone is making sure the package gets regular updates and improvements).

Click in the name \emph{dplyr}. You will see that R Studio has now brought you to the Help tab. Here is where you find the help files for this package, including all the available documentation.

Every beginner in R will find these help files a bit confusing. But after a while, their format and structure will begin to make sense to you. Click where it says \emph{User guides, package vignettes, and other documentation}. Documentation in R has become much better since people started to write \textbf{vignettes} for their packages. They are little tutorials that explain with examples what each package does. Click in the \emph{cowsay::cowsay\_tutorial} that you see listed here (the html link). What you will find there is an html file that gives you a detailed tutorial on this package. You don't need to read it now, but remember that this is one way to find help when using R. You will learn to love vignettes.

\hypertarget{exploring-data}{%
\section{Exploring data}\label{exploring-data}}

Now that we know the basic component, let's play around with using R as we will throughout the course, for some data analysis.

We will get some data by installing a package which has data in it as well as functions, and then go on to produce some basic summaries. This should give some practice!

\hypertarget{activity-8-playing-around-with-data}{%
\subsection{Activity 8: Playing around with data}\label{activity-8-playing-around-with-data}}

We are going to look at some data that are part of the \emph{fivethirtyeight} package. This package contains data sets and code behind the stories in \href{http://fivethirtyeight.com/}{this particular online newspaper}. This package is not part of the base installation of R, so you will need to install it first. I won't give you the code for it. See if you can figure it out by looking at previous examples. Discuss and write in the google doc what you think the code will be.

Done? Ok, now we are going to look at the data sets that are included in this package. Remember first we have to load the package if we want to use it:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"fivethirtyeight"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Some larger datasets need to be installed separately, like senators and
## house_district_forecast. To install these, we recommend you install the
## fivethirtyeightdata package by running:
## install.packages('fivethirtyeightdata', repos =
## 'https://fivethirtyeightdata.github.io/drat/', type = 'source')
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\AttributeTok{package=}\StringTok{"fivethirtyeight"}\NormalTok{) }\CommentTok{\#This function will return all the data frames that are available in the named package.}
\end{Highlighting}
\end{Shaded}

Notice that this package has some data sets that relate to stories covered in this newspaper that had a criminological angle. Let's look for example at the \texttt{hate\_crimes} data set. How do you that? First we have to load the data frame into our global environment. To do so use the following code:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(}\StringTok{"hate\_crimes"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

This function will search among all the \emph{loaded} packages and locate the \texttt{hate\_crimes} data set. Notice that it now appears in the global environment, although it also says ``promise'' next to it. To see the data in full you need to do something to it first. So let's do that.

Every object in R can have \textbf{attributes}. These are: names; dimensions (for matrices and arrays: number of rows and columns) and dimensions names; class of object (numeric, character, etc.); length (for a vector this will be the number of elements in the vector); and other user-defined. You can access the attributes of an object using the \texttt{attributes()} function. Let's query R for the attributes of this data frame.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attributes}\NormalTok{(hate\_crimes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $row.names
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
## [26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
## [51] 51
## 
## $class
## [1] "tbl_df"     "tbl"        "data.frame"
## 
## $names
##  [1] "state"                       "state_abbrev"               
##  [3] "median_house_inc"            "share_unemp_seas"           
##  [5] "share_pop_metro"             "share_pop_hs"               
##  [7] "share_non_citizen"           "share_white_poverty"        
##  [9] "gini_index"                  "share_non_white"            
## [11] "share_vote_trump"            "hate_crimes_per_100k_splc"  
## [13] "avg_hatecrimes_per_100k_fbi"
\end{verbatim}

This prints out the row names (not very exciting here..) the class (see above when we used \texttt{class()} function) and the names, which are the column headers - or the \emph{names of the variables within this data set}. You can see there are things like state, and share who voted trump (in the 2016 election, not most recent!).

Now use the \texttt{View()} function to glance at your data frame. What you get there is a spreadsheet with 12 variables and 51 observations. Each variable in this case is providing you with information (demographics, voting patterns, and hate crime) about each of the US states.

Ok, let's now have a quick look at the data. There are so many different ways of producing summary stats for data stored in R that is impossible to cover them all! We will just introduce a few functions that you may find useful for summarising data. Before we do any of that it is important you get a sense for what is available in this data set. Go to the help tab and in the search box input the name of the data frame, this will take you to the documentation for this data frame. Here you can see a list of the available variables.

\includegraphics{img/codebook.png}

Let's start with the \emph{mean}. This function takes as an argument the numeric variable for which you want to obtain the mean. You have done this above, so it should be familiar now! If you want to obtain the mean of the variable that gives us the proportion of people that voted for Donald Trump you can use the following expression:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(hate\_crimes}\SpecialCharTok{$}\NormalTok{share\_vote\_trump)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.49
\end{verbatim}

Another function you may want to use with numeric variables is \texttt{summary()}:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(hate\_crimes}\SpecialCharTok{$}\NormalTok{share\_vote\_trump)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.040   0.415   0.490   0.490   0.575   0.700
\end{verbatim}

This gives you the five number summary (minimum, first quartile, median, third quartile, and maximum, plus the mean and the count of missing values if there are any).

You don't have to specify a variable you can ask for these summaries from the whole data frame:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(hate\_crimes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     state           state_abbrev       median_house_inc share_unemp_seas 
##  Length:51          Length:51          Min.   :35521    Min.   :0.02800  
##  Class :character   Class :character   1st Qu.:48657    1st Qu.:0.04200  
##  Mode  :character   Mode  :character   Median :54916    Median :0.05100  
##                                        Mean   :55224    Mean   :0.04957  
##                                        3rd Qu.:60719    3rd Qu.:0.05750  
##                                        Max.   :76165    Max.   :0.07300  
##                                                                          
##  share_pop_metro   share_pop_hs    share_non_citizen share_white_poverty
##  Min.   :0.3100   Min.   :0.7990   Min.   :0.01000   Min.   :0.04000    
##  1st Qu.:0.6300   1st Qu.:0.8405   1st Qu.:0.03000   1st Qu.:0.07500    
##  Median :0.7900   Median :0.8740   Median :0.04500   Median :0.09000    
##  Mean   :0.7502   Mean   :0.8691   Mean   :0.05458   Mean   :0.09176    
##  3rd Qu.:0.8950   3rd Qu.:0.8980   3rd Qu.:0.08000   3rd Qu.:0.10000    
##  Max.   :1.0000   Max.   :0.9180   Max.   :0.13000   Max.   :0.17000    
##                                    NA's   :3                            
##    gini_index     share_non_white  share_vote_trump hate_crimes_per_100k_splc
##  Min.   :0.4190   Min.   :0.0600   Min.   :0.040    Min.   :0.06745          
##  1st Qu.:0.4400   1st Qu.:0.1950   1st Qu.:0.415    1st Qu.:0.14271          
##  Median :0.4540   Median :0.2800   Median :0.490    Median :0.22620          
##  Mean   :0.4538   Mean   :0.3157   Mean   :0.490    Mean   :0.30409          
##  3rd Qu.:0.4665   3rd Qu.:0.4200   3rd Qu.:0.575    3rd Qu.:0.35694          
##  Max.   :0.5320   Max.   :0.8100   Max.   :0.700    Max.   :1.52230          
##                                                     NA's   :4                
##  avg_hatecrimes_per_100k_fbi
##  Min.   : 0.2669            
##  1st Qu.: 1.2931            
##  Median : 1.9871            
##  Mean   : 2.3676            
##  3rd Qu.: 3.1843            
##  Max.   :10.9535            
##  NA's   :1
\end{verbatim}

There are multiple ways of getting results in R. Particularly for basic and intermediate-level statistical analysis many core functions and packages can give you the answer that you are looking for. For example, there are a variety of packages that allow you to look at summary statistics using functions defined within those packages. You will need to install these packages before you can use them.

I am only going to introduce one of them here \texttt{skimr}. You will need to install it before anything else.

Once you have loaded the \emph{skimr} package you can use it. Its main function is \emph{skim}. Like \emph{summary} for data frames, skim presents results for all the columns and the statistics will depend on the class of the variable.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{skim}\NormalTok{(hate\_crimes)}
\end{Highlighting}
\end{Shaded}

Hopefully in your statistical modules you had taken previously, you have learned some things about how to graphically display variables. So you may have some memory about the amount of work involved with this. Hopefully R will offer some respite. Of course, there are many different ways of producing graphics in R. In this course we rely on a package called \emph{ggplot2}, which is part of the tidyverse set of packages mentioned earlier.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Then we will use one of its functions to create a scatterplot.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(hate\_crimes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{share\_vote\_trump, }\AttributeTok{y=}\NormalTok{avg\_hatecrimes\_per\_100k\_fbi)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{shape=}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
     \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing non-finite values (stat_smooth).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 1 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-23-1.pdf}

What do you think this graphic is telling you? Discuss and write in your shared google docs.

Graphing is very powerful in R, and much of the spatial visualisation we will produce throughout the module will build on this. If you are not already familiar with this, I recommend a read of the data visualisation chapter of R for Data Science \url{https://r4ds.had.co.nz/data-visualisation.html}

\hypertarget{getting-organised-r-projects}{%
\section{Getting organised: R Projects}\label{getting-organised-r-projects}}

One thing that can help you tremendously throughout this module is keeping your code organised.R Studio helps with this by virtue of something called \textbf{R Projects}.

Technically, a R Studio project is just a directory with the name of the project, and a few files and folders created by R Studio for internal purposes. This is where you should hold your scripts, your data, and reports. You can manage this folder with your own operating system manager (discussed earlier, e.g., Windows) or through the R Studio file manager (that you access in the bottom right corner set of windows in R Studio).

When a project is reopened, R Studio opens every file and data view that was open when the project was closed last time around. Trust me, this is a really helpful thing! If you create a project for this module, you can keep everything in once place, and refer back to your old code and your learnings throughout the module.

\hypertarget{activity-9-saving-your-work-and-projects}{%
\subsubsection{Activity 9: Saving your work and projects}\label{activity-9-saving-your-work-and-projects}}

First things first, hopefully you have already created a separate folder on your desktop, or dropbox, or something like this. Now save the script you've been working on into this folder. By clicking on ``File'' and ``Save as\ldots{}''.

\includegraphics{img/save_script_as.png}

Then navigate to your folder for this module, and for your script make sure to give it some meaningful name like week1lab.R or something like this. Then click `save'.

\includegraphics{img/rename_and_save.png}

Now, go back to ``File'' and select ``New project\ldots{}''

\includegraphics{img/file_newproj.png}

Then in the options that appear choose ``Existing Directory''. This is because you already have a folder for this work, this is where you saved your script just before. For me this was my folder called `crime\_mapping' you saw above.

\includegraphics{img/existing_dir.png}

So select `Existing Directory', and on the next page use the ``Browse'' button to select this folder (the directory) where you saved the script earlier. Once you have done this, click on `Create Project' on the bottom.

This will now open up a new R Studio window with your project. In the future, you can start right back up where you finished last time by navigating to the .Rproj file, and double clicking it. It helps you keep everything in one place, and lets R read everything from that folder.

With simple projects a single script file and a data file is all you may have. But with more complex projects, things can rapidly become messy. So you may want to create subdirectories within this project folder. I typically use the following structure in my own work to put all files of a certain type in the same subdirectory:

\begin{itemize}
\item
  \emph{Scripts and code}: Here I put all the text files with my analytic code, including rmarkdown files which is something we will introduce much later in the semester.
\item
  \emph{Source data}: Here I put the original data. I tend not to touch this once I have obtained the original data.
\item
  \emph{Documentation}: This is the subdirectory where I place all the data documentation (e.g., codebooks, questionnaires, etc.)
\item
  \emph{Modified data}: All analysis involve doing transformations and changing things in the original data files. You don't want to mess up the original data files, so what you should do is create new data files as soon as you start changing your source data. I go so far as to place them in a different subdirectory.
\item
  \emph{Literature}: Analysis is all about answering research questions. There is always a literature about these questions. I place the relevant literature for the analytic project I am conducting in this subdirectory.
\item
  \emph{Reports and write up}: Here is where I file all the reports and data visualisations that are associated with my analysis.
\end{itemize}

If you come to my office, you will see it is a very messy place. But my computer is, in contrast, a very tidy environment. You should aim for your computer workspace to be very organised as well.

You can read up here on why projects are useful here: \url{https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/}

\hypertarget{making-maps-in-r}{%
\chapter{Making Maps in R}\label{making-maps-in-r}}

This week we will start making some maps in R, and learn about how we can take regular crime data, and assign the appropriate geometry for our chosen unit of analysis. We will produce some maps, using possibly familiar ggplot notation, and learn some key terms around projectsion and coordinate reference systems which will be essential for your work in the coming weeks.

Today we will use the following packages, so make sure you have them downloaded:

\begin{itemize}
\tightlist
\item
  \texttt{reader}
\item
  \texttt{tibble}
\item
  \texttt{janitor}
\item
  \texttt{sf}
\item
  \texttt{ggplot2}
\item
  \texttt{ggspatial}
\item
  \texttt{dplyr}
\end{itemize}

\hypertarget{a-quick-introduction-of-terms}{%
\section{A quick introduction of terms}\label{a-quick-introduction-of-terms}}

\hypertarget{geospatial-perspective---the-basics}{%
\subsection{Geospatial Perspective - The Basics}\label{geospatial-perspective---the-basics}}

Geospatial analysis provides a distinct perspective on the world, a unique lens through which to examine events, patterns, and processes that operate on or near the surface of our planet. Ultimately geospatial analysis concerns what happens where, and makes use of geographic information that links features and phenomena on the Earth's surface to their locations.

We can talk about a few different concepts when it comes to spatial information. These are:

\begin{itemize}
\tightlist
\item
  Place
\item
  Attributes
\item
  Objects
\end{itemize}

\hypertarget{place}{%
\subsubsection{Place}\label{place}}

At the center of all spatial analysis is the concept of \emph{place}. People identify with places of various sizes and shapes, from the room with the parcel of land, to the neighbourhood, to the city, the country, the state or the nation state. Places often have names, and people use these to talk about and distinguish names. Names can be official. Places also change continually as people move. The basis of rigorous and precise definition of place is a coordinate system, a set of measurements that allows place to be specified unambiguously and in a way that is meaningful to everyone.

\hypertarget{attributes}{%
\subsubsection{Attributes}\label{attributes}}

Attribute has become the preferred term for any recorded characteristic or property of a place. A place's name is an obvious example of an attribute. But there can be other pieces of information, such as number of crimes in a neighbourhood, or the GDP of a country. Within GIS the term `attributes' usually refers to records in a data table associated with individual elements in a vector map or cells in a grid (raster or image file). These data behave exactly as data you have encountered in your past experience. The rows represent observations, and the columns represent variables. The variables can be numeric or categorical, and depending on what they are, you can apply different methods to making sense of them. The difference with other kind of data table is that the observations, your rows, correspond to places or locations.

\hypertarget{objects-1}{%
\subsubsection{Objects}\label{objects-1}}

In spatial analysis it is customary to refer to places as objects. These objects can be a whole country, or a road. In forestry, the objects of interest might be trees, and their location will be represented as points. On the other hand, studies of social or economic patterns may need to consider the two-dimensional extent of places, which will therefore be represented as areas. These representations of the world are part of what is called the \textbf{vector data model}: A representation of the world using points, lines, and polygons. Vector models are useful for storing data that have discrete boundaries, such as country borders, land parcels, and streets. This is made up of points, lines, and areas (polygons):

\begin{itemize}
\tightlist
\item
  Points

  \begin{itemize}
  \tightlist
  \item
    Points are pairs of coordinates, in latitude/longitude or some other standard system
  \end{itemize}
\item
  Lines

  \begin{itemize}
  \tightlist
  \item
    Lines are ordered sequences of points connected by straight lines
  \end{itemize}
\item
  Areas (polygons)

  \begin{itemize}
  \tightlist
  \item
    Areas are ordered rings of points, also connected by straight lines to form polygons. It can contain holes, or be linked with separate islands.
  \end{itemize}
\end{itemize}

\includegraphics{img/ptlinepoly.png}

Objects can also be \textbf{raster data}. Raster data is made up of pixels (or cells), and each pixel has an associated value. Simplifying slightly, a digital photograph is an example of a raster dataset where each pixel value corresponds to a particular colour. In GIS, the pixel values may represent elevation above sea level, or chemical concentrations, or rainfall etc. The key point is that all of this data is represented as a grid of (usually square) cells.

\hypertarget{networks}{%
\subsubsection{Networks}\label{networks}}

We already mentioned lines that constitute objects of spatial data, such as streets, roads, railroads, etc. Networks constitute one-dimensional structures embedded in two or three dimensions. Discrete point objects may be distributed on the network, representing phenomena such as landmarks, or observation points. Mathematically, a network forms a graph, and many techniques developed for graphs have application to networks. These include various ways of measuring a network's connectivity, or of finding the shortest path between pairs of points on a network. You can have a look at the \href{https://docs.qgis.org/2.18/en/docs/training_manual/vector_analysis/network_analysis.html}{lesson on network analysis in the QGIS documentation}

\hypertarget{maps-reference-and-thematic-maps}{%
\subsubsection{Maps: reference and thematic maps}\label{maps-reference-and-thematic-maps}}

Historically maps have been the primary means to store and communicate spatial data. Objects and their attributes can be readily depicted, and the human eye can quickly discern patterns and anomalies in a well-designed map.

In GIS we distinguish between reference and thematic maps. A \textbf{reference map} places the emphasis on the location of spatial objects such as cities, mountains, rivers, parks, etc. You use these maps to orient yourself in space and find out the location of particular places. \textbf{Thematic maps}, on the other hand, are about the spatial distribution of attributes or statistics. For example, the number of crimes across different neighbourhouds. Our focus in this book is on thematic maps.

\hypertarget{map-projections-and-geographic-coordinate-systems}{%
\subsubsection{Map projections and geographic coordinate systems}\label{map-projections-and-geographic-coordinate-systems}}

Whenever we put something into a map we need some sort of system to pinpoint the location. A coordinate system allows you to integrate any dataset with other geographical datasets within a common framework. There are hundreds of them. It is common to distinguish between \textbf{geographic coordinate systems} and \textbf{projected coordinate systems}. A \emph{geographic coordinate system} is a \emph{three dimensional} reference system that enables you to locate any location on earth. Often this is done with longitude, latitute and elevation. \emph{Projected coordinate systems} or map projections, on the other hand, try to portray the surface of the earth or a portion of the earth on a \emph{two dimensional} flat piece of paper or computer screen.

All projections of a sphere like the earth in a two dimensional map involve some sort of distortion. You can't fit a three dimensional object into two dimensions without doing so. Projections differ to a large extent on the kind of distortion that they introduce. The decision as to which map projection and coordinate reference system to use, depends on the regional extent of the area you want to work in, on the analysis you want to do and often on the availability of data. Knowing the system you use would allow you to translate your data into other systems whenever this may be necessary. Often you may have to integrate data that is provided to you in different coordinate or projected systems. As long as you know the systems, you can do this.

{[}Footnote to this for more detail: \url{https://www.youtube.com/watch?v=6tmDxTAjux0}{]}

A traditional method of representing the earth's shape is the use of globes. When viewed at close range the earth appears to be relatively flat. However when viewed from space, we can see that the earth is relatively spherical. Maps, are representations of reality. They are designed to not only represent features, but also their shape and spatial arrangement. Each map projection has advantages and disadvantages. The best projection for a map depends on the scale of the map, and on the purposes for which it will be used. For your purposes, you just need to understand that essentially there are different ways to flatten out the earth, in order to get it into a 2-dimensional map.

The process of creating map projections can be visualised by positioning a light source inside a transparent globe on which opaque earth features are placed. Then project the feature outlines onto a two-dimensional flat piece of paper. Different ways of projecting can be produced by surrounding the globe in a cylindrical fashion, as a cone, or even as a flat surface. Each of these methods produces what is called a map projection family. Therefore, there is a family of planar projections, a family of cylindrical projections, and another called conical projections.

\begin{figure}
\centering
\includegraphics{img/projection_families.png}
\caption{figure\_projection\_families}
\end{figure}

With the help of \textbf{coordinate reference systems} (CRS) every place on the earth can be specified by a set of three numbers, called coordinates. In general CRS can be divided into \textbf{projected coordinate reference systems} (also called Cartesian or rectangular coordinate reference systems) and \textbf{geographic coordinate reference systems}.

The use of Geographic Coordinate Reference Systems is very common. They use degrees of latitude and longitude and sometimes also a height value to describe a location on the earth's surface. The most popular is called \textbf{WGS 84}. This is the one you will most likely be using, and if you get your data in latitude and longitude, then this is the CRS you are working in. It is also possible that you will be using a projected CRS. This two-dimensional coordinate reference system is commonly defined by two axes. At right angles to each other, they form a so called XY-plane. The horizontal axis is normally labelled X, and the vertical axis is normally labelled Y.

Working with data in the UK, on the other hand, you are most likely to be using \textbf{British National Grid (BNG)}. The Ordnance Survey National Grid reference system is a system of geographic grid references used in Great Britain, different from using Latitude and Longitude. In this case, points will be defined by ``Easting'' and ``Northing'' rather than ``Longitude'' and ``Latitude''. It basically divides the UK into a series of squares, and uses references to these to locate something. The most common usage is the six figure grid reference, employing three digits in each coordinate to determine a 100 m square. For example, the grid reference of the 100 m square containing the summit of Ben Nevis is NN 166 712. Grid references may also be quoted as a pair of numbers: eastings then northings in meters, measured from the southwest corner of the SV square. For example, the grid reference for Sullom Voe oil terminal in the Shetland Islands may be given as HU396753 or 439668,1175316

\begin{figure}
\centering
\includegraphics{img/Ordnance_Survey_National_Grid.svg.png}
\caption{BNG}
\end{figure}

This will be important later on when we are linking data from different projections, or when you look at your map and you try to figure out why it might look ``squished''.

\hypertarget{density-estimation}{%
\subsubsection{Density estimation}\label{density-estimation}}

One of the more useful concepts in spatial analysis is density - the density of humans in a crowded city, or the density of retail stores in a shopping centre. Mathematically, the density of some kind of object is calculated by counting the number of such objects in an area, and dividing by the size of the area. To read more about this, I recommend \href{https://books.google.co.uk/books?id=e-xsrjsL7WkC\&dq=silverman+density+estimation+for+statistics\&lr=\&source=gbs_navlinks_s}{Silverman, Bernard W. Density estimation for statistics and data analysis. Vol. 26. CRC press, 1986.}

\hypertarget{summary}{%
\subsection{Summary}\label{summary}}

Right so hopefully this gives you a few things to think about. Be sure that you are confident to know about:

\begin{itemize}
\tightlist
\item
  Spatial objects - what they are and how they are represented
\item
  Attributes - the bits of information that belong to your spatial objects
\item
  Maps and projections - especially what WSG84 and BNG mean, and why it's important that you know what CRS your data have
\end{itemize}

\hypertarget{getting-some-spatial-data-to-put-on-a-map}{%
\section{Getting some spatial data to put on a map}\label{getting-some-spatial-data-to-put-on-a-map}}

Alright let's get some practical experience where we take some crime data, and find out how we can put it on the map!

\hypertarget{find-some-relevant-data-to-show-obtaining-data-on-crime}{%
\subsection{Find some relevant data to show: obtaining data on crime}\label{find-some-relevant-data-to-show-obtaining-data-on-crime}}

For your first crime map, we better get some real world crime data. This can be done for the UK easily, as anonymised open crime data are released for the public to use. We can play around with police recorded crime data, which can be downloaded from the \href{https://data.police.uk/data/}{police.uk} website.

Let's download some data for crime in Manchester.

\hypertarget{activity-1-get-some-crime-data}{%
\subsection{Activity 1: Get some crime data}\label{activity-1-get-some-crime-data}}

To do acquire the data, open the \href{https://data.police.uk/data/}{data.police.uk/data} website. Choose the data tab, in order to download some data.

\begin{itemize}
\tightlist
\item
  In \texttt{Date\ range} just select one month of data. Choose whatever month you like EXCEPT nothing more recent than June 2019. Unfortunately, for GMP there is no more recent data available than that. This is because they are having some serious IT issues \href{https://www.manchestereveningnews.co.uk/news/greater-manchester-news/gmp-finally-switches-new-27m-16632975}{see this article} which apparently have disrupted this flow of data.
\item
  In \texttt{Force} find \texttt{Greater\ Manchester\ Police}, and tick the box next to it.
\item
  In \texttt{Data\ sets} tick \texttt{Include\ crime\ data}.
\item
  Finally click on \texttt{Generate\ File} button.
\end{itemize}

This will take you to a download page, where you have to click the \texttt{Download\ now} button. This will open a dialogue to save a .zip file. Navigate to the project directory folder you've created and save it there, ideally in a subfolder. I call my subfolder `data'.

Unzip the file. You can use the unzip function for this. A cool function you may want to use as well is file.choose(). If we pass this function as an argument to unzip(), we will get a pop window where we will be able to select our file using familiar point and click. Ideally, you want to rather write down the path to your file. But sometimes these shortcuts are convenient.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unzip}\NormalTok{(}\FunctionTok{file.choose}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

If you look at the \emph{Files} window in the bottom right corner of RStudio you should see now a new subdirectory that contains a .csv file with the data that we need. Since I downloaded the data from June 2019 in my case this subdirectory is called 2019-06.

Before we can use this data we need to read it or import it into R and turn it into a dataframe object. To read in the .csv file, which is the format we just downloaded, the command is \texttt{read\_csv()} from the \texttt{readr} package. You'll need to load this package first.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\end{Highlighting}
\end{Shaded}

Again there are two ways to read in the data, if you want to open a window where you can manually navigate and open the file, you can pass \texttt{file.choose()} argument to the \texttt{read\_csv()} function as illustrated earlier.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#This code creates a dataframe object called crimes which will include the spreadsheet in the file we have downloaded. In my case, that is 2007{-}11{-}greater{-}manchester{-}street.csv.}

\NormalTok{crimes }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\FunctionTok{file.choose}\NormalTok{())}

\NormalTok{m }\CommentTok{\# Print the map}
\end{Highlighting}
\end{Shaded}

Or, if you know the path to your file, you can code it in there, within quotation marks:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/2019{-}06{-}greater{-}manchester{-}street.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## -- Column specification --------------------------------------------------------
## cols(
##   `Crime ID` = col_character(),
##   Month = col_character(),
##   `Reported by` = col_character(),
##   `Falls within` = col_character(),
##   Longitude = col_double(),
##   Latitude = col_double(),
##   Location = col_character(),
##   `LSOA code` = col_character(),
##   `LSOA name` = col_character(),
##   `Crime type` = col_character(),
##   `Last outcome category` = col_character(),
##   Context = col_logical()
## )
\end{verbatim}

You might notice that the object \texttt{crimes} has appeared in your work environment window. It will tell you how many observations (rows - and incidentally the number of recorded crimes in June 2019 within the GMP jurisdiction) and how many variables (columns) your data has.

Let's have a look at the crimes dataframe with the \texttt{View()} function. This will open the data browser in RStudio

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(crimes)}
\end{Highlighting}
\end{Shaded}

If you rather just want your results in the console, you can use the glimpse() function from the tibble package. This function does just that, it gives you a quick glimpse of the first few cases in the dataframe. Notice that there are two columns (Longitude and Latitude) that provide the require geographical coordinates that we need to plot this data.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tibble)}
\FunctionTok{glimpse}\NormalTok{(crimes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 32,058
## Columns: 12
## $ `Crime ID`              <chr> NA, "aa1cc4cb0c436f463635890bcb4ff2cba08f59...
## $ Month                   <chr> "2019-06", "2019-06", "2019-06", "2019-06",...
## $ `Reported by`           <chr> "Greater Manchester Police", "Greater Manch...
## $ `Falls within`          <chr> "Greater Manchester Police", "Greater Manch...
## $ Longitude               <dbl> -2.464422, -2.441166, -2.444807, -2.444807,...
## $ Latitude                <dbl> 53.61250, 53.61604, 53.61151, 53.61151, 53....
## $ Location                <chr> "On or near Parking Area", "On or near Pitc...
## $ `LSOA code`             <chr> "E01004768", "E01004768", "E01004768", "E01...
## $ `LSOA name`             <chr> "Bolton 001A", "Bolton 001A", "Bolton 001A"...
## $ `Crime type`            <chr> "Anti-social behaviour", "Violence and sexu...
## $ `Last outcome category` <chr> NA, "Unable to prosecute suspect", "Unable ...
## $ Context                 <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,...
\end{verbatim}

You may notice that a lot of the variable names are messy in that they have a space in them - this can cause issues, so before playing around too much with the data we want to clean this up.

Luckily there is a very handy package you can use for this called \texttt{janitor} which contains the function \texttt{clean\_names()}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(janitor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'janitor'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     chisq.test, fisher.test
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes }\OtherTok{\textless{}{-}} \FunctionTok{clean\_names}\NormalTok{(crimes)}
\end{Highlighting}
\end{Shaded}

Now the names are much neater. You can print them all for a view using the \texttt{names()} function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(crimes)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "crime_id"              "month"                 "reported_by"          
##  [4] "falls_within"          "longitude"             "latitude"             
##  [7] "location"              "lsoa_code"             "lsoa_name"            
## [10] "crime_type"            "last_outcome_category" "context"
\end{verbatim}

So what you see above is what we can call a \textbf{basemap}. The term basemap is seen often in GIS and refers to a collection of GIS data and/or orthorectified imagery that form the background setting for a map. The function of the basemap is to provide background detail necessary to orient the location of the map. Basemaps also add to the aesthetic appeal of a map.

\hypertarget{from-dataframes-to-spatial-objects-finding-spatial-information-in-our-data}{%
\section{From dataframes to spatial objects: finding spatial information in our data}\label{from-dataframes-to-spatial-objects-finding-spatial-information-in-our-data}}

Having had a chance to inspect the data set you've downloaded, let's consider what sort of spatial information we might be able to use.

\hypertarget{activity-2-find-the-spatial-data}{%
\subsection{Activity 2: Find the spatial data}\label{activity-2-find-the-spatial-data}}

If you have a look at the column names, what are some of the variables which you think might have some spatial component? Have a think about each column, and how you think it may help to put these crimes on the map. Discuss in your groups, and add the answer to the shared google doc. Once you are done, read on.

So what did you decide in your discussion? There are a few answers here.

In fact there are one each to map onto point, line, and polygon, which we read about earlier.

\hypertarget{the-point}{%
\subsection{The point}\label{the-point}}

First, and possibly most obvious, are the coordinates provided with each crime incident recorded. You can find this in the two columns - Longitude and Latitude. These two column help put each crime incident on a specific point on a map. For example, let's take the very first crime incident. Here we use the head() function and specify that we want the first 1 rows only with \texttt{n=1} parameter.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(crimes, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   <chr>    <chr> <chr>       <chr>            <dbl>    <dbl> <chr>    <chr>    
## 1 <NA>     2019~ Greater Ma~ Greater Man~     -2.46     53.6 On or n~ E01004768
## # ... with 4 more variables: lsoa_name <chr>, crime_type <chr>,
## #   last_outcome_category <chr>, context <lgl>
\end{verbatim}

You can see that the values are for Longitude and for Latitude. These two numbers allow us to put this point on a map.

\hypertarget{the-line}{%
\subsection{The line}\label{the-line}}

Another column which contains information about \emph{where} the crime happened is the aptly named \texttt{location} variable. This shows you a list of locations related to where the crimes happened. You may see a few values such as on or near XYZ street. Let's look again at the first entry.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(crimes, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   <chr>    <chr> <chr>       <chr>            <dbl>    <dbl> <chr>    <chr>    
## 1 <NA>     2019~ Greater Ma~ Greater Man~     -2.46     53.6 On or n~ E01004768
## # ... with 4 more variables: lsoa_name <chr>, crime_type <chr>,
## #   last_outcome_category <chr>, context <lgl>
\end{verbatim}

You can see that the value is this isn't great, as we might struggle to identify \emph{which} parking area\ldots{} Some other ones are more useful, let's look at the last entry for example with the \texttt{tail()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(crimes, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   <chr>    <chr> <chr>       <chr>            <dbl>    <dbl> <chr>    <chr>    
## 1 75e215f~ 2019~ Greater Ma~ Greater Man~     -2.57     53.5 On or n~ E01006347
## # ... with 4 more variables: lsoa_name <chr>, crime_type <chr>,
## #   last_outcome_category <chr>, context <lgl>
\end{verbatim}

You can see that the value is . This makes our crime much easier to find, we just need to locate where is . We might have a shapefile of lines of all the roads of Manchester, and if we did, we can link the crime to that particular road, in order to map it.

\hypertarget{the-polygon}{%
\subsection{The polygon}\label{the-polygon}}

What more? You may also have seen the column \texttt{lsao\_name} seems to have some spatial component, Let's have a look at the first crime again.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(crimes, }\AttributeTok{n =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   <chr>    <chr> <chr>       <chr>            <dbl>    <dbl> <chr>    <chr>    
## 1 <NA>     2019~ Greater Ma~ Greater Man~     -2.46     53.6 On or n~ E01004768
## # ... with 4 more variables: lsoa_name <chr>, crime_type <chr>,
## #   last_outcome_category <chr>, context <lgl>
\end{verbatim}

You see the value for LSOA name is - Bolton we know is a Borough of Greater Manchester, but what is the 001 for ?

Well it denotes a sparticular geographical sub-unit within Bolton called a \textbf{Lower Layer Super Output Area}. This is a unit of \href{https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography}{UK Census Geography}. The basic unit for Census Geography is an `Outout area' - this is the resolution at which we can access data from the UK Census. We will be making use of census data later in the course. The Ourput Area (OA) is therefore the smallest unit we could use. Normally, in this module, we will be using a slightly larger version - the Lower Super Output Area (LSOA).

There are now 181,408 OAs, 34,753 lower layer super output areas (LSOA) and 7,201 middle layer super output areas (MSOA) in England and Wales. The neat thing about these Census geographies is the idea is that they don't change (unlike administrative boundaries such as wards) and were created with statistical analysis in mind. The less neat thing is that although we use them to operationalise the concept of neighbourhood a lot, they may not bear much resemblance to what residesnts might think of as their neighbourhood. Think for a minute - do you know what LSOA you live in? Most likely you answered no. If you answered yes, I am impressed and you get geography nerd cred. Well done.

Anyway back to our crime data. You see we have two columns that reference LSOAs, \texttt{lsoa\_name} and \texttt{lsoa\_code}. We can use these to \emph{link} our crime data to a \emph{shapefile} of a \emph{polygon} which contains the geometries needed to put the crime data on the map.

\hypertarget{putting-crime-on-the-map---simple-features}{%
\section{Putting crime on the map - simple features}\label{putting-crime-on-the-map---simple-features}}

So how can we use these spatial details to put our crimes on the map? We need to somehow specify a geometry for our data, which links each unit of analysis (whether that is the point, line, or polygon) to a relevant geographical representation, which allows us to put this thing on the map.

How you add geographical information will vary with the type of information we have, but in all of these, we will use the simple features framework.

\begin{figure}
\centering
\includegraphics{https://user-images.githubusercontent.com/520851/50280460-e35c1880-044c-11e9-9ed7-cc46754e49db.jpg}
\caption{(Illustration (c) by Allison Horst)}
\end{figure}

What are simple features? sf package author Edzer Pebesma describes simple features as a standardized way of encoding spatial vector data (points, lines, polygons) in computers. The sf package is an R package for reading, writing, handling, and manipulating simple features in R, implementing the vector (points, lines, polygons) data handling functionality.

Traditionally spatial analysis in R were done using the \texttt{sp} package which creates a particular way of storing spatial objects in R. When most packages for spatial data analysis in R and for thematic cartography were first developed \texttt{sp} was the only way to work with spatial data in R. There are more than 450 packages rely on \texttt{sp}, making it an important part of the R ecosystem. More recently a new package, \texttt{sf} (which stands for ``simple features''), is revolutionising the way that R does spatial analysis. This new package provides a new way of storing spatial objects in R and most recent R packages for spatial analysis and cartography are using it as the new default. It is easy to transform \texttt{sf} objects into \texttt{sp} objects, so that those packages that still don't use this new format can be used. But in this course we will emphasise the use of \texttt{sf} whenever possible. You can read more about the history of spatial packages and the \texttt{sf} package in the first two chapters of \href{https://geocompr.robinlovelace.net}{this book}.

Features can be thought of as ``things'' or objects that have a spatial location or extent; they may be physical objects like a building, or social conventions like a political state. Feature geometry refers to the spatial properties (location or extent) of a feature, and can be described by a point, a point set, a linestring, a set of linestrings, a polygon, a set of polygons, or a combination of these. The simple adjective of simple features refers to the property that linestrings and polygons are built from points connected by straight line segments. Features typically also have other properties (temporal properties, color, name, measured quantity), which are called feature attributes.

For more detailed insight I recommend reading the paper \href{https://journal.r-project.org/archive/2018/RJ-2018-009/RJ-2018-009.pdf}{Simple Features for R: Standardized Support for Spatial Vector Data}

\hypertarget{mapping-points-with-sf}{%
\subsection{Mapping points with sf}\label{mapping-points-with-sf}}

Let's get started with making some maps using \texttt{sf}. First, make sure you install the package, and then load with \texttt{library()} function.

\textbf{On Mac and Linux a few requirements must be met to install sf. These are described in the package's README at \url{github.com/r-spatial/sf}.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
\end{verbatim}

Now we can use the functions of sf in order to introduce geometries. Let's start with the points

\hypertarget{activity-3-creating-a-sf-object-of-points}{%
\subsubsection{Activity 3: Creating a sf object of points}\label{activity-3-creating-a-sf-object-of-points}}

WE know that we have two columns one for Longitude and one for Latitude, which pinpoint each crime event to a specific point, close to where it happened. Not \emph{quite} where it happened, as the data are anonymised (more on this later), but for our purposes here, we can assume this is the location of the crime.

To map these points, we can transform our ordinary dataframe into a simple features object.

To do so, we can use the \texttt{st\_as\_sf()} function, into which we need to specify what we are to transform (our dataframe), where the spatial data can be found (our columns which hold the latitude and longidude information), and also what coordinate reference system the object has (see above our discussion about projections and coordinate reference systems).

Latitude longitude coordinates specify location on the \textbf{WGS 84} CRS (remember I said to keep this one in mind!). We can tell R that this is our CRS of choice by including it's {[}EPSG identifier{]}
(\url{https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset}) as a parameter in our function. It is handy to know the more common EPSG identifiers. For example, for WGS84 the EPSG identifier is \emph{4326}. For British National Grid, the identifier is \emph{27700}. We will be making use of these numbers, so do note them down somewhere.

Putting it all together in practice, we can create a simple features object from our dataframe using the latitude and longitude columns:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes\_sf }\OtherTok{\textless{}{-}} \FunctionTok{st\_as\_sf}\NormalTok{(crimes,                                     }\CommentTok{\#dataframe}
                      \AttributeTok{coords =} \FunctionTok{c}\NormalTok{(}\StringTok{"longitude"}\NormalTok{, }\StringTok{"latitude"}\NormalTok{),        }\CommentTok{\#columns with coordinates}
                      \AttributeTok{crs =} \DecValTok{4326}\NormalTok{)                                 }\CommentTok{\#crs is WGS84}
\end{Highlighting}
\end{Shaded}

We can see that this is now a simple features object using the class() function the we see the result ``sf'':

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(crimes\_sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "sf"         "tbl_df"     "tbl"        "data.frame"
\end{verbatim}

You might also notice something else that is different between crimes and crimes\_sf. Have a look at the dimension (hint look in your `Environment' tab). Do you see? Discuss what you think is different, and write your answers in the shared google doc.

\hypertarget{activity-4-mapping-our-points}{%
\subsubsection{Activity 4: Mapping our points}\label{activity-4-mapping-our-points}}

Now that we have this sf object, how can we map it? I mentioned before about the graphical package \texttt{ggplot2}. We can use this, and its syntax, in order to map spatial data using the \texttt{geom\_sf()} geometry.

First, a quick refresher on ggplot and the grammar of graphics. The grammar of graphics upon which this package is based on defines various components of a graphic. Some of the most important are:

-\textbf{The data}: For using \texttt{ggplot2} the data has to be stored as a data frame or tibble.

-\textbf{The geoms}: They describe the objects that represent the data (e.g., points, lines, polygons, etc..). This is what gets drawn. And you can have various different types layered over each other in the same visualisation.

-\textbf{The aesthetics}: They describe the visual characteristics that represent data (e.g., position, size, colour, shape, transparency).

-\textbf{Facets}: They describe how data is split into subsets and displayed as multiple small graphs.

-\textbf{Stats}: They describe statistical transformations that typically summarise data.

Let's take it one step at the time.

Essentially the philosophy behind this is that all graphics are made up of layers. The package \texttt{ggplot2} is based on the grammar of graphics, the idea that you can build every graph from the same few components: a data set, a set of geoms---visual marks that represent data points, and a coordinate system.

Take this example (all taken from \emph{Wickham, H. (2010). A layered grammar of graphics. Journal of Computational and Graphical Statistics, 19(1), 3-28.})

You have a table such as:

\includegraphics{img/table.png}

You then want to plot this. To do so, you want to create a plot that combines the following layers:

\includegraphics{img/layers.png}

This will result in a final plot:

\includegraphics{img/combined.png}

Taking our crime data as an example, we would build up our plot as follows:

Load ggplot2 package

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

Data:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(crimes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ crime\_type))}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-35-1.pdf}

Geometry:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(crimes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ crime\_type)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-36-1.pdf}

Aesthetics:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(crimes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ crime\_type, }\AttributeTok{fill =}\NormalTok{ last\_outcome\_category)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-37-1.pdf}

And then you could add any facets (for example if we had more than one month of data) or any statistics (for example error bars) with facet and stats layers. One more thing I do want to show is tidying up your chart, you can add theme and clean up your labels and titles and colour scheme.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(crimes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ crime\_type, }\AttributeTok{fill =}\NormalTok{ last\_outcome\_category)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_bar}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Crime Type"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Number of cases"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{scale\_fill\_brewer}\NormalTok{(}\AttributeTok{type =} \StringTok{"qual"}\NormalTok{, }\AttributeTok{palette =} \DecValTok{3}\NormalTok{, }\AttributeTok{name =} \StringTok{"Outcome"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-38-1.pdf}

This is not the greatest graph you'll ever see, but it illustrates the process. Do read up on ggplot2 for example in Hadley Wickham's book R4DS \href{https://r4ds.had.co.nz/data-visualisation.html}{chapter on data visualisation}.

So how can we use this for spatial data? We can use the \texttt{geom\_sf()} function to do so.

\hypertarget{activity-5-mapping-our-points}{%
\subsubsection{Activity 5: Mapping our points}\label{activity-5-mapping-our-points}}

Using geom\_sf is slightly different to other geometries, for example how we used \texttt{geom\_bar()} above. First we initiate the plot with the \texttt{ggplot()} function but don't include the data in there. Instead, it is in the geometry where we add the data. And second we don't need to specify the mapping of x and y. Since this is in the geometry column of our spatial object. Like so:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ crimes\_sf)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-39-1.pdf}

And here we have a map of each point in our data set, each recorded crime in June 2019 in Greater Manchester.

Would you call this a map though? While it is presenting spatial data, there is not a lot of meaning being communicated. Point maps generally can be messy and their uses are specific to certain situations and cases, usually when you have fewer points, but here, these points are especially devoid of any meaning, as they are floating in a graph grid. SO let's give it a basemap.

We can do this by adding a layer to our graph object. Specifically we will use the \texttt{annotation\_map\_tile()} from the \texttt{ggspatial} package. This provides us with a static Open Street Map layer behind our data, giving it (some) more context.

Remember to load the package (and install if you haven't already)

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggspatial)}
\end{Highlighting}
\end{Shaded}

And then use the \texttt{annotation\_map\_tile()} function, making sure to place it before the geom\_sf points layer, so the background map is placed first, and the points on top of that:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
 \FunctionTok{annotation\_map\_tile}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ crimes\_sf)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Zoom: 9
\end{verbatim}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-41-1.pdf}

So what you see above is what we can call a \textbf{basemap}. The term basemap is seen often in GIS and refers to a collection of GIS data and/or orthorectified imagery that form the background setting for a map. The function of the basemap is to provide background detail necessary to orient the location of the map. Basemaps also add to the aesthetic appeal of a map.

In the lecture and some readings these are described as \emph{reference maps}. We often may want to use these reference maps as \textbf{basemaps} for our thematic and point maps. They may give us context and help with the interpretation. You can see above that you are seeing the \emph{Open Street Map} Basemap. This is one option but there are others.

Anyway let's leave out points for now, and move on to how we might map our lines and polygons.

\hypertarget{mapping-data-by-joining-it-to-sf-objects}{%
\subsection{Mapping data by joining it to sf objects}\label{mapping-data-by-joining-it-to-sf-objects}}

What about our other two columnds, location, and LSOAs? Well to put these on the map, we need a geometry representation of them. We will learn in this section where you may find these, how to download them, turn them into sf objects, and how to link your data to them to be able to map them.

\hypertarget{activity-6-finding-shapefiles}{%
\subsubsection{Activity 6: Finding shapefiles}\label{activity-6-finding-shapefiles}}

In this section you are going to learn how you take one of the most popular data formats for spatial objects, the \textbf{shapefile}, and read it into R. The shapefile was developed by ESRI, the developers and vendors or ArcGIS. And although many other formats have developed since and ESRI no longer holds the same market position it once occupied (though they're still the player to beat), shapefiles continue to be one of the most popular formats you will encounter in your work. You can read more about shapefiles \href{https://en.wikipedia.org/wiki/Shapefile}{here}.

We are going to learn here how to obtain shapefiles for British census geographies. In the class today we talked about the idea of neighborhouds and we explained how a good deal of sociological and criminological work traditionally used census geographies as proxies for neighbourhouds. As of today, they still are the geographical subdivisions for which we can obtain a greater number of attribute information (e.g., sociodemographics, etc.).

For this activity we will focus on the polygon (the LSOA) rather than the lines of the streets, but the logic is more or less the same. Remember above we talked about what is a census geography. You can read more about census boundary data \href{https://census.ukdataservice.ac.uk/use-data/guides/boundary-data}{here}. ``Boundary data are a digitised representation of the underlying geography of the census''. Census Geography is often used in research and spatial analysis because it is divided into units based on population counts, created to form comparable units, rather than other administrative boundaries such as wards or police force areas. However depending on your research question and the context for your analysis, you might be using different units. The hierarchy of the census geographies goes from Country to Local Authority to Middle Layer Super Output Area (MSOA) to Lower Layer Super Output Area (LSOA) to Output Area:

\includegraphics{img/maps_geography_types.png}

Here we will get some boundaries for Manchester. Let's use the LSOA level, so that we can link back to our crime data earily. These are geographical regions designed to be more stable over time and consistent in size than existing administrative and political boundaries. LSOAs comprise, on average, 600 households that are combined on the basis of spatial proximity and homogeneity of dwelling type and tenure.

So to get some boundary data, you can use the UK Data Service website. There is a simple \href{https://borders.ukdataservice.ac.uk/bds.html}{Boundary Data Selector} tool which we can use.

When you get to the link, you will see on the top there is some notification to help you with the boundary data selector. If in the future you are looking for boundary data and you are feeling unsure at any point, feel free to click on that note ``\textbf{How to use Boundary Data Selector}'' which will help to guide you.

For now, let's focus on the selector options. Here you can choose the country you want to select shapefiles for. We select ``England''. You can also choose the type of geography we want to use. Here we select ``Statistical Building Block'', as discussed above. And finally you can select when you want it for. If you are working with historical data, it makes sense to find boundaries that match the timescale for your data. Here we will be dealing with contemporary data, and therefore we want to be able to use the newest available boundary data.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/boundary_selector_1.png}

Once you have selected these options, click on the ``Find'' button. That will populate the box below:

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/boundary_selector_2.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Here you can select the boundaries we want. As discussed, we want the census lower super output areas. But again, your future choices here will depend on what data you want to be mapping.

Once you've made your choice, click on ``List Areas''. This will now populate the box below. We are here concerned with Manchester. However you can select more than one if you want boundaries for more than one area as well. Just hold down ``ctrl'' to select multiple areas individually, or the shift key to select everything in between.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/boundary_selector_3.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Once you've made your decision click on the ``Extract Boundary Data'' button. You will see the following message:

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/wait.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

You can bookmark, or just stay on the page and wait. How long you have to wait will depend on how much data you have requested to download.

When your data is read, you will see the following message:

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/download.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

You have to right click on the ``BoundaryData.zip'', and hit Save Target as on a PC or Save Link As on a Mac:

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/save_link_as.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

Navigate to the folder you have created for this analysis, and save the .zip file there. Extract the file contents using whatever you like to use to unzip compressed files.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# For example,}
\FunctionTok{unzip}\NormalTok{(}\StringTok{"BoundaryData.zip"}\NormalTok{, }\AttributeTok{exdir =} \StringTok{"BoundaryData"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

You should end up with a folder called ``BoundaryData''. Have a look at its contents:

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\includegraphics{img/folder_contents.png}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

So you can see immediately that there are some documentations around the usage of this shapefile, in the readme and the terms and conditions. Have a look at these as they will contain information about how you can use this map. For example, all your maps will have to mention where you got all the data from. So since you got this boundary data from the UKDS, you will have to note the following:

``Contains National Statistics data © Crown copyright and database right {[}year{]}
Contains OS data © Crown copyright {[}and database right{]} (year)''

You can read more about this in the terms and conditions document.

But then you will also notice that there are 4 files with the same name ``england\_oac\_2011''. \textbf{It is important that you keep all these files in the same location as each other!} They all contain different bits of information about your shapefile (and they are all needed):

\begin{itemize}
\tightlist
\item
  .shp --- shape format; the feature geometry itself - this is what you see on the map
\item
  .shx --- shape index format; a positional index of the feature geometry to allow seeking forwards and backwards quickly
\item
  .dbf --- attribute format; columnar attributes for each shape, in dBase IV format.
\item
  .prj --- projection format; the coordinate system and projection information, a plain text file describing the projection using well-known text format
\end{itemize}

Sometimes there might be more files associated with your shapefile as well, but we will not cover them here. So unlike when you work with spreadsheets and data in tabular form, which typically is just all included in one file; when you work with spatial data, you have to live with the required information living in separate files that need to be stored together. So, being tidy and organised is even more important when you carry out projects that involve spatial data. Please do remember the suggestions we provided last week as to how to organise your RStudio project directories.

\hypertarget{activity-7-reading-shapefiles-into-r}{%
\subsubsection{Activity 7: Reading shapefiles into R}\label{activity-7-reading-shapefiles-into-r}}

To read in your data, you will need to know the path to where you have saved it. Ideally this will be in your data folder in your project directory.

Let's create an object and assign it our shapefile's name:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Remember to use the appropriate pathfile in your case}
\NormalTok{shp\_name }\OtherTok{\textless{}{-}} \StringTok{"data/BoundaryData/england\_lsoa\_2011.shp"}
\end{Highlighting}
\end{Shaded}

Make sure that this is saved in your working directory, and you have set your working directory.

Now use the \texttt{st\_read()} function to read in the shapefile:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manchester\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(shp\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Reading layer `england_lsoa_2011' from data source `/Users/reka/Desktop/crime_mapping_textbook/data/BoundaryData/england_lsoa_2011.shp' using driver `ESRI Shapefile'
## Simple feature collection with 282 features and 3 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 378833.2 ymin: 382620.6 xmax: 390350.2 ymax: 405357.1
## projected CRS:  OSGB 1936 / British National Grid
\end{verbatim}

Now you have your spatial data file. You can have a look at what sort of data it contains, the same way you would view a dataframe, with the \texttt{View()} function:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{View}\NormalTok{(manchester\_lsoa)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 282
## Columns: 4
## $ label    <chr> "E08000003E02001062E01005066", "E08000003E02001092E0100507...
## $ name     <chr> "Manchester 018E", "Manchester 048C", "Manchester 018A", "...
## $ code     <chr> "E01005066", "E01005073", "E01005061", "E01005062", "E0100...
## $ geometry <POLYGON [m]> POLYGON ((384850 397432, 38..., POLYGON ((382221.1...
\end{verbatim}

And of course, since it's spatial data, you can map it using the geom\_sf() function, as we did with our points:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ manchester\_lsoa)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-47-1.pdf}

Great, we now have an outline of the LSOAs in Manchester. Notice how the shape is different to that of the points in our crime data. Why do you think this is? Discuss and write your thoughts in the shared google doc.

\hypertarget{activity-8-data-wrangling-with-dplyr}{%
\subsubsection{Activity 8: Data wrangling with dplyr}\label{activity-8-data-wrangling-with-dplyr}}

In order to map crimes to LSOAs we might want to take a step back and think about unit of analysis at which our data are collected. In our original dataframe of crimes, we saw that each crime incident is one row. So the unit of anlysis is each crime. Since we were looking to map each crime at the location it happened, we used the latitude and longitude supplied with each one, and this supplied a geometry each for each crime type.

However, when we are looking to map our data to LSOA level, we need to match the crime data to the geometry we wish to display.

Have a look at the manchester\_lsoa object we mapped above. How many rows (observations) does it have? You can check this by looking in the Environment pane, or by using the \texttt{nrow()} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{nrow}\NormalTok{(manchester\_lsoa)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 282
\end{verbatim}

You can see this has 282 rows. This means we have geometries for 282 LSOAs.

On the other hand, our crimes dataframe has 32058 rows, one for each crime (observation). So how can we match these up? The answer lies in thinking about what it is that our map using LSOAs as our unit of analysis will be able to tell us. Think of other maps of areas - what are they usually telling you? Usually we expect to see crimes per neighbourhood - something like this. So our unit of analysis needs to be LSOA, and for each one we need to know how many crimes occurred in that area.

To achieve this, we will wrangle our data using functions from the \texttt{dplyr} package. This is a package for conducting all sorts of operations with data frames. We are not going to cover the full functionality of dplyr (which you can consult in \href{https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html}{this tutorial}), but we are going to cover three different very useful elements of dplyr: the select function, the group\_by function, and the piping operator.

First load the library:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

The \texttt{select()} function provides you with a simple way of subsetting columns from a data frame. So, say we just want to use one variable, lsoa\_code, from the crimes dataframe and store it in a new object we could write the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{new\_object }\OtherTok{\textless{}{-}} \FunctionTok{select}\NormalTok{(crimes, lsoa\_code)}
\end{Highlighting}
\end{Shaded}

We can also use the \texttt{group\_by()} function for performing group operations. Essentially this function ask R to group cases within categories and then do something with those grouped cases. So, say, we want to count the number of cases within each LSOA, we could use the following code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#First we group the cases by LSOA code and stored this organised data into a new object}
\NormalTok{grouped\_crimes }\OtherTok{\textless{}{-}} \FunctionTok{group\_by}\NormalTok{(new\_object, lsoa\_code)}

\CommentTok{\#Then we could count the number of cases within each category and use the summarise function to print the results}
\FunctionTok{summarise}\NormalTok{(grouped\_crimes, }\AttributeTok{count =} \FunctionTok{n}\NormalTok{())}

\CommentTok{\#We could infact create a new dataframe with these results}

\NormalTok{crime\_per\_LSOA }\OtherTok{\textless{}{-}} \FunctionTok{summarise}\NormalTok{(grouped\_crimes, }\AttributeTok{count =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

As you can see we can do what we wanted, create a new dataframe with the required info, but if we do this we are creating many objects that we don't need, one at each step. Instead there is a more efficient way of doing this, without so many intermediate steps clogging up our environment with unnecessary objects. That's where the piping operator comes handy. The piping operator is written like \texttt{\%\textgreater{}\%} and it can be read as ``and then''. Look at the code below:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#First we say create a new object called crime\_per\_lsoa, and then select only the LSOA.code column to exist in this object, and then group this object by the LSOA.code, and then count the number of cases within each category, this is what I want in the new object.}

\NormalTok{crimes\_per\_lsoa }\OtherTok{\textless{}{-}}\NormalTok{ crimes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(lsoa\_code) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count=}\FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

Essentially we obtain the same results but with more streamlined and elegant code, and not needing additional objects in our environment.

And now we have a new object, \emph{crimes\_per\_lsoa} if we have a look at this one, we can now see what each row represents one LSOA, and next to it we have a variable for the number of crimes from each area. We created a new dataframe from a frequency table, and as each row of the crimes data was one crime, the frequency table tells us the number of crimes which occurred in each LSOA.

Those of you playing close attention might note that there are still more observations in this dataframe (1671) than in the manchester\_lsoas one (282). Why do you think that might be? Look back at how you answered the final question for the previous activity for a hint.

\hypertarget{activity-9-join-data-to-sf-object}{%
\subsubsection{Activity 9: Join data to sf object}\label{activity-9-join-data-to-sf-object}}

Our next task is to link our crimes data to our sf spatial object to help us map this. Notice anything similar between the data from the shapefile and the frequency table data we just created? Do they share a column?

Yes! You might notice that the \texttt{lsoa\_code} field in the crimes data matches the values in the \texttt{code} field in the spatial data. In theory we could join these two data tables.

So how do we do this? Well what you can do is to link one data set with another. Data linking is used to bring together information from different sources in order to create a new, richer dataset. This involves identifying and combining information from corresponding records on each of the different source datasets. The records in the resulting linked dataset contain some data from each of the source datasets. Most linking techniques combine records from different datasets if they refer to the same entity (an entity may be a person, organisation, household or even a geographic region.)

You can merge (combine) rows from one table into another just by pasting them in the first empty cells below the target table---the table grows in size to include the new rows. And if the rows in both tables match up, you can merge columns from one table with another by pasting them in the first empty cells to the right of the table---again, the table grows, this time to include the new columns.

Merging rows is pretty straightforward, but merging columns can be tricky if the rows of one table don't always line up with the rows in the other table. By using \texttt{left\_join()} from the \texttt{dplyr} package, you can avoid some of the alignment problems.

\texttt{left\_join()} will return all rows from x, and all columns from x and y. Rows in x with no match in y will have NA values in the new columns. If there are multiple matches between x and y, all combinations of the matches are returned.

So we've already identified that both our crimes data, and the spatial data contain a column with matching values, the codes for the LSOA that each row represents.

\includegraphics{img/fn2187.png}

\textbf{You need a unique identifier to be present} for each row in all the data sets that you wish to join. This is how R knows what values belong to what row! What you are doing is matching each value from one table to the next, using this unique identified column, that exists in both tables. For example, let's say we have two data sets from some people in Hawkins, Indiana. In one data set we collected information about their age. In another one, we collected information about their hair colour. If we collected some information that is unique to each observation, and this is the \emph{same} in both sets of data, for example their names, then we can link them up, based on this information. Something like this:

\includegraphics{img/merge_logic_1.png}

And by doing so, we produce a final table that contains all values, lined up \emph{correctly} for each individual observation, like this:

\includegraphics{img/merge_logic_2.png}

This is all we are doing, when merging tables, is we are making use that we line up the correct value for all the variables, for all our observations.

Why are we using \emph{left} join though? There is a \href{http://stat545.com/bit001_dplyr-cheatsheet.html}{whole family of join functions as part of dplyr} which join data sets. There is also a right\_join, and an inner\_join and an outer\_join and a full\_join. But here we use left join, because that way we keep all the rows in x (the left-hand side dataframe), and join to it all the matched columns in y (the right-hand side dataframe).

So let's join the crimes data to the spatial data, using left\_join():

We have to tell left\_join what are the dataframes we want to join, as well as the names of the columns that contain the matching values in each one. This is ``code'' in the manchester\_lsoa dataframe and ``lsoa\_code'' in the crimes\_per\_lsoa dataframe. Like so:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manchester\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(manchester\_lsoa, crimes\_per\_lsoa, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"code"}\OtherTok{=}\StringTok{"lsoa\_code"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Now if you have a look at the data again, you will see that the column of number of crimes (n) has been added on.

\hypertarget{activity-10-mapping-our-data-at-polygon-level}{%
\subsubsection{Activity 10: Mapping our data at polygon level}\label{activity-10-mapping-our-data-at-polygon-level}}

Now that we have joined the crimes data to the geometry, you can use this to make our map!

Remember our original empty map:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
\FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ manchester\_lsoa)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-54-1.pdf}

Well now, since we have the column (varaible) for number of crimes here, we can use that to share the polygons based on how many crimes there are in each LSOA. We can do this by specifying the \texttt{fill=} parameter of the \texttt{geom\_sf} function.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
\FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ manchester\_lsoa, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ count))}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-55-1.pdf}

We can add a basemap, and adjust the colour scheme, and even the opacity to see under our shape files.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{annotation\_map\_tile}\NormalTok{() }\SpecialCharTok{+}  \CommentTok{\# add basemap}
\FunctionTok{geom\_sf}\NormalTok{(}\AttributeTok{data =}\NormalTok{ manchester\_lsoa, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill =}\NormalTok{ count), }\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+} \CommentTok{\# alpha sets the opacity}
  \FunctionTok{scale\_fill\_gradient2}\NormalTok{(}\AttributeTok{name =}\StringTok{"Number of crimes"}\NormalTok{) }\CommentTok{\#use scale\_fill\_gradient2() for a different palette and name the variable on the legend}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Zoom: 10
\end{verbatim}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-56-1.pdf}

\hypertarget{summary-1}{%
\section{Summary}\label{summary-1}}

In this session we had a play around with some regular old crime data and discovered how we can use the sf package in R to assign it a geometry (both at point and polygon level), and how that can help us visualise our results. We covered some very important concepts such as projections and coordinate reference systems, and we had a play at acquiring shapefiles which can help us visualise our data. We had a think about units of analysis, and how that will affect how we visualise our data.

Make sure to complete the homework tasks available on Blackboard, and once you have done that, and read all the readings and watched all the videos, complete your homework quiz.

Next week we will spend a bit of more time discussing how to make good choices when producing maps.

\hypertarget{thematic-maps-in-r}{%
\chapter{Thematic maps in R}\label{thematic-maps-in-r}}

\hypertarget{intro-and-recap}{%
\section{Intro and recap}\label{intro-and-recap}}

Last week we showed you fairly quickly how to create maps by understanding how data may have spatial elements, and how that can be linked to geometries.

This week we will get to know how to think about thematic maps, and how to apply your learning to creating your own maps of this variety. In our lecture videos this week we discuss in detail issues with choropleth maps. So the focus of today's lab is going to be around thematic maps and some of the choices we discussed.

We will also introduce faceting and \textbf{small multiples}, which is a format for comparing the geographical distribution of different social phenomena. For this session we will be using the spatial object that you created last week and complement it with additional information from the census. So first of all you will have to rerun the code you used to create the \emph{manchester\_lsoa} \texttt{sf} object. Apart from doing so, you want to start your session loading the libraries you know for sure you will need:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(sf)}
\FunctionTok{library}\NormalTok{(janitor)}
\FunctionTok{library}\NormalTok{(tmap)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

You may not remember all of what you did to generate that file so let's not waste time and just cut and paste from below (but try to remember what each of the lines of code is doing and if you are not clear look at the notes from last week). Imagine you had to do all of this again by pointing and clicking in a graphical user interface rather than just sending the code to the console! As you will see time and time again, code in the end is a much more efficient way of talking to a computer.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/2019{-}06{-}greater{-}manchester{-}street.csv"}\NormalTok{)}

\CommentTok{\#The following assumes you have a subdirectory called BoundaryData in your data folder, if not then you will need to change to the pathfile where you store your LSOA shapefile}
\NormalTok{shp\_name }\OtherTok{\textless{}{-}} \StringTok{"data/BoundaryData/england\_lsoa\_2011.shp"}
\NormalTok{manchester\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(shp\_name)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Reading layer `england_lsoa_2011' from data source `/Users/reka/Desktop/crime_mapping_textbook/data/BoundaryData/england_lsoa_2011.shp' using driver `ESRI Shapefile'
## Simple feature collection with 282 features and 3 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 378833.2 ymin: 382620.6 xmax: 390350.2 ymax: 405357.1
## projected CRS:  OSGB 1936 / British National Grid
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crimes\_per\_lsoa }\OtherTok{\textless{}{-}}\NormalTok{ crimes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{clean\_names}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(lsoa\_code) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(lsoa\_code) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count=}\FunctionTok{n}\NormalTok{())}

\NormalTok{manchester\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(manchester\_lsoa, crimes\_per\_lsoa, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"code"}\OtherTok{=}\StringTok{"lsoa\_code"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

You may not want to have to go through this process all the time. One thing you could do is to save the \emph{manchester\_lsoa} object as a physical file in your machine. You can use the \texttt{st\_write()} function from the \texttt{sf} package to do this. If we want to write into a shapefile format we would do as shown below:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{st\_write}\NormalTok{(manchester\_lsoa, }\StringTok{"data/BoundaryData/manchester\_crime\_lsoa.shp"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Notice how four files have appeared in your working directory, in your ``BoundaryData''" subdirectory or whatever you called it. Remember what we said last week about shapefiles, there are a collection of files that need to be kept together.

If you wanted to bring this shapefile back into R at any future point, you would only need to use the \texttt{st\_read()} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manchester\_crime\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{st\_read}\NormalTok{(}\StringTok{"data/BoundaryData/manchester\_crime\_lsoa.shp"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Reading layer `manchester_crime_lsoa' from data source `/Users/reka/Desktop/crime_mapping_textbook/data/BoundaryData/manchester_crime_lsoa.shp' using driver `ESRI Shapefile'
## Simple feature collection with 282 features and 4 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 378833.2 ymin: 382620.6 xmax: 390350.2 ymax: 405357.1
## projected CRS:  Transverse_Mercator
\end{verbatim}

\hypertarget{activity-1-spot-the-difference}{%
\subsubsection{Activity 1: Spot the difference}\label{activity-1-spot-the-difference}}

Before we carry on, can you tell what is different between \emph{manchester\_lsoa.shp} and \emph{manchester\_crime\_lsoa.shp} that you now have saved for working with? Discuss in your groups, and write your thoughts on the shared google doc.

\hypertarget{creating-thematic-maps}{%
\section{Creating thematic maps}\label{creating-thematic-maps}}

Today we are going to introduce the \texttt{tmap} package. This package was developed to easily produce thematic maps. It is inspired by the \texttt{ggplot2} package and the layered grammar of graphics. It was written by Martjin Tennekes a Dutch data scientist. There are a number of \href{https://cran.r-project.org/web/packages/tmap/index.html}{vignettes in the CRAN repository} and the \href{https://github.com/mtennekes/tmap}{GitHub repo for this package} that you can explore. GitHub is a collaborative website used by software developers and data scientist, also contains a useful \emph{readme} section with additional resources to familiarise yourself with this package. Each map can be plotted as a static map (\emph{plot mode}) and shown interactively (\emph{view mode}) as we briefly saw last week. We will start by focusing on static maps.

Every time you use this package you will need a line of code that specifies the spatial object you will be using. Although originally developed to handle \texttt{sp} objects only, it now also has support for \texttt{sf} objects. For specifying the spatial object we use the \texttt{tm\_shape()} function and inside we specify the name of the spatial object we are using. On its own, this will do nothing apparent. No map will be created. We need to add additional functions to specify what we are doing with that spatial object. If you try to run this line on its own, you'll get an error telling you you must ``Specify at least one layer after each tm\_shape''.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa)}
\end{Highlighting}
\end{Shaded}

The main plotting method consists of elements that we can add. The first element is the \texttt{tm\_shape()} function specifying the spatial object, and then we can add a series of elements specifying layers in the visualisation. They can include polygons, symbols, polylines, raster, and text labels as base layers. We will add a polygon using \texttt{tm\_polygon()}. As noted, with \texttt{tmap} you can produce both static and interactive maps. The interactive maps rely on \texttt{leaflet}. You can control whether the map is static or interactive with the \texttt{tmap\_mode()} function. If you want a static map you pass \texttt{plot} as an argument, if you want an interactive map you pass \texttt{view} as an argument. Let's create a static map first.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tmap\_mode}\NormalTok{(}\StringTok{"plot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tmap mode set to plotting
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_polygons}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-62-1.pdf}

Given that we are not passing any additional arguments all we are getting is a map with the shape of the geographies that we are representing, the census LSOAs for Manchester city. We can, however, ask R to produce a choropleth map by mapping the values of a variable in our data table using colour. In tmap we need to denote our variables between quotes. The first argument we pass then would be the name of the variable we want to visualise. If you remember we have a count for crimes (``count''), so let's visualise that by creating a thematic map.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_polygons}\NormalTok{(}\StringTok{"count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-63-1.pdf}

We have been using \texttt{tm\_polygons()} but we can also add the elements of a polygon map using different functions that break down what we represent here. In the map above you see the polygons have a dual representation, the borders are represented by lines and the colour is mapped to the intensity of the quantitative variable we are representing. With darker colours representing more of the variable, the areas with more crimes. Instead of using \texttt{tm\_polygon()} we can use the related functions \texttt{tm\_fill()}, for the colour inside the polygons, and \texttt{tm\_borders()}, for the aesthetics representing the border of the polygons. Say we find the borders distracting and we want to set them to be transparent. In that case we could just use \texttt{tm\_fill()}.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-64-1.pdf}

As you can see here, the look is a bit cleaner. We don't need to get rid of the borders completely. Perhaps we want to make them a bit more translucent. We could do that by adding the border element but making the drawing of the borders less pronounced.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-65-1.pdf}

The alpha parameter that we are inserting within \texttt{tm\_borders()} controls the transparency of the borders, we can go from 0 (totally transparent) to 1 (not transparent). You can play around with this value and see the results.

Notice in the last few maps we did not have to specify whether we wanted the map to be static or interactive. When you use \texttt{tmap}, R will remember the mode you want to use. So once you specify \texttt{tmap\_mode("plot")}, all the subsequent maps will be static. It is only when you want to change this behaviour that you would need another \texttt{tmap\_mode} call.

Notice as well that the legend in this map is (a) not very informative and (b) located in a place that is less than optimal, since it covers part of the map. We can add a title within the \texttt{tm\_fill} to clarify what count is and we can use the \texttt{tm\_layout()} function to control the appearance of the legend. This later function \texttt{tm\_layout} allows you to think about many of the more general cosmetics of the map.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Crime counts"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{main.title =} \StringTok{"Crime in Manchester City, Nov/2017"}\NormalTok{, }\AttributeTok{main.title.size =} \FloatTok{0.7}\NormalTok{ ,}
            \AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }\AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-66-1.pdf}

We are also going to change the current style of the maps by making them more friendly to colour blind people. We can use the tmap\_style() function to do so.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{current\_style }\OtherTok{\textless{}{-}} \FunctionTok{tmap\_style}\NormalTok{(}\StringTok{"col\_blind"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## tmap style set to "col_blind"
\end{verbatim}

\begin{verbatim}
## other available styles are: "white", "gray", "natural", "cobalt", "albatross", "beaver", "bw", "classic", "watercolor"
\end{verbatim}

See how the map changes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Crime counts"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{main.title =} \StringTok{"Crime in Manchester City, Nov/2017"}\NormalTok{, }\AttributeTok{main.title.size =} \FloatTok{0.7}\NormalTok{ ,}
            \AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }\AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-68-1.pdf}

\hypertarget{classification-systems-for-thematic-maps}{%
\section{Classification systems for thematic maps}\label{classification-systems-for-thematic-maps}}

In thematic mapping, you have to make some key decisions, the most important one being how to display your data. When mapping a quantitative varaible, we have to ``bin'' this variable into groups. For example in the map we made below, the default binning applied was to display LSOAs grouped into those with 1 -200, 201-400, 401-600 and 601-800 crimes. But why these? How were these groupings decided upon?

The quantitative information, being directly measured (e.g.~total population) or derived (e.g.~population density), is usually classified before its symbolization in a thematic map. Theoretically, accurate classes that best reflect the distributional character of the data set can be calculated.

\textbf{The equal interval} (or equal step) classification method divides the range of attribute values into equally sized classes. What this means is that the values are divided into equal groups. This approach is best for continuous data.

\textbf{The quantile map} bin the same count of features into each of its classes. This classification method places equal numbers of observations into each class. This method is best for data that is evenly distributed across its range.

\textbf{The natural breaks (or Jenks)} classification method utilizes an algorithm to group values in classes that are separated by distinct break points. It is an optimisation method which takes an iterative approach to its groupings to achieve least variation within each class. This method is best used with data that is unevenly distributed but not skewed toward either end of the distribution.

\textbf{The standard deviation} map uses the standard deviation (standardised measure of observations' deviation from the mean) to bin the observations into classes. This classification method forms each class by adding and subtracting the standard deviation from the mean of the dataset. It is best suited to be used with data that conforms to a normal distribution.

The above should be familiar from your reading, but if you would like another angle I recommend a browse of \href{https://gisgeography.com/choropleth-maps-data-classification/}{this guide} which has some nice visualisations.

\hypertarget{activity-2-comparing-classifications}{%
\subsubsection{Activity 2: Comparing classifications}\label{activity-2-comparing-classifications}}

For comparing the effects of using different methods we can use small multiples. Small multiples is simply a way of reproducing side by sides similar maps for comparative purposes. To be more precise small multiples are \emph{sets of charts of the same type, with the same scale, presented together at a small size and with minimal detail, usually in a grid of some kind}. The term was at least popularized by Edward Tufte, appearing first in his \emph{Visual Display of Quantitative Information} in 1983.

There are different ways of creating small multiples with \texttt{tmap} as you could see in the vignettes for the package, some of which are quicker but a bit more restricted. Here we are going to use \texttt{tmap\_arrange()}. With \texttt{tmap\_arrange()} first we need to create the maps we want and then we arrange them together.

Let's make four maps, each one using a different classification method: Equal interval, QUantile, Natural breaks (Jenks), and Standard Deviation.

For each map, instead of visualising them one by one, just assign them to a new object. Let's call them \emph{map1}, \emph{map2}, \emph{map3} and \emph{map4}.

So let's make \emph{map1}. This will create a thematic map using equal intervals:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map1 }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+}                   \CommentTok{\#use tm\_shape function to specify spatial object}
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{style=}\StringTok{"equal"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Equal"}\NormalTok{) }\SpecialCharTok{+}  \CommentTok{\#use tm\_fill to specify variable, classification method, and give the map a title}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{),   }\CommentTok{\#use tm\_layout to make the legend look nice}
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{,}
            \AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now create \emph{map2}, with the jenks method often preferred by geographers:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map2 }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{style=}\StringTok{"jenks"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Jenks"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{,}
            \AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now create \emph{map3}, with the quantile method often preferred by epidemiologists:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map3 }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{style=}\StringTok{"quantile"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Quantile"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{,}
            \AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

And finally make \emph{map4}, standard deviation map, which maps the values of our variable to distance to the mean value.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map4 }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{style=}\StringTok{"sd"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Standard Deviation"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{alpha=}\FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{,}
            \AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Notice that we are not plotting the maps, we are storing them into R objects (map1 to map4). This way they are saved, and you can call them later, which is what we need in order to plot them together using the \texttt{tmap\_arrange()} function.

So if you wanted to map just \emph{map3} for example, all you need to do, is call the map3 object. Like so:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{map3}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-73-1.pdf}

But now we will plot all 4 maps together, arranged using the \texttt{tmap\_arrange()} function. Like so:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#And now we deploy tmap\_arrange to plot these maps together}
\FunctionTok{tmap\_arrange}\NormalTok{(map1, map2, map3, map4) }
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-74-1.pdf}

There are some other classification methods built into tmap which you can experiment with if you'd like. Your discrete gradient options are ``cat'', ``fixed'', ``sd'', ``equal'', ``pretty'', ``quantile'', ``kmeans'', ``hclust'', ``bclust'', ``fisher'', ``jenks'', ``dpih'', ``headtails'', and ``log10\_pretty''. A numeric variable is processed as a categorical variable when using ``cat'', i.e.~each unique value will correspond to a distinct category.

Taken from the help file we can find more information about these, for example the ``kmeans'' style uses kmeans clustering technique (a form of unsupervised statistical learning) to generate the breaks. The ``hclust'' style uses hclust to generate the breaks using hierarchical clustering and the ``bclust'' style uses bclust to generate the breaks using bagged clustering. These approaches are outisde the scope of what we cover, but just keep in mind that there are many different ways to classify your data, and you must think carefully about the choice you make, as it may affect your readers' conclusions from your map.

\hypertarget{using-graduated-symbols}{%
\section{Using graduated symbols}\label{using-graduated-symbols}}

Some of the literature on thematic cartography highlights how counts, like the ones above, are best represented using graduated symbols rather than choropleth maps (using colour, as we did above). So let's try to go for a more appropriate representation. In \texttt{tmap} you can use tm\_symbols for this. We will use \texttt{tm\_borders} to provide some context.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_bubbles}\NormalTok{(}\StringTok{"count"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-75-1.pdf}

First thing you see is that we loose the context (provided by the polygon borders) that we had earlier. The \texttt{border.lwd} argument set to NA in the \texttt{tm\_symbols()} is asking R not to draw a border to the circles. Whereas \texttt{tm\_borders()} brings back a layer with the borders of the polygons representing the different LSOAs in Manchester city. Notice how I am modifying the transparency of the borders with the alpha parameter.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+}                         \CommentTok{\#use tm\_shape function to specify spatial object}
  \FunctionTok{tm\_bubbles}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{border.lwd=}\ConstantTok{NA}\NormalTok{) }\SpecialCharTok{+}              \CommentTok{\#use tm\_bubbles to add the bubble visualisation, but set the \textquotesingle{}border.lwd\textquotesingle{} parameter to NA, meaning no symbol borders are drawn}
  \FunctionTok{tm\_borders}\NormalTok{(}\AttributeTok{alpha=}\FloatTok{0.1}\NormalTok{) }\SpecialCharTok{+}                           \CommentTok{\#add the LSOA border outlines using tm\_borders, but set their transparency using the alpha parameter (0 is totally transparent, 1 is not at all)}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{), }\CommentTok{\#use tm\_layout to make the legend look nice}
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{,}
            \AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-76-1.pdf}

\hypertarget{mapping-rates-rather-than-counts}{%
\section{Mapping rates rather than counts}\label{mapping-rates-rather-than-counts}}

In much of our readings we have now seen the importance to map rates rather than counts of things, and that is for the simple reason that population is not equally distributed in space. That means that if we do not account for how many people are somewhere, we end up mapping population size rather than our topic of interest. As always, there is a relevant xkcd for that:

\begin{figure}
\centering
\includegraphics{https://imgs.xkcd.com/comics/heatmap.png}
\caption{\url{https://xkcd.com/1138/}}
\end{figure}

In specific to crime mapping, there is an ongoing issue of the \emph{denominators dilemma} which has been cropping up in your reading. This is concerned with choosing the most appropriate measure for calculating crime rates. The best measure is one which captures opportunities. You read about some approaches to capturing ambient population for example to estimate risk for on-street crimes. Whatever denominator you choose, you will usually want to make a case as to why that is the best representation of the opportunities for the crime type you're interested in.

\hypertarget{activity-3-getting-population-data-from-the-census}{%
\subsubsection{Activity 3: Getting population data from the census}\label{activity-3-getting-population-data-from-the-census}}

Last week you learned how to obtain crime data from the police UK website and you also developed the skills to obtain shapefiles with the boundaries for the UK census geographies. Specifically you learnt how to obtain LSOAs boundaries. Then we taught you how to join these data tables using \texttt{dplyr}. If you open your \emph{manchester\_lsoa} object you will see that at the moment you only have one field in this dataframe providing you with statistical information. However, there is a great deal of additional information that you could add to these data frame. Given that you are using census geographies you could add to it all kind of socio demographic variables available from the census.

You may want to watch \href{https://www.youtube.com/watch?v=AzK04BOFd_s\#t=17}{this 4 minute video} to get a sense for how to obtain the data. If you don't have headphones make sure you read \href{http://infuse.ukdataservice.ac.uk/help/tutorial.html}{this brief tutorial} before carrying on. We are going to get some data for Manchester city LSOAs. Let me warn you though, the census data portal is one of the closest things to hell you are going to come across on the internet. Using it will be a good reminder of why point and click interfaces can suck the life out of you.

From the main Infuse portal select the 2011 census data then when queried pick selection by geography:

\includegraphics{img/infuse1.png}

Expand the local authorities and select Manchester. Expand Manchester and select LSOAs:

\includegraphics{img/infuse2.png}

At the bottom of the page click in \emph{Add} and then where it says \emph{Next}. Now big tip. Do not press back in your browser. If you need to navigate back once you get to that point use the \emph{previous} button at the bottom of the screen. You will regret it if you don't do this.

Now you will need to practice navigating the Infuse system to generate a data table that has a number of relevant fields we are going to use today and at a later point this semester. I want you to create a file with information about: the resident population, the workday population, and the number of deprivation households. This will involve some trial and error but you should end up with a selection like the one below:

\includegraphics{img/infuseselection.png}

Once you have those fields click next to get the data and download the file. Unzip them and see you have your .csv file. Save this into your data subfolder in your project directory. Use \texttt{read\_csv()} function from the \texttt{readr} package to import this data.

\begin{verbatim}
## Warning: Missing column names filled in: 'X14' [14]
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\NormalTok{census\_lsoa\_m }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"data/Data\_AGE\_APPSOCG\_DAYPOP\_UNIT\_URESPOP.csv?dl=1"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Notice that even all the variables that begin with ``f'' are numbers they have been read into R as characters. This is to do with the fact the first two lines do not represent cases and do have characters. R is coercing everything into character vectors. Let's clean this a bit.

First we will get rid of the first two rows. In particular we will use the \emph{slice()} function from \emph{dplyr}. We can use slice to select cases based on row number. We don't need the first two rows so we can select rows 3 to 284.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{census\_lsoa\_m }\OtherTok{\textless{}{-}} \FunctionTok{slice}\NormalTok{(census\_lsoa\_m, }\DecValTok{3}\SpecialCharTok{:}\DecValTok{284}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

There are also fields that we don't need. We only need the variables beginning with F for those have the information about population and deprivation, and the \emph{GEO\_CODE} tag which will allow us to link this table to the \emph{manchester\_lsoa} file.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{census\_lsoa\_m }\OtherTok{\textless{}{-}} \FunctionTok{select}\NormalTok{(census\_lsoa\_m, GEO\_CODE, F996}\SpecialCharTok{:}\NormalTok{F323339)}
\end{Highlighting}
\end{Shaded}

We also want to convert the character variables into numeric ones, whilst preserving the \emph{id} as a character variable. For this we will use the \texttt{lapply} function. This is a convenient function that will administer a function to the elements we pass as an argument. In this case we are asking to apply the \texttt{as.numeric()} function to the columns 2 to 9 of the \emph{census\_lsoa\_m} data frame. This is turning into numeric all those character columns.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{census\_lsoa\_m[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{9}\NormalTok{] }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(census\_lsoa\_m[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{9}\NormalTok{], as.numeric)}
\end{Highlighting}
\end{Shaded}

The only problem we have now is that the variable names are not very informative. If you look at the metadata file that came along you can see that there is a key there to understand what these variables mean. We could use that information to create more meaningful names for the variables we have. We will use the \texttt{rename()} function from the \texttt{dplyr} package to do the renaming:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{census\_lsoa\_m }\OtherTok{\textless{}{-}} \FunctionTok{rename}\NormalTok{(census\_lsoa\_m, }\AttributeTok{tothouse =}\NormalTok{ F996, }\AttributeTok{notdepr =}\NormalTok{ F997, }\AttributeTok{depriv1 =}\NormalTok{ F998,}
                        \AttributeTok{depriv2 =}\NormalTok{ F999, }\AttributeTok{depriv3 =}\NormalTok{ F1000, }\AttributeTok{depriv4 =}\NormalTok{ F1001, }\AttributeTok{respop =}\NormalTok{ F2384,}
                        \AttributeTok{wkdpop =}\NormalTok{ F323339)}
\end{Highlighting}
\end{Shaded}

The rename function takes as the first argument the name of the dataframe. Then for each variable you want to change you write down the new name followed by the old name. Now that we have the file ready we can link it to our \emph{manchester\_lsoa} file using code we learned last week. We use again the \texttt{left\_join()} function to add to the \emph{manchester\_lsoa} dataframe the variables that are present in the \emph{census\_lsoa\_m}. The first argument in the function is the name of the dataframe to which we want to add fields, the second argument the name of the dataframe from which those fields come, and then you need to specify using ``by'' the name of the variables on each of these two dataframes that have the id variable that will allow us to ensure that we are linking the information across the same observations.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manchester\_crime\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{left\_join}\NormalTok{(manchester\_crime\_lsoa, census\_lsoa\_m, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"code"}\OtherTok{=}\StringTok{"GEO\_CODE"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

And there you go\ldots{} Now you have a datafile with quite a few pieces of additional information about LSOAs in Manchester. The next step is to use this information.

\hypertarget{activity-4-computing-crime-rates}{%
\subsubsection{Activity 4: Computing crime rates}\label{activity-4-computing-crime-rates}}

Ok, so now we have a field that provides us with the number of crimes and two alternative counts of population for each LSOA in Manchester in the same dataframe. We could compute the rate of crime in each using the population counts as our denominator. Let's see how the maps may compare using these different denominators.

But first we need to create new variables. For this we can use the \texttt{mutate()} function from the \texttt{dplyr} package. This is a very helpful function to create new variables in a dataframe based on transformations or mathematical operations performed in other variables within the dataframe. In this function, the first argument is the name of the data frame, and then we can pass as arguments all new variables we want to create as well as the instructions as to how we are creating those variables.

First we want to create a rate using the usual residents, since crime rates are often expressed by 100,000 inhabitants we will multiply the division of the number of crimes by the number of usual residents by 100,000. We will then create another variable, \emph{crimr2}, using the workday population as the denominator. We will store this new variables in our existing \emph{manchester\_lsoa} dataset. You can see that below then I specify the name of a new variable \emph{crimr1} and then I tell the function I want that variable to equal (for each case) the division of the values in the variable \emph{count} (number of crimes) by the variable \emph{respop} (number of people residing in the area) and then we multiply the result of this division by 100,000 to obtain a rate expressed in those terms. Then we do likewise for the alternative measure of crime.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{manchester\_crime\_lsoa }\OtherTok{\textless{}{-}} \FunctionTok{mutate}\NormalTok{(manchester\_crime\_lsoa, }\AttributeTok{crimr1 =}\NormalTok{ (count}\SpecialCharTok{/}\NormalTok{respop)}\SpecialCharTok{*}\DecValTok{100000}\NormalTok{, }\AttributeTok{crimr2 =}\NormalTok{ (count}\SpecialCharTok{/}\NormalTok{wkdpop)}\SpecialCharTok{*}\DecValTok{100000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

And now we have two new variables, one for crime rate with residential population as a denominator, and another with workplace population as a denominator.

\hypertarget{activity-5-mapping-crime-rates}{%
\subsubsection{Activity 5: Mapping crime rates}\label{activity-5-mapping-crime-rates}}

Now that we have our variables for crime rate per population, we can use this to produce our crime maps!

Let's first map crime count, next to residential population, and then the crime rate. We can do this by creating two maps, and then using our trusty \texttt{tmap\_arrange()} to put them next to one another.

Let's also use a different palette for each map, that is a different fill colour. To change the colours for the fill of the polygons you can use the palette argument within the \texttt{tm\_fill()} function. You can explore different palettes running the following code:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tmaptools}\SpecialCharTok{::}\FunctionTok{palette\_explorer}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

Pick the ones you like, and use them. Here I will use Blues, Greens and Reds

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crime\_count\_map }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"count"}\NormalTok{, }\AttributeTok{style=}\StringTok{"quantile"}\NormalTok{, }\AttributeTok{palette=} \StringTok{"Blues"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Crime count"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{panel.labels =} \StringTok{"Crime count"}\NormalTok{, }\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{),}
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}

\NormalTok{res\_pop\_map }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"respop"}\NormalTok{, }\AttributeTok{style=}\StringTok{"quantile"}\NormalTok{, }\AttributeTok{palette=} \StringTok{"Greens"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Residential population"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{panel.labels =} \StringTok{"Residential population"}\NormalTok{, }\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{),}
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}

\NormalTok{crime\_rate\_map }\OtherTok{\textless{}{-}} \FunctionTok{tm\_shape}\NormalTok{(manchester\_crime\_lsoa) }\SpecialCharTok{+} 
  \FunctionTok{tm\_fill}\NormalTok{(}\StringTok{"crimr1"}\NormalTok{, }\AttributeTok{style=}\StringTok{"quantile"}\NormalTok{, }\AttributeTok{palette=} \StringTok{"Reds"}\NormalTok{, }\AttributeTok{title =} \StringTok{"Crime rate"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{tm\_layout}\NormalTok{(}\AttributeTok{panel.labels =} \StringTok{"Crime per 100,00 population"}\NormalTok{, }\AttributeTok{legend.position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{),}
            \AttributeTok{legend.title.size =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{legend.text.size =} \FloatTok{0.5}\NormalTok{)}

\FunctionTok{tmap\_arrange}\NormalTok{(crime\_count\_map, res\_pop\_map, crime\_rate\_map)}
\end{Highlighting}
\end{Shaded}

\includegraphics{crime_mapping_textbook_files/figure-latex/unnamed-chunk-86-1.pdf}

What do you think about these three maps? How do you think this might be different if we were to look at workday population instead of residential population as a denominator? Discuss in your groups and make notes in your shared google doc.

Once you have completed this activity, let's explore your map with the crime rate using the usual residents as the denominator using the interactive way. Assuming you name that visualisation map5 you could use the following code.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tmap\_mode}\NormalTok{(}\StringTok{"view"}\NormalTok{)}
\NormalTok{map5}
\end{Highlighting}
\end{Shaded}

You may find it useful to shift to the OpenStreetMap view by clicking in the box to the left, since it will give you a bit more contextual information than the default CartoDB basemap.

In the first lecture we spoke a bit about Open Street Map, but if you're interested it's definitely worth reading up on. As I mentioned, Open Street Map is a non-profit foundation whose aim is to support and enable the development of freely-reusable geospatial data, and relies heavily on volunteers participating in this project to map their local areas. You can have a look \href{https://www.hotosm.org/get-involved/disaster-mapping}{here} for ongoing humanitarian projects, or read \href{https://wiki.openstreetmap.org/wiki/Mapping_parties}{here} about the mapping parties I told you about. At the very least though, in the spirit of open source and crowdsourcing, take a moment to appreciate that all these volunteers of people just like you have contributed to creating such a detailed geographical database of our world. That's definitely something kinda cool to think about!

\includegraphics{img/shiftingbasemap.png}

\hypertarget{summary-2}{%
\section{Summary}\label{summary-2}}

This week we learned some basic principles of thematic maps. We learned how to make them using the tmap package, we learned about the importance of classification schemes, and how each one may produce a different looking map, which may tell a different story. We learned how to access population data from the UK census, and how we can use that to calculate crime rates instead of crime counts. Taking this forward, make sure to think critically about the decisions that go into producing your thematic maps

  \bibliography{book.bib,packages.bib}

\end{document}
