<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2  | Crime Mapping in R</title>
  <meta name="description" content="Worksheets for labs of Crime Mapping course" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2  | Crime Mapping in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Worksheets for labs of Crime Mapping course" />
  <meta name="github-repo" content="maczokni/crimemapping_textbook_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2  | Crime Mapping in R" />
  
  <meta name="twitter:description" content="Worksheets for labs of Crime Mapping course" />
  

<meta name="author" content="Reka Solymosi and Juanjo Medina" />


<meta name="date" content="2021-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="a-first-lesson-about-r.html"/>
<link rel="next" href="thematic-maps-in-r.html"/>
<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prelude</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#introduction"><i class="fa fa-check"></i><b>0.1</b> Introduction</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>0.2</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A first lesson about R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-r-studio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; R Studio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-1-identifying-your-operating-system"><i class="fa fa-check"></i><b>1.1.1</b> Activity 1: Identifying your operating system</a></li>
<li class="chapter" data-level="1.1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-2-install-r-r-studio"><i class="fa fa-check"></i><b>1.1.2</b> Activity 2: Install R &amp; R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#open-up-and-explore-rstudio"><i class="fa fa-check"></i><b>1.2</b> Open up and explore RStudio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#the-four-panes-of-r-studio"><i class="fa fa-check"></i><b>1.2.1</b> The four panes of R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-the-rstudio-look"><i class="fa fa-check"></i><b>1.3</b> Customising the RStudio look</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="section.html"><a href="section.html"><i class="fa fa-check"></i><b>2</b> <img src="img/appearance_choose_tomorrow_night_bright.png" /></a>
<ul>
<li class="chapter" data-level="2.0.1" data-path="section.html"><a href="section.html#functions"><i class="fa fa-check"></i><b>2.0.1</b> Functions</a></li>
<li class="chapter" data-level="2.0.2" data-path="section.html"><a href="section.html#objects"><i class="fa fa-check"></i><b>2.0.2</b> Objects</a></li>
<li class="chapter" data-level="2.1" data-path="section.html"><a href="section.html#packages"><i class="fa fa-check"></i><b>2.1</b> Packages</a></li>
<li class="chapter" data-level="2.2" data-path="section.html"><a href="section.html#exploring-data"><i class="fa fa-check"></i><b>2.2</b> Exploring data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="section.html"><a href="section.html#activity-8-playing-around-with-data"><i class="fa fa-check"></i><b>2.2.1</b> Activity 8: Playing around with data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="section.html"><a href="section.html#getting-organised-r-projects"><i class="fa fa-check"></i><b>2.3</b> Getting organised: R Projects</a></li>
<li class="chapter" data-level="2.4" data-path="section.html"><a href="section.html#a-quick-introduction-of-terms"><i class="fa fa-check"></i><b>2.4</b> A quick introduction of terms</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="section.html"><a href="section.html#geospatial-perspective---the-basics"><i class="fa fa-check"></i><b>2.4.1</b> Geospatial Perspective - The Basics</a></li>
<li class="chapter" data-level="2.4.2" data-path="section.html"><a href="section.html#summary"><i class="fa fa-check"></i><b>2.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="section.html"><a href="section.html#getting-some-spatial-data-to-put-on-a-map"><i class="fa fa-check"></i><b>2.5</b> Getting some spatial data to put on a map</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="section.html"><a href="section.html#find-some-relevant-data-to-show-obtaining-data-on-crime"><i class="fa fa-check"></i><b>2.5.1</b> Find some relevant data to show: obtaining data on crime</a></li>
<li class="chapter" data-level="2.5.2" data-path="section.html"><a href="section.html#activity-1-get-some-crime-data"><i class="fa fa-check"></i><b>2.5.2</b> Activity 1: Get some crime data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="section.html"><a href="section.html#from-dataframes-to-spatial-objects-finding-spatial-information-in-our-data"><i class="fa fa-check"></i><b>2.6</b> From dataframes to spatial objects: finding spatial information in our data</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="section.html"><a href="section.html#activity-2-find-the-spatial-data"><i class="fa fa-check"></i><b>2.6.1</b> Activity 2: Find the spatial data</a></li>
<li class="chapter" data-level="2.6.2" data-path="section.html"><a href="section.html#the-point"><i class="fa fa-check"></i><b>2.6.2</b> The point</a></li>
<li class="chapter" data-level="2.6.3" data-path="section.html"><a href="section.html#the-line"><i class="fa fa-check"></i><b>2.6.3</b> The line</a></li>
<li class="chapter" data-level="2.6.4" data-path="section.html"><a href="section.html#the-polygon"><i class="fa fa-check"></i><b>2.6.4</b> The polygon</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="section.html"><a href="section.html#putting-crime-on-the-map---simple-features"><i class="fa fa-check"></i><b>2.7</b> Putting crime on the map - simple features</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="section.html"><a href="section.html#mapping-points-with-sf"><i class="fa fa-check"></i><b>2.7.1</b> Mapping points with sf</a></li>
<li class="chapter" data-level="2.7.2" data-path="section.html"><a href="section.html#mapping-data-by-joining-it-to-sf-objects"><i class="fa fa-check"></i><b>2.7.2</b> Mapping data by joining it to sf objects</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="section.html"><a href="section.html#summary-1"><i class="fa fa-check"></i><b>2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html"><i class="fa fa-check"></i><b>3</b> Thematic maps in R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#intro-and-recap"><i class="fa fa-check"></i><b>3.1</b> Intro and recap</a></li>
<li class="chapter" data-level="3.2" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#creating-thematic-maps"><i class="fa fa-check"></i><b>3.2</b> Creating thematic maps</a></li>
<li class="chapter" data-level="3.3" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#classification-systems-for-thematic-maps"><i class="fa fa-check"></i><b>3.3</b> Classification systems for thematic maps</a></li>
<li class="chapter" data-level="3.4" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#using-graduated-symbols"><i class="fa fa-check"></i><b>3.4</b> Using graduated symbols</a></li>
<li class="chapter" data-level="3.5" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#mapping-rates-rather-than-counts"><i class="fa fa-check"></i><b>3.5</b> Mapping rates rather than counts</a></li>
<li class="chapter" data-level="3.6" data-path="thematic-maps-in-r.html"><a href="thematic-maps-in-r.html#summary-2"><i class="fa fa-check"></i><b>3.6</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Crime Mapping in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="section" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> <img src="img/appearance_choose_tomorrow_night_bright.png" /></h1>
<p><img src="img/consoleresults.png" />
As indicated above, the window in the bottom left corner is the main <strong>console</strong>.You will see that the words “I love maps” appear printed there. If rather than using R Studio you were working directly from R, that’s all you would get: the main console where you can write code interactively (rather than all the different windows you see in R Studio). You can write your code directly in the main console and execute it line by line in an interactive fashion. However, we will be running code from scripts, so that you get used to the idea of properly documenting all the steps you take,</p>
<div id="functions" class="section level3" number="2.0.1">
<h3><span class="header-section-number">2.0.1</span> Functions</h3>
<p><strong>Functions</strong> <em>do</em> things. They are called by a certain name, usually a name which represents what they do, and they are followed by brackets <code>()</code>. Within the brackets, you can put whatever it is that you want the function to work with. For example, the code we wrote in Activity 4 was the <code>print()</code> function. This function told <code>R</code> to print into the console whatever we put in the brackets (“Hello World!”).</p>
<p>Same idea with a personalised greeting: if you want to print ‘Hello Reka,’ you will need to have “Hello Reka” inside the brackets:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="section.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Hello Reka&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Hello Reka&quot;</code></pre>
<p>There are so many functions in <code>R</code>. We will be learning many of them throughout our class. <code>Print</code> is fun, but most of the time, we will be using functions to help us with our data analysis. For example, getting the minimum, maximum, or mean of a list of numbers. <code>R</code> does this using functions in a very similar way.</p>
<p>For example, if we have a bunch of numbers, we just find the appropriate function to get the summary we want:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="section.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="dv">10</span>, <span class="dv">34</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">77</span>)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="section.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(<span class="dv">10</span>, <span class="dv">34</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">77</span>)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="section.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(<span class="dv">10</span>, <span class="dv">34</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">77</span>)</span></code></pre></div>
<pre><code>## [1] 77</code></pre>
<p>How can you find the function you need? Throughout this class, you will learn a list that appears at the top of each lesson. A recommendation is to also create a ‘function cookbook,’ where you write down a list of functions, what the functions do, and some examples. Here is an example:</p>
<p><img src="img/fn_cookbook.png" /></p>
<p>You can use google to make your cookbook, and the website <a href="https://stackoverflow.com/">stackoverflow</a>, in particular, can help you find the function you need. But be wary, especially in the beginning, that you understand what the function does. There can be several different functions for the same action. One good approach is to add a function of interest to your cookbook and ask the teaching team about what it does, and how it might be different to other functions that do the same thing.</p>
<div id="activity-5-play-around-with-functions" class="section level4" number="2.0.1.1">
<h4><span class="header-section-number">2.0.1.1</span> Activity 5: Play around with functions</h4>
<p>Have a guess (or google) about what you think is the function to get the median. Once you have your answer, write it in the shared google docs. Then, use it to get the median of the numbers 10, 34, 5, 3, 77.</p>
<p>Write the answer in your shared google doc (or note it down for yourself if in the quiet room).</p>
<p>The answer is further below, after the note:</p>
<p><strong>NOTE:</strong> <code>R</code> is case-sensitive! For example:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="section.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating the logarithm </span></span>
<span id="cb10-2"><a href="section.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Log</span>(<span class="dv">100</span>)</span>
<span id="cb10-3"><a href="section.html#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="section.html#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ERROR!</span></span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="section.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instead, it should be:</span></span>
<span id="cb11-2"><a href="section.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">log</span>(<span class="dv">100</span>)</span></code></pre></div>
<pre><code>## [1] 4.60517</code></pre>
<p>Okay, now you know these, the answer to Activity 6 was…</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="section.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(<span class="dv">10</span>, <span class="dv">34</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">77</span>)</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>Now let us move on to our second key topic: objects!</p>
</div>
</div>
<div id="objects" class="section level3" number="2.0.2">
<h3><span class="header-section-number">2.0.2</span> Objects</h3>
<p>Everything that exists in <code>R</code> is an <strong>object</strong>. Think of objects as boxes where you put things in. Imagine a big, empty cardboard box. We can create this big empty box in R by simply giving it a name. Usually, you want your object/box to have a good descriptive name, which will tell people what is in it. Imagine moving house. If you have a cardboard box full of places, you might want to label it “plates.” That way, when carrying, you know to be careful, and when unpacking, you know its contents will go in the kitchen. On the other hand, if you named it “box1,” then this is a lot less helpful when it comes to unpacking.</p>
<div id="activity-6-creating-an-object" class="section level4" number="2.0.2.1">
<h4><span class="header-section-number">2.0.2.1</span> Activity 6: Creating an object</h4>
<p>Let us create an object called ‘plates.’ To do this, you go to your script, and type ‘plates.’</p>
<p><img src="img/plates.png" /></p>
<p>But if you run this code, you will get an error. Let’s see:</p>
<p><img src="img/error_no_plates.gif" /></p>
<p>You see the error ‘Error! Object plates not found.’ This is because you have not yet put anything inside the plates ‘box.’ Remember objects are like boxes,so there must be something inside our object ‘plates.’ In order for this object to exist, you have to put something inside it, or in <code>R</code>-speak <em>assign it some value</em>.</p>
<p>Therefore, we make an object by using an <em>assignment operator</em> ( <code>&lt;-</code> ). In other words, we assign something to an object (i.e., put something in the box). For example:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="section.html#cb15-1" aria-hidden="true" tabindex="-1"></a>plates <span class="ot">&lt;-</span> <span class="st">&quot;yellow plate&quot;</span></span></code></pre></div>
<p>Now if we run this, we will see no error message, but instead, we will see the <code>plates</code> object appear in our <em>environment pane</em>:</p>
<p><img src="img/assign_plates.gif" /></p>
<p>Here are some more examples to illustrate:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="section.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting &#39;10&#39; in the &#39;a&#39; box</span></span>
<span id="cb16-2"><a href="section.html#cb16-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb16-3"><a href="section.html#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="section.html#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Putting &#39;Hello!&#39; in the &#39;abc123&#39; box</span></span>
<span id="cb16-5"><a href="section.html#cb16-5" aria-hidden="true" tabindex="-1"></a>abc123 <span class="ot">&lt;-</span> <span class="st">&quot;Hello!&quot;</span></span></code></pre></div>
<p>In these examples, we are putting the value of <code>10</code> into the object <code>a</code>, and the value of ‘Hello!’ into the object <code>abc123</code>.</p>
<p>Earlier, we introduced you to the Environment and History pane. We mentioned that it lists objects you defined. After making the ‘a’ and ‘abc123’ objects, they should appear in that very pane under the <code>Environment</code> tab.</p>
</div>
<div id="types-of-objects" class="section level4" number="2.0.2.2">
<h4><span class="header-section-number">2.0.2.2</span> Types of objects</h4>
<p>Why are objects important? We will be storing everything in our data analysis process in these objects. Depending on what is inside them, they can become a different type of object. Here are some examples:</p>
<p><strong>Data structures</strong> are important objects that store your data, and there are five main types but we focus on three for this course:</p>
<ol style="list-style-type: decimal">
<li><em>(atomic) vector</em>: an ordered set of elements that are of the same <em>class</em>. Vectors are a basic data structure in <code>R</code>. Below are five different classes of vectors:</li>
</ol>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="section.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. numeric vector with three elements</span></span>
<span id="cb17-2"><a href="section.html#cb17-2" aria-hidden="true" tabindex="-1"></a>my_1st_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">8.9</span>, <span class="fl">0.6</span>) </span>
<span id="cb17-3"><a href="section.html#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="section.html#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. integer vector with addition of L at the end of the value</span></span>
<span id="cb17-5"><a href="section.html#cb17-5" aria-hidden="true" tabindex="-1"></a>my_2nd_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(1L, 2L, 3L)  </span>
<span id="cb17-6"><a href="section.html#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="section.html#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. logical vector</span></span>
<span id="cb17-8"><a href="section.html#cb17-8" aria-hidden="true" tabindex="-1"></a>my_3rd_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="cn">TRUE</span>, <span class="cn">FALSE</span>, <span class="cn">FALSE</span>) </span>
<span id="cb17-9"><a href="section.html#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># &#39;my_4th_vector&#39; creates a logical vector using abbreviations of True and False, but you should use the full words instead</span></span>
<span id="cb17-10"><a href="section.html#cb17-10" aria-hidden="true" tabindex="-1"></a>my_4th_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(T, F) </span>
<span id="cb17-11"><a href="section.html#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="section.html#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. character vector</span></span>
<span id="cb17-13"><a href="section.html#cb17-13" aria-hidden="true" tabindex="-1"></a>my_5th_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;c&quot;</span>) </span>
<span id="cb17-14"><a href="section.html#cb17-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-15"><a href="section.html#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. complex vector (we will not use this for our class)</span></span>
<span id="cb17-16"><a href="section.html#cb17-16" aria-hidden="true" tabindex="-1"></a>my_6th_vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">+</span>0i, <span class="dv">2</span><span class="sc">+</span>4i) </span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li><em>lists</em>: technically they, too, are vectors but they are more complex because they are not restricted on the length, structure, or class of the included elements. For example, to create a list containing strings, numbers, vectors and a logical, use the <code>list()</code> function, and inside the brackets, put everything tat you want to combine into a list:</li>
</ol>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="section.html#cb18-1" aria-hidden="true" tabindex="-1"></a>list_data <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="st">&quot;teal&quot;</span>, <span class="st">&quot;sky blue&quot;</span>, <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">10</span>), <span class="cn">TRUE</span>, <span class="fl">68.26</span>, <span class="fl">95.46</span>, <span class="fl">99.7</span>) </span></code></pre></div>
<p>Above, we created <code>list_data</code>, an object that contains all those things that we put inside the <code>list()</code> function. This function serves to create a list from combining everything that is put inside its brackets.</p>
<p>Use the <code>class()</code> function to confirm that the objects have been defined as a list</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="section.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(list_data)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><em>data frames</em>: also stores elements but differ from lists because they are defined by their number of columns and rows; the vectors (columns) must be of the same length. Data frames can contain different classes but each column must be of the same class. For example, if you want to combine some related vectors to make a data frame on violent American cities, use the function <code>data.frame()</code>:</li>
</ol>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="section.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Making some relevant vectors</span></span>
<span id="cb21-2"><a href="section.html#cb21-2" aria-hidden="true" tabindex="-1"></a>TopVioCities <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;St. Louis&quot;</span>, <span class="st">&quot;Detroit&quot;</span>, <span class="st">&quot;Baltimore&quot;</span>) <span class="co"># some violent US cities</span></span>
<span id="cb21-3"><a href="section.html#cb21-3" aria-hidden="true" tabindex="-1"></a>VioRatePer1k <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">20.8</span>, <span class="fl">20.6</span>, <span class="fl">20.3</span>) <span class="co"># their violence rates per 1,000 persons</span></span>
<span id="cb21-4"><a href="section.html#cb21-4" aria-hidden="true" tabindex="-1"></a>State <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Missouri&quot;</span>, <span class="st">&quot;Michigan&quot;</span>, <span class="st">&quot;Maryland&quot;</span>) <span class="co"># in what states are these cities found</span></span>
<span id="cb21-5"><a href="section.html#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="section.html#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Join them to make a data frame called &#39;df&#39;</span></span>
<span id="cb21-7"><a href="section.html#cb21-7" aria-hidden="true" tabindex="-1"></a>df<span class="ot">&lt;-</span><span class="fu">data.frame</span>(TopVioCities, VioRatePer1k, State)</span></code></pre></div>
<p>We can then view the data frame, ‘df,’ with the <code>View()</code> function:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="section.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df)</span></code></pre></div>
</div>
<div id="activity-7-doing-things-to-objects" class="section level4" number="2.0.2.3">
<h4><span class="header-section-number">2.0.2.3</span> Activity 7: Doing things to objects</h4>
<p>We have learned what functions are (i.e., things that do things) and what are objects (i.e., the boxes that hold things). We also saw some functions which helped us create objects. Functions can also do things to objects. For example, we saw the function <code>class()</code> that told us about what kind of object list_data was, and <code>View()</code> which allowed us to have a look at our dataframe we called <code>df</code>.</p>
<p>Let us look back at our <code>plates</code> object. Remember it was the object that held our kitchen items. We added ‘yellow plate’ to it. Now let us add some more items and let us use the concatenate <code>c()</code> function for this again:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="section.html#cb23-1" aria-hidden="true" tabindex="-1"></a>plates <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;yellow plate&quot;</span>, <span class="st">&quot;purple plate&quot;</span>, <span class="st">&quot;silver plate&quot;</span>, <span class="st">&quot;orange bowl&quot;</span>)</span></code></pre></div>
<p>Let us say that we suddenly forgot what was in our object called ‘plates.’ Like what we learned earlier, we use the function <code>print()</code> to see what is inside this object:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="section.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plates)</span></code></pre></div>
<pre><code>## [1] &quot;yellow plate&quot; &quot;purple plate&quot; &quot;silver plate&quot; &quot;orange bowl&quot;</code></pre>
<p>This can apply to obtaining the mean, the minimum, and maximum. You could assign those statistics to an object this time:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="section.html#cb26-1" aria-hidden="true" tabindex="-1"></a>nums <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">34</span>, <span class="dv">5</span>, <span class="dv">3</span>, <span class="dv">77</span>)</span></code></pre></div>
<p>Now if we want to know the mean, we can take the mean of the object <code>nums</code>, which we just created:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="section.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nums)</span></code></pre></div>
<pre><code>## [1] 25.8</code></pre>
<p>The object we will use most frequently though is data frames. These hold your data in a format whereby each column represents a variable, and each row an observation.</p>
<p>Just earlier, we had created a dataframe called <code>df</code> previously. If you have not yet copied this over into your own <code>R Studio</code>, do this now. You should have the object <code>df</code> in your environment. When you run <code>View(df)</code>, you should see this dataset:</p>
<p><img src="img/df_view.png" /></p>
<p>To do something to an entire dataframe, we would use the name of the object (<code>df</code>) to refer to it. In the case of the <code>View()</code> function, we want to see the whole thing, so we will call <code>View(df)</code>. On the other hand, if we want to refer to only one variable in the data, (remember back to term 1 - each varible is held in each column) there is a special notation to do this.</p>
<p>To refer to a variable (column) inside a dataframe, you use:</p>
<p><span class="math inline">\(dataframe name + \$ + variable name\)</span></p>
<p>For example, to refer to the variable <code>VioRatePer1k</code>, we use the notation <code>df$VioRatePer1k</code>.</p>
<p>And if we wanted to View only that column, we use:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="section.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(df<span class="sc">$</span>VioRatePer1k)</span></code></pre></div>
<p>You should see:</p>
<p><img src="img/view_col_only.png" /></p>
<p>Say we wanted to know the mean violence rate across our units of analysis, the cities, for example, we would take the numeric column to calculate this:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="section.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(df<span class="sc">$</span>VioRatePer1k)</span></code></pre></div>
<pre><code>## [1] 20.56667</code></pre>
</div>
</div>
<div id="packages" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Packages</h2>
<p><strong>Packages</strong> are a very important element of <code>R</code>.</p>
<p>Packages are elements that add the functionality of R. What most packages do is they introduce new functions that allow you to ask R to do new different things. Anybody can write a package, so consequently R packages vary on quality and complexity. You can find packages in different places, as well, from official repositories (which means they have passed a minimum of quality control), something called Git Hub (a webpage where software developers post work in progress), to personal webpages (danger danger!).</p>
<p>Throughout the course, and hopefully afterwards, you will find yourself installing numerous open source software packages that allow <code>R</code> to do new and different things. There are loads of packages out there. In early 2020, there were over 150,000 packages available. Anyone can write one, so you will need to be careful on which ones you use as the quality can vary. Official repositories, like <a href="https://cran.r-project.org/">CRAN</a>, are your best bet for packages as they will have passed some quality controls.</p>
<p>You can see what packages are available in your local install by looking at the <em>packages</em> tab in the <em>File directory, Plots, Packages</em> pane.</p>
<p><img src="img/packages.png" style="width:35.0%" /></p>
<p>A number of the packages we will use belong to a set of packages called <strong>tidyverse</strong>. These packages help make your data tidy. According to Statistician and Chief Scientist at <code>RStudio</code>, Hadley Wickham, transforming your data into <em>tidy data</em> is one of the most important steps of the data analysis process. It will ensure your data are in the format you need to conduct your analyses. We will also be using the simple features package <strong>sf</strong> and many more associated with spatial data analysis.</p>
<p>Packages can be installed using the <code>install.packages()</code> function. Remember that while you only need to install packages once, they need to be loaded with the <code>library()</code>function each time you open up <code>RStudio</code>. Let us install the package <code>dplyr</code> from <code>tidyverse</code> and load it:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="section.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<p>A lot of code and activity appears in the console. Warnings may manifest. Most of the time, the warnings explain what is being loaded and confirm that the package is successfully loaded. If there is an error, you will have to figure out what the warnings are telling you to successfully load the package. This happens and is normal.</p>
<p>To double check that you have actually installed <code>dplyr</code>, go to that <em>File Directory, Plots, Packages</em> pane and click on the <em>Packages</em> tab. The list of packages is in alphabetical order and <code>dplyr</code> should be there. If there is a tick in its box, it means that this package is currently loaded and you can use it; if there is no tick, it means that it is inactive, and you will have to bring it up with <code>library()</code>, or just tick its box (Figure 1.6).</p>
<p><img src="img/dplyr.png" style="width:35.0%" /></p>
<p>On <em>masking</em>: sometimes packages introduce functions that have the same name as those that are already loaded into your session. When that happens, the newly loaded ones will override the previous ones. You can still use them but you will have to refer to them explicitly by bringing them up by specifying to which package they belong with <code>library()</code>.</p>
<p>How do you find out what a package does? You look at the relevant documentation. In the Packages window scroll down until you find the new package we installed listed. Here you will see the name of the package (dplyr), a brief description of what the program is about, and the version you have installed (an indication that a package is a good package is that it has gone through several versions, that means that someone is making sure the package gets regular updates and improvements).</p>
<p>Click in the name <em>dplyr</em>. You will see that R Studio has now brought you to the Help tab. Here is where you find the help files for this package, including all the available documentation.</p>
<p>Every beginner in R will find these help files a bit confusing. But after a while, their format and structure will begin to make sense to you. Click where it says <em>User guides, package vignettes, and other documentation</em>. Documentation in R has become much better since people started to write <strong>vignettes</strong> for their packages. They are little tutorials that explain with examples what each package does. Click in the <em>cowsay::cowsay_tutorial</em> that you see listed here (the html link). What you will find there is an html file that gives you a detailed tutorial on this package. You don’t need to read it now, but remember that this is one way to find help when using R. You will learn to love vignettes.</p>
</div>
<div id="exploring-data" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Exploring data</h2>
<p>Now that we know the basic component, let’s play around with using R as we will throughout the course, for some data analysis.</p>
<p>We will get some data by installing a package which has data in it as well as functions, and then go on to produce some basic summaries. This should give some practice!</p>
<div id="activity-8-playing-around-with-data" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Activity 8: Playing around with data</h3>
<p>We are going to look at some data that are part of the <em>fivethirtyeight</em> package. This package contains data sets and code behind the stories in <a href="http://fivethirtyeight.com/">this particular online newspaper</a>. This package is not part of the base installation of R, so you will need to install it first. I won’t give you the code for it. See if you can figure it out by looking at previous examples. Discuss and write in the google doc what you think the code will be.</p>
<p>Done? Ok, now we are going to look at the data sets that are included in this package. Remember first we have to load the package if we want to use it:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="section.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;fivethirtyeight&quot;</span>)</span></code></pre></div>
<pre><code>## Some larger datasets need to be installed separately, like senators and
## house_district_forecast. To install these, we recommend you install the
## fivethirtyeightdata package by running:
## install.packages(&#39;fivethirtyeightdata&#39;, repos =
## &#39;https://fivethirtyeightdata.github.io/drat/&#39;, type = &#39;source&#39;)</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="section.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="at">package=</span><span class="st">&quot;fivethirtyeight&quot;</span>) <span class="co">#This function will return all the data frames that are available in the named package.</span></span></code></pre></div>
<p>Notice that this package has some data sets that relate to stories covered in this newspaper that had a criminological angle. Let’s look for example at the <code>hate_crimes</code> data set. How do you that? First we have to load the data frame into our global environment. To do so use the following code:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="section.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;hate_crimes&quot;</span>)</span></code></pre></div>
<p>This function will search among all the <em>loaded</em> packages and locate the <code>hate_crimes</code> data set. Notice that it now appears in the global environment, although it also says “promise” next to it. To see the data in full you need to do something to it first. So let’s do that.</p>
<p>Every object in R can have <strong>attributes</strong>. These are: names; dimensions (for matrices and arrays: number of rows and columns) and dimensions names; class of object (numeric, character, etc.); length (for a vector this will be the number of elements in the vector); and other user-defined. You can access the attributes of an object using the <code>attributes()</code> function. Let’s query R for the attributes of this data frame.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="section.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(hate_crimes)</span></code></pre></div>
<pre><code>## $row.names
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
## [26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
## [51] 51
## 
## $class
## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;
## 
## $names
##  [1] &quot;state&quot;                       &quot;state_abbrev&quot;               
##  [3] &quot;median_house_inc&quot;            &quot;share_unemp_seas&quot;           
##  [5] &quot;share_pop_metro&quot;             &quot;share_pop_hs&quot;               
##  [7] &quot;share_non_citizen&quot;           &quot;share_white_poverty&quot;        
##  [9] &quot;gini_index&quot;                  &quot;share_non_white&quot;            
## [11] &quot;share_vote_trump&quot;            &quot;hate_crimes_per_100k_splc&quot;  
## [13] &quot;avg_hatecrimes_per_100k_fbi&quot;</code></pre>
<p>This prints out the row names (not very exciting here..) the class (see above when we used <code>class()</code> function) and the names, which are the column headers - or the <em>names of the variables within this data set</em>. You can see there are things like state, and share who voted trump (in the 2016 election, not most recent!).</p>
<p>Now use the <code>View()</code> function to glance at your data frame. What you get there is a spreadsheet with 12 variables and 51 observations. Each variable in this case is providing you with information (demographics, voting patterns, and hate crime) about each of the US states.</p>
<p>Ok, let’s now have a quick look at the data. There are so many different ways of producing summary stats for data stored in R that is impossible to cover them all! We will just introduce a few functions that you may find useful for summarising data. Before we do any of that it is important you get a sense for what is available in this data set. Go to the help tab and in the search box input the name of the data frame, this will take you to the documentation for this data frame. Here you can see a list of the available variables.</p>
<p><img src="img/codebook.png" /></p>
<p>Let’s start with the <em>mean</em>. This function takes as an argument the numeric variable for which you want to obtain the mean. You have done this above, so it should be familiar now! If you want to obtain the mean of the variable that gives us the proportion of people that voted for Donald Trump you can use the following expression:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="section.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(hate_crimes<span class="sc">$</span>share_vote_trump)</span></code></pre></div>
<pre><code>## [1] 0.49</code></pre>
<p>Another function you may want to use with numeric variables is <code>summary()</code>:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="section.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hate_crimes<span class="sc">$</span>share_vote_trump)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.040   0.415   0.490   0.490   0.575   0.700</code></pre>
<p>This gives you the five number summary (minimum, first quartile, median, third quartile, and maximum, plus the mean and the count of missing values if there are any).</p>
<p>You don’t have to specify a variable you can ask for these summaries from the whole data frame:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="section.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hate_crimes)</span></code></pre></div>
<pre><code>##     state           state_abbrev       median_house_inc share_unemp_seas 
##  Length:51          Length:51          Min.   :35521    Min.   :0.02800  
##  Class :character   Class :character   1st Qu.:48657    1st Qu.:0.04200  
##  Mode  :character   Mode  :character   Median :54916    Median :0.05100  
##                                        Mean   :55224    Mean   :0.04957  
##                                        3rd Qu.:60719    3rd Qu.:0.05750  
##                                        Max.   :76165    Max.   :0.07300  
##                                                                          
##  share_pop_metro   share_pop_hs    share_non_citizen share_white_poverty
##  Min.   :0.3100   Min.   :0.7990   Min.   :0.01000   Min.   :0.04000    
##  1st Qu.:0.6300   1st Qu.:0.8405   1st Qu.:0.03000   1st Qu.:0.07500    
##  Median :0.7900   Median :0.8740   Median :0.04500   Median :0.09000    
##  Mean   :0.7502   Mean   :0.8691   Mean   :0.05458   Mean   :0.09176    
##  3rd Qu.:0.8950   3rd Qu.:0.8980   3rd Qu.:0.08000   3rd Qu.:0.10000    
##  Max.   :1.0000   Max.   :0.9180   Max.   :0.13000   Max.   :0.17000    
##                                    NA&#39;s   :3                            
##    gini_index     share_non_white  share_vote_trump hate_crimes_per_100k_splc
##  Min.   :0.4190   Min.   :0.0600   Min.   :0.040    Min.   :0.06745          
##  1st Qu.:0.4400   1st Qu.:0.1950   1st Qu.:0.415    1st Qu.:0.14271          
##  Median :0.4540   Median :0.2800   Median :0.490    Median :0.22620          
##  Mean   :0.4538   Mean   :0.3157   Mean   :0.490    Mean   :0.30409          
##  3rd Qu.:0.4665   3rd Qu.:0.4200   3rd Qu.:0.575    3rd Qu.:0.35694          
##  Max.   :0.5320   Max.   :0.8100   Max.   :0.700    Max.   :1.52230          
##                                                     NA&#39;s   :4                
##  avg_hatecrimes_per_100k_fbi
##  Min.   : 0.2669            
##  1st Qu.: 1.2931            
##  Median : 1.9871            
##  Mean   : 2.3676            
##  3rd Qu.: 3.1843            
##  Max.   :10.9535            
##  NA&#39;s   :1</code></pre>
<p>There are multiple ways of getting results in R. Particularly for basic and intermediate-level statistical analysis many core functions and packages can give you the answer that you are looking for. For example, there are a variety of packages that allow you to look at summary statistics using functions defined within those packages. You will need to install these packages before you can use them.</p>
<p>I am only going to introduce one of them here <code>skimr</code>. You will need to install it before anything else.</p>
<p>Once you have loaded the <em>skimr</em> package you can use it. Its main function is <em>skim</em>. Like <em>summary</em> for data frames, skim presents results for all the columns and the statistics will depend on the class of the variable.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="section.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(hate_crimes)</span></code></pre></div>
<p>Hopefully in your statistical modules you had taken previously, you have learned some things about how to graphically display variables. So you may have some memory about the amount of work involved with this. Hopefully R will offer some respite. Of course, there are many different ways of producing graphics in R. In this course we rely on a package called <em>ggplot2</em>, which is part of the tidyverse set of packages mentioned earlier.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="section.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Then we will use one of its functions to create a scatterplot.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="section.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hate_crimes, <span class="fu">aes</span>(<span class="at">x=</span>share_vote_trump, <span class="at">y=</span>avg_hatecrimes_per_100k_fbi)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="section.html#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb50-3"><a href="section.html#cb50-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (geom_point).</code></pre>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>What do you think this graphic is telling you? Discuss and write in your shared google docs.</p>
<p>Graphing is very powerful in R, and much of the spatial visualisation we will produce throughout the module will build on this. If you are not already familiar with this, I recommend a read of the data visualisation chapter of R for Data Science <a href="https://r4ds.had.co.nz/data-visualisation.html">https://r4ds.had.co.nz/data-visualisation.html</a></p>
</div>
</div>
<div id="getting-organised-r-projects" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Getting organised: R Projects</h2>
<p>One thing that can help you tremendously throughout this module is keeping your code organised.R Studio helps with this by virtue of something called <strong>R Projects</strong>.</p>
<p>Technically, a R Studio project is just a directory with the name of the project, and a few files and folders created by R Studio for internal purposes. This is where you should hold your scripts, your data, and reports. You can manage this folder with your own operating system manager (discussed earlier, e.g., Windows) or through the R Studio file manager (that you access in the bottom right corner set of windows in R Studio).</p>
<p>When a project is reopened, R Studio opens every file and data view that was open when the project was closed last time around. Trust me, this is a really helpful thing! If you create a project for this module, you can keep everything in once place, and refer back to your old code and your learnings throughout the module.</p>
<div id="activity-9-saving-your-work-and-projects" class="section level4" number="2.3.0.1">
<h4><span class="header-section-number">2.3.0.1</span> Activity 9: Saving your work and projects</h4>
<p>First things first, hopefully you have already created a separate folder on your desktop, or dropbox, or something like this. Now save the script you’ve been working on into this folder. By clicking on “File” and “Save as….”</p>
<p><img src="img/save_script_as.png" /></p>
<p>Then navigate to your folder for this module, and for your script make sure to give it some meaningful name like week1lab.R or something like this. Then click ‘save.’</p>
<p><img src="img/rename_and_save.png" /></p>
<p>Now, go back to “File” and select “New project…”</p>
<p><img src="img/file_newproj.png" /></p>
<p>Then in the options that appear choose “Existing Directory.” This is because you already have a folder for this work, this is where you saved your script just before. For me this was my folder called ‘crime_mapping’ you saw above.</p>
<p><img src="img/existing_dir.png" /></p>
<p>So select ‘Existing Directory,’ and on the next page use the “Browse” button to select this folder (the directory) where you saved the script earlier. Once you have done this, click on ‘Create Project’ on the bottom.</p>
<p>This will now open up a new R Studio window with your project. In the future, you can start right back up where you finished last time by navigating to the .Rproj file, and double clicking it. It helps you keep everything in one place, and lets R read everything from that folder.</p>
<p>With simple projects a single script file and a data file is all you may have. But with more complex projects, things can rapidly become messy. So you may want to create subdirectories within this project folder. I typically use the following structure in my own work to put all files of a certain type in the same subdirectory:</p>
<ul>
<li><p><em>Scripts and code</em>: Here I put all the text files with my analytic code, including rmarkdown files which is something we will introduce much later in the semester.</p></li>
<li><p><em>Source data</em>: Here I put the original data. I tend not to touch this once I have obtained the original data.</p></li>
<li><p><em>Documentation</em>: This is the subdirectory where I place all the data documentation (e.g., codebooks, questionnaires, etc.)</p></li>
<li><p><em>Modified data</em>: All analysis involve doing transformations and changing things in the original data files. You don’t want to mess up the original data files, so what you should do is create new data files as soon as you start changing your source data. I go so far as to place them in a different subdirectory.</p></li>
<li><p><em>Literature</em>: Analysis is all about answering research questions. There is always a literature about these questions. I place the relevant literature for the analytic project I am conducting in this subdirectory.</p></li>
<li><p><em>Reports and write up</em>: Here is where I file all the reports and data visualisations that are associated with my analysis.</p></li>
</ul>
<p>If you come to my office, you will see it is a very messy place. But my computer is, in contrast, a very tidy environment. You should aim for your computer workspace to be very organised as well.</p>
<p>You can read up here on why projects are useful here: <a href="https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/">https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/</a></p>

<p>This week we will start making some maps in R, and learn about how we can take regular crime data, and assign the appropriate geometry for our chosen unit of analysis. We will produce some maps, using possibly familiar ggplot notation, and learn some key terms around projectsion and coordinate reference systems which will be essential for your work in the coming weeks.</p>
<p>Today we will use the following packages, so make sure you have them downloaded:</p>
<ul>
<li><code>reader</code></li>
<li><code>tibble</code></li>
<li><code>janitor</code></li>
<li><code>sf</code></li>
<li><code>ggplot2</code></li>
<li><code>ggspatial</code></li>
<li><code>dplyr</code></li>
</ul>
</div>
</div>
<div id="a-quick-introduction-of-terms" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> A quick introduction of terms</h2>
<div id="geospatial-perspective---the-basics" class="section level3" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Geospatial Perspective - The Basics</h3>
<p>Geospatial analysis provides a distinct perspective on the world, a unique lens through which to examine events, patterns, and processes that operate on or near the surface of our planet. Ultimately geospatial analysis concerns what happens where, and makes use of geographic information that links features and phenomena on the Earth’s surface to their locations.</p>
<p>We can talk about a few different concepts when it comes to spatial information. These are:</p>
<ul>
<li>Place</li>
<li>Attributes</li>
<li>Objects</li>
</ul>
<div id="place" class="section level4" number="2.4.1.1">
<h4><span class="header-section-number">2.4.1.1</span> Place</h4>
<p>At the center of all spatial analysis is the concept of <em>place</em>. People identify with places of various sizes and shapes, from the room with the parcel of land, to the neighbourhood, to the city, the country, the state or the nation state. Places often have names, and people use these to talk about and distinguish names. Names can be official. Places also change continually as people move. The basis of rigorous and precise definition of place is a coordinate system, a set of measurements that allows place to be specified unambiguously and in a way that is meaningful to everyone.</p>
</div>
<div id="attributes" class="section level4" number="2.4.1.2">
<h4><span class="header-section-number">2.4.1.2</span> Attributes</h4>
<p>Attribute has become the preferred term for any recorded characteristic or property of a place. A place’s name is an obvious example of an attribute. But there can be other pieces of information, such as number of crimes in a neighbourhood, or the GDP of a country. Within GIS the term ‘attributes’ usually refers to records in a data table associated with individual elements in a vector map or cells in a grid (raster or image file). These data behave exactly as data you have encountered in your past experience. The rows represent observations, and the columns represent variables. The variables can be numeric or categorical, and depending on what they are, you can apply different methods to making sense of them. The difference with other kind of data table is that the observations, your rows, correspond to places or locations.</p>
</div>
<div id="objects-1" class="section level4" number="2.4.1.3">
<h4><span class="header-section-number">2.4.1.3</span> Objects</h4>
<p>In spatial analysis it is customary to refer to places as objects. These objects can be a whole country, or a road. In forestry, the objects of interest might be trees, and their location will be represented as points. On the other hand, studies of social or economic patterns may need to consider the two-dimensional extent of places, which will therefore be represented as areas. These representations of the world are part of what is called the <strong>vector data model</strong>: A representation of the world using points, lines, and polygons. Vector models are useful for storing data that have discrete boundaries, such as country borders, land parcels, and streets. This is made up of points, lines, and areas (polygons):</p>
<ul>
<li>Points
<ul>
<li>Points are pairs of coordinates, in latitude/longitude or some other standard system</li>
</ul></li>
<li>Lines
<ul>
<li>Lines are ordered sequences of points connected by straight lines</li>
</ul></li>
<li>Areas (polygons)
<ul>
<li>Areas are ordered rings of points, also connected by straight lines to form polygons. It can contain holes, or be linked with separate islands.</li>
</ul></li>
</ul>
<p><img src="img/ptlinepoly.png" /></p>
<p>Objects can also be <strong>raster data</strong>. Raster data is made up of pixels (or cells), and each pixel has an associated value. Simplifying slightly, a digital photograph is an example of a raster dataset where each pixel value corresponds to a particular colour. In GIS, the pixel values may represent elevation above sea level, or chemical concentrations, or rainfall etc. The key point is that all of this data is represented as a grid of (usually square) cells.</p>
</div>
<div id="networks" class="section level4" number="2.4.1.4">
<h4><span class="header-section-number">2.4.1.4</span> Networks</h4>
<p>We already mentioned lines that constitute objects of spatial data, such as streets, roads, railroads, etc. Networks constitute one-dimensional structures embedded in two or three dimensions. Discrete point objects may be distributed on the network, representing phenomena such as landmarks, or observation points. Mathematically, a network forms a graph, and many techniques developed for graphs have application to networks. These include various ways of measuring a network’s connectivity, or of finding the shortest path between pairs of points on a network. You can have a look at the <a href="https://docs.qgis.org/2.18/en/docs/training_manual/vector_analysis/network_analysis.html">lesson on network analysis in the QGIS documentation</a></p>
</div>
<div id="maps-reference-and-thematic-maps" class="section level4" number="2.4.1.5">
<h4><span class="header-section-number">2.4.1.5</span> Maps: reference and thematic maps</h4>
<p>Historically maps have been the primary means to store and communicate spatial data. Objects and their attributes can be readily depicted, and the human eye can quickly discern patterns and anomalies in a well-designed map.</p>
<p>In GIS we distinguish between reference and thematic maps. A <strong>reference map</strong> places the emphasis on the location of spatial objects such as cities, mountains, rivers, parks, etc. You use these maps to orient yourself in space and find out the location of particular places. <strong>Thematic maps</strong>, on the other hand, are about the spatial distribution of attributes or statistics. For example, the number of crimes across different neighbourhouds. Our focus in this book is on thematic maps.</p>
</div>
<div id="map-projections-and-geographic-coordinate-systems" class="section level4" number="2.4.1.6">
<h4><span class="header-section-number">2.4.1.6</span> Map projections and geographic coordinate systems</h4>
<p>Whenever we put something into a map we need some sort of system to pinpoint the location. A coordinate system allows you to integrate any dataset with other geographical datasets within a common framework. There are hundreds of them. It is common to distinguish between <strong>geographic coordinate systems</strong> and <strong>projected coordinate systems</strong>. A <em>geographic coordinate system</em> is a <em>three dimensional</em> reference system that enables you to locate any location on earth. Often this is done with longitude, latitute and elevation. <em>Projected coordinate systems</em> or map projections, on the other hand, try to portray the surface of the earth or a portion of the earth on a <em>two dimensional</em> flat piece of paper or computer screen.</p>
<p>All projections of a sphere like the earth in a two dimensional map involve some sort of distortion. You can’t fit a three dimensional object into two dimensions without doing so. Projections differ to a large extent on the kind of distortion that they introduce. The decision as to which map projection and coordinate reference system to use, depends on the regional extent of the area you want to work in, on the analysis you want to do and often on the availability of data. Knowing the system you use would allow you to translate your data into other systems whenever this may be necessary. Often you may have to integrate data that is provided to you in different coordinate or projected systems. As long as you know the systems, you can do this.</p>
<p>[Footnote to this for more detail: <a href="https://www.youtube.com/watch?v=6tmDxTAjux0" class="uri">https://www.youtube.com/watch?v=6tmDxTAjux0</a>]</p>
<p>A traditional method of representing the earth’s shape is the use of globes. When viewed at close range the earth appears to be relatively flat. However when viewed from space, we can see that the earth is relatively spherical. Maps, are representations of reality. They are designed to not only represent features, but also their shape and spatial arrangement. Each map projection has advantages and disadvantages. The best projection for a map depends on the scale of the map, and on the purposes for which it will be used. For your purposes, you just need to understand that essentially there are different ways to flatten out the earth, in order to get it into a 2-dimensional map.</p>
<p>The process of creating map projections can be visualised by positioning a light source inside a transparent globe on which opaque earth features are placed. Then project the feature outlines onto a two-dimensional flat piece of paper. Different ways of projecting can be produced by surrounding the globe in a cylindrical fashion, as a cone, or even as a flat surface. Each of these methods produces what is called a map projection family. Therefore, there is a family of planar projections, a family of cylindrical projections, and another called conical projections.</p>
<div class="figure">
<img src="img/projection_families.png" alt="" />
<p class="caption">figure_projection_families</p>
</div>
<p>With the help of <strong>coordinate reference systems</strong> (CRS) every place on the earth can be specified by a set of three numbers, called coordinates. In general CRS can be divided into <strong>projected coordinate reference systems</strong> (also called Cartesian or rectangular coordinate reference systems) and <strong>geographic coordinate reference systems</strong>.</p>
<p>The use of Geographic Coordinate Reference Systems is very common. They use degrees of latitude and longitude and sometimes also a height value to describe a location on the earth’s surface. The most popular is called <strong>WGS 84</strong>. This is the one you will most likely be using, and if you get your data in latitude and longitude, then this is the CRS you are working in. It is also possible that you will be using a projected CRS. This two-dimensional coordinate reference system is commonly defined by two axes. At right angles to each other, they form a so called XY-plane. The horizontal axis is normally labelled X, and the vertical axis is normally labelled Y.</p>
<p>Working with data in the UK, on the other hand, you are most likely to be using <strong>British National Grid (BNG)</strong>. The Ordnance Survey National Grid reference system is a system of geographic grid references used in Great Britain, different from using Latitude and Longitude. In this case, points will be defined by “Easting” and “Northing” rather than “Longitude” and “Latitude.” It basically divides the UK into a series of squares, and uses references to these to locate something. The most common usage is the six figure grid reference, employing three digits in each coordinate to determine a 100 m square. For example, the grid reference of the 100 m square containing the summit of Ben Nevis is NN 166 712. Grid references may also be quoted as a pair of numbers: eastings then northings in meters, measured from the southwest corner of the SV square. For example, the grid reference for Sullom Voe oil terminal in the Shetland Islands may be given as HU396753 or 439668,1175316</p>
<div class="figure">
<img src="img/Ordnance_Survey_National_Grid.svg.png" alt="" />
<p class="caption">BNG</p>
</div>
<p>This will be important later on when we are linking data from different projections, or when you look at your map and you try to figure out why it might look “squished.”</p>
</div>
<div id="density-estimation" class="section level4" number="2.4.1.7">
<h4><span class="header-section-number">2.4.1.7</span> Density estimation</h4>
<p>One of the more useful concepts in spatial analysis is density - the density of humans in a crowded city, or the density of retail stores in a shopping centre. Mathematically, the density of some kind of object is calculated by counting the number of such objects in an area, and dividing by the size of the area. To read more about this, I recommend <a href="https://books.google.co.uk/books?id=e-xsrjsL7WkC&amp;dq=silverman+density+estimation+for+statistics&amp;lr=&amp;source=gbs_navlinks_s">Silverman, Bernard W. Density estimation for statistics and data analysis. Vol. 26. CRC press, 1986.</a></p>
</div>
</div>
<div id="summary" class="section level3" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Summary</h3>
<p>Right so hopefully this gives you a few things to think about. Be sure that you are confident to know about:</p>
<ul>
<li>Spatial objects - what they are and how they are represented</li>
<li>Attributes - the bits of information that belong to your spatial objects</li>
<li>Maps and projections - especially what WSG84 and BNG mean, and why it’s important that you know what CRS your data have</li>
</ul>
</div>
</div>
<div id="getting-some-spatial-data-to-put-on-a-map" class="section level2" number="2.5">
<h2><span class="header-section-number">2.5</span> Getting some spatial data to put on a map</h2>
<p>Alright let’s get some practical experience where we take some crime data, and find out how we can put it on the map!</p>
<div id="find-some-relevant-data-to-show-obtaining-data-on-crime" class="section level3" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Find some relevant data to show: obtaining data on crime</h3>
<p>For your first crime map, we better get some real world crime data. This can be done for the UK easily, as anonymised open crime data are released for the public to use. We can play around with police recorded crime data, which can be downloaded from the <a href="https://data.police.uk/data/">police.uk</a> website.</p>
<p>Let’s download some data for crime in Manchester.</p>
</div>
<div id="activity-1-get-some-crime-data" class="section level3" number="2.5.2">
<h3><span class="header-section-number">2.5.2</span> Activity 1: Get some crime data</h3>
<p>To do acquire the data, open the <a href="https://data.police.uk/data/">data.police.uk/data</a> website. Choose the data tab, in order to download some data.</p>
<ul>
<li>In <code>Date range</code> just select one month of data. Choose whatever month you like EXCEPT nothing more recent than June 2019. Unfortunately, for GMP there is no more recent data available than that. This is because they are having some serious IT issues <a href="https://www.manchestereveningnews.co.uk/news/greater-manchester-news/gmp-finally-switches-new-27m-16632975">see this article</a> which apparently have disrupted this flow of data.</li>
<li>In <code>Force</code> find <code>Greater Manchester Police</code>, and tick the box next to it.</li>
<li>In <code>Data sets</code> tick <code>Include crime data</code>.</li>
<li>Finally click on <code>Generate File</code> button.</li>
</ul>
<p>This will take you to a download page, where you have to click the <code>Download now</code> button. This will open a dialogue to save a .zip file. Navigate to the project directory folder you’ve created and save it there, ideally in a subfolder. I call my subfolder ‘data.’</p>
<p>Unzip the file. You can use the unzip function for this. A cool function you may want to use as well is file.choose(). If we pass this function as an argument to unzip(), we will get a pop window where we will be able to select our file using familiar point and click. Ideally, you want to rather write down the path to your file. But sometimes these shortcuts are convenient.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="section.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="fu">file.choose</span>())</span></code></pre></div>
<p>If you look at the <em>Files</em> window in the bottom right corner of RStudio you should see now a new subdirectory that contains a .csv file with the data that we need. Since I downloaded the data from June 2019 in my case this subdirectory is called 2019-06.</p>
<p>Before we can use this data we need to read it or import it into R and turn it into a dataframe object. To read in the .csv file, which is the format we just downloaded, the command is <code>read_csv()</code> from the <code>readr</code> package. You’ll need to load this package first.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="section.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div>
<p>Again there are two ways to read in the data, if you want to open a window where you can manually navigate and open the file, you can pass <code>file.choose()</code> argument to the <code>read_csv()</code> function as illustrated earlier.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="section.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#This code creates a dataframe object called crimes which will include the spreadsheet in the file we have downloaded. In my case, that is 2007-11-greater-manchester-street.csv.</span></span>
<span id="cb56-2"><a href="section.html#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="section.html#cb56-3" aria-hidden="true" tabindex="-1"></a>crimes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">file.choose</span>())</span>
<span id="cb56-4"><a href="section.html#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="section.html#cb56-5" aria-hidden="true" tabindex="-1"></a>m <span class="co"># Print the map</span></span></code></pre></div>
<p>Or, if you know the path to your file, you can code it in there, within quotation marks:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="section.html#cb57-1" aria-hidden="true" tabindex="-1"></a>crimes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/2019-06-greater-manchester-street.csv&quot;</span>)</span></code></pre></div>
<pre><code>## 
## ── Column specification ────────────────────────────────────────────────────────
## cols(
##   `Crime ID` = col_character(),
##   Month = col_character(),
##   `Reported by` = col_character(),
##   `Falls within` = col_character(),
##   Longitude = col_double(),
##   Latitude = col_double(),
##   Location = col_character(),
##   `LSOA code` = col_character(),
##   `LSOA name` = col_character(),
##   `Crime type` = col_character(),
##   `Last outcome category` = col_character(),
##   Context = col_logical()
## )</code></pre>
<p>You might notice that the object <code>crimes</code> has appeared in your work environment window. It will tell you how many observations (rows - and incidentally the number of recorded crimes in June 2019 within the GMP jurisdiction) and how many variables (columns) your data has.</p>
<p>Let’s have a look at the crimes dataframe with the <code>View()</code> function. This will open the data browser in RStudio</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="section.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(crimes)</span></code></pre></div>
<p>If you rather just want your results in the console, you can use the glimpse() function from the tibble package. This function does just that, it gives you a quick glimpse of the first few cases in the dataframe. Notice that there are two columns (Longitude and Latitude) that provide the require geographical coordinates that we need to plot this data.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="section.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb60-2"><a href="section.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(crimes)</span></code></pre></div>
<pre><code>## Rows: 32,058
## Columns: 12
## $ `Crime ID`              &lt;chr&gt; NA, &quot;aa1cc4cb0c436f463635890bcb4ff2cba08f5992…
## $ Month                   &lt;chr&gt; &quot;2019-06&quot;, &quot;2019-06&quot;, &quot;2019-06&quot;, &quot;2019-06&quot;, &quot;…
## $ `Reported by`           &lt;chr&gt; &quot;Greater Manchester Police&quot;, &quot;Greater Manches…
## $ `Falls within`          &lt;chr&gt; &quot;Greater Manchester Police&quot;, &quot;Greater Manches…
## $ Longitude               &lt;dbl&gt; -2.464422, -2.441166, -2.444807, -2.444807, -…
## $ Latitude                &lt;dbl&gt; 53.61250, 53.61604, 53.61151, 53.61151, 53.60…
## $ Location                &lt;chr&gt; &quot;On or near Parking Area&quot;, &quot;On or near Pitcom…
## $ `LSOA code`             &lt;chr&gt; &quot;E01004768&quot;, &quot;E01004768&quot;, &quot;E01004768&quot;, &quot;E0100…
## $ `LSOA name`             &lt;chr&gt; &quot;Bolton 001A&quot;, &quot;Bolton 001A&quot;, &quot;Bolton 001A&quot;, …
## $ `Crime type`            &lt;chr&gt; &quot;Anti-social behaviour&quot;, &quot;Violence and sexual…
## $ `Last outcome category` &lt;chr&gt; NA, &quot;Unable to prosecute suspect&quot;, &quot;Unable to…
## $ Context                 &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…</code></pre>
<p>You may notice that a lot of the variable names are messy in that they have a space in them - this can cause issues, so before playing around too much with the data we want to clean this up.</p>
<p>Luckily there is a very handy package you can use for this called <code>janitor</code> which contains the function <code>clean_names()</code>.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="section.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;janitor&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     chisq.test, fisher.test</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="section.html#cb65-1" aria-hidden="true" tabindex="-1"></a>crimes <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(crimes)</span></code></pre></div>
<p>Now the names are much neater. You can print them all for a view using the <code>names()</code> function:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="section.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(crimes)</span></code></pre></div>
<pre><code>##  [1] &quot;crime_id&quot;              &quot;month&quot;                 &quot;reported_by&quot;          
##  [4] &quot;falls_within&quot;          &quot;longitude&quot;             &quot;latitude&quot;             
##  [7] &quot;location&quot;              &quot;lsoa_code&quot;             &quot;lsoa_name&quot;            
## [10] &quot;crime_type&quot;            &quot;last_outcome_category&quot; &quot;context&quot;</code></pre>
<p>So what you see above is what we can call a <strong>basemap</strong>. The term basemap is seen often in GIS and refers to a collection of GIS data and/or orthorectified imagery that form the background setting for a map. The function of the basemap is to provide background detail necessary to orient the location of the map. Basemaps also add to the aesthetic appeal of a map.</p>
</div>
</div>
<div id="from-dataframes-to-spatial-objects-finding-spatial-information-in-our-data" class="section level2" number="2.6">
<h2><span class="header-section-number">2.6</span> From dataframes to spatial objects: finding spatial information in our data</h2>
<p>Having had a chance to inspect the data set you’ve downloaded, let’s consider what sort of spatial information we might be able to use.</p>
<div id="activity-2-find-the-spatial-data" class="section level3" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Activity 2: Find the spatial data</h3>
<p>If you have a look at the column names, what are some of the variables which you think might have some spatial component? Have a think about each column, and how you think it may help to put these crimes on the map. Discuss in your groups, and add the answer to the shared google doc. Once you are done, read on.</p>
<p>So what did you decide in your discussion? There are a few answers here.</p>
<p>In fact there are one each to map onto point, line, and polygon, which we read about earlier.</p>
</div>
<div id="the-point" class="section level3" number="2.6.2">
<h3><span class="header-section-number">2.6.2</span> The point</h3>
<p>First, and possibly most obvious, are the coordinates provided with each crime incident recorded. You can find this in the two columns - Longitude and Latitude. These two column help put each crime incident on a specific point on a map. For example, let’s take the very first crime incident. Here we use the head() function and specify that we want the first 1 rows only with <code>n=1</code> parameter.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="section.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crimes, <span class="at">n =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    
## 1 &lt;NA&gt;     2019… Greater Ma… Greater Man…     -2.46     53.6 On or n… E01004768
## # … with 4 more variables: lsoa_name &lt;chr&gt;, crime_type &lt;chr&gt;,
## #   last_outcome_category &lt;chr&gt;, context &lt;lgl&gt;</code></pre>
<p>You can see that the values are for Longitude and for Latitude. These two numbers allow us to put this point on a map.</p>
</div>
<div id="the-line" class="section level3" number="2.6.3">
<h3><span class="header-section-number">2.6.3</span> The line</h3>
<p>Another column which contains information about <em>where</em> the crime happened is the aptly named <code>location</code> variable. This shows you a list of locations related to where the crimes happened. You may see a few values such as on or near XYZ street. Let’s look again at the first entry.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="section.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crimes, <span class="at">n =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    
## 1 &lt;NA&gt;     2019… Greater Ma… Greater Man…     -2.46     53.6 On or n… E01004768
## # … with 4 more variables: lsoa_name &lt;chr&gt;, crime_type &lt;chr&gt;,
## #   last_outcome_category &lt;chr&gt;, context &lt;lgl&gt;</code></pre>
<p>You can see that the value is this isn’t great, as we might struggle to identify <em>which</em> parking area… Some other ones are more useful, let’s look at the last entry for example with the <code>tail()</code> function.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="section.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(crimes, <span class="at">n =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    
## 1 75e215f… 2019… Greater Ma… Greater Man…     -2.57     53.5 On or n… E01006347
## # … with 4 more variables: lsoa_name &lt;chr&gt;, crime_type &lt;chr&gt;,
## #   last_outcome_category &lt;chr&gt;, context &lt;lgl&gt;</code></pre>
<p>You can see that the value is . This makes our crime much easier to find, we just need to locate where is . We might have a shapefile of lines of all the roads of Manchester, and if we did, we can link the crime to that particular road, in order to map it.</p>
</div>
<div id="the-polygon" class="section level3" number="2.6.4">
<h3><span class="header-section-number">2.6.4</span> The polygon</h3>
<p>What more? You may also have seen the column <code>lsao_name</code> seems to have some spatial component, Let’s have a look at the first crime again.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="section.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(crimes, <span class="at">n =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   crime_id month reported_by falls_within longitude latitude location lsoa_code
##   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;       &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    
## 1 &lt;NA&gt;     2019… Greater Ma… Greater Man…     -2.46     53.6 On or n… E01004768
## # … with 4 more variables: lsoa_name &lt;chr&gt;, crime_type &lt;chr&gt;,
## #   last_outcome_category &lt;chr&gt;, context &lt;lgl&gt;</code></pre>
<p>You see the value for LSOA name is - Bolton we know is a Borough of Greater Manchester, but what is the 001 for ?</p>
<p>Well it denotes a sparticular geographical sub-unit within Bolton called a <strong>Lower Layer Super Output Area</strong>. This is a unit of <a href="https://www.ons.gov.uk/methodology/geography/ukgeographies/censusgeography">UK Census Geography</a>. The basic unit for Census Geography is an ‘Outout area’ - this is the resolution at which we can access data from the UK Census. We will be making use of census data later in the course. The Ourput Area (OA) is therefore the smallest unit we could use. Normally, in this module, we will be using a slightly larger version - the Lower Super Output Area (LSOA).</p>
<p>There are now 181,408 OAs, 34,753 lower layer super output areas (LSOA) and 7,201 middle layer super output areas (MSOA) in England and Wales. The neat thing about these Census geographies is the idea is that they don’t change (unlike administrative boundaries such as wards) and were created with statistical analysis in mind. The less neat thing is that although we use them to operationalise the concept of neighbourhood a lot, they may not bear much resemblance to what residesnts might think of as their neighbourhood. Think for a minute - do you know what LSOA you live in? Most likely you answered no. If you answered yes, I am impressed and you get geography nerd cred. Well done.</p>
<p>Anyway back to our crime data. You see we have two columns that reference LSOAs, <code>lsoa_name</code> and <code>lsoa_code</code>. We can use these to <em>link</em> our crime data to a <em>shapefile</em> of a <em>polygon</em> which contains the geometries needed to put the crime data on the map.</p>
</div>
</div>
<div id="putting-crime-on-the-map---simple-features" class="section level2" number="2.7">
<h2><span class="header-section-number">2.7</span> Putting crime on the map - simple features</h2>
<p>So how can we use these spatial details to put our crimes on the map? We need to somehow specify a geometry for our data, which links each unit of analysis (whether that is the point, line, or polygon) to a relevant geographical representation, which allows us to put this thing on the map.</p>
<p>How you add geographical information will vary with the type of information we have, but in all of these, we will use the simple features framework.</p>
<div class="figure">
<img src="https://user-images.githubusercontent.com/520851/50280460-e35c1880-044c-11e9-9ed7-cc46754e49db.jpg" alt="" />
<p class="caption">(Illustration (c) by Allison Horst)</p>
</div>
<p>What are simple features? sf package author Edzer Pebesma describes simple features as a standardized way of encoding spatial vector data (points, lines, polygons) in computers. The sf package is an R package for reading, writing, handling, and manipulating simple features in R, implementing the vector (points, lines, polygons) data handling functionality.</p>
<p>Traditionally spatial analysis in R were done using the <code>sp</code> package which creates a particular way of storing spatial objects in R. When most packages for spatial data analysis in R and for thematic cartography were first developed <code>sp</code> was the only way to work with spatial data in R. There are more than 450 packages rely on <code>sp</code>, making it an important part of the R ecosystem. More recently a new package, <code>sf</code> (which stands for “simple features”), is revolutionising the way that R does spatial analysis. This new package provides a new way of storing spatial objects in R and most recent R packages for spatial analysis and cartography are using it as the new default. It is easy to transform <code>sf</code> objects into <code>sp</code> objects, so that those packages that still don’t use this new format can be used. But in this course we will emphasise the use of <code>sf</code> whenever possible. You can read more about the history of spatial packages and the <code>sf</code> package in the first two chapters of <a href="https://geocompr.robinlovelace.net">this book</a>.</p>
<p>Features can be thought of as “things” or objects that have a spatial location or extent; they may be physical objects like a building, or social conventions like a political state. Feature geometry refers to the spatial properties (location or extent) of a feature, and can be described by a point, a point set, a linestring, a set of linestrings, a polygon, a set of polygons, or a combination of these. The simple adjective of simple features refers to the property that linestrings and polygons are built from points connected by straight line segments. Features typically also have other properties (temporal properties, color, name, measured quantity), which are called feature attributes.</p>
<p>For more detailed insight I recommend reading the paper <a href="https://journal.r-project.org/archive/2018/RJ-2018-009/RJ-2018-009.pdf">Simple Features for R: Standardized Support for Spatial Vector Data</a></p>
<div id="mapping-points-with-sf" class="section level3" number="2.7.1">
<h3><span class="header-section-number">2.7.1</span> Mapping points with sf</h3>
<p>Let’s get started with making some maps using <code>sf</code>. First, make sure you install the package, and then load with <code>library()</code> function.</p>
<p><strong>On Mac and Linux a few requirements must be met to install sf. These are described in the package’s README at <a href="github.com/r-spatial/sf">github.com/r-spatial/sf</a>.</strong></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="section.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
<pre><code>## Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1</code></pre>
<p>Now we can use the functions of sf in order to introduce geometries. Let’s start with the points</p>
<div id="activity-3-creating-a-sf-object-of-points" class="section level4" number="2.7.1.1">
<h4><span class="header-section-number">2.7.1.1</span> Activity 3: Creating a sf object of points</h4>
<p>WE know that we have two columns one for Longitude and one for Latitude, which pinpoint each crime event to a specific point, close to where it happened. Not <em>quite</em> where it happened, as the data are anonymised (more on this later), but for our purposes here, we can assume this is the location of the crime.</p>
<p>To map these points, we can transform our ordinary dataframe into a simple features object.</p>
<p>To do so, we can use the <code>st_as_sf()</code> function, into which we need to specify what we are to transform (our dataframe), where the spatial data can be found (our columns which hold the latitude and longidude information), and also what coordinate reference system the object has (see above our discussion about projections and coordinate reference systems).</p>
<p>Latitude longitude coordinates specify location on the <strong>WGS 84</strong> CRS (remember I said to keep this one in mind!). We can tell R that this is our CRS of choice by including it’s [EPSG identifier]
(<a href="https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset" class="uri">https://en.wikipedia.org/wiki/EPSG_Geodetic_Parameter_Dataset</a>) as a parameter in our function. It is handy to know the more common EPSG identifiers. For example, for WGS84 the EPSG identifier is <em>4326</em>. For British National Grid, the identifier is <em>27700</em>. We will be making use of these numbers, so do note them down somewhere.</p>
<p>Putting it all together in practice, we can create a simple features object from our dataframe using the latitude and longitude columns:</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="section.html#cb78-1" aria-hidden="true" tabindex="-1"></a>crimes_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(crimes,                                     <span class="co">#dataframe</span></span>
<span id="cb78-2"><a href="section.html#cb78-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;longitude&quot;</span>, <span class="st">&quot;latitude&quot;</span>),        <span class="co">#columns with coordinates</span></span>
<span id="cb78-3"><a href="section.html#cb78-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">crs =</span> <span class="dv">4326</span>)                                 <span class="co">#crs is WGS84</span></span></code></pre></div>
<p>We can see that this is now a simple features object using the class() function the we see the result “sf”:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="section.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(crimes_sf)</span></code></pre></div>
<pre><code>## [1] &quot;sf&quot;         &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>You might also notice something else that is different between crimes and crimes_sf. Have a look at the dimension (hint look in your ‘Environment’ tab). Do you see? Discuss what you think is different, and write your answers in the shared google doc.</p>
</div>
<div id="activity-4-mapping-our-points" class="section level4" number="2.7.1.2">
<h4><span class="header-section-number">2.7.1.2</span> Activity 4: Mapping our points</h4>
<p>Now that we have this sf object, how can we map it? I mentioned before about the graphical package <code>ggplot2</code>. We can use this, and its syntax, in order to map spatial data using the <code>geom_sf()</code> geometry.</p>
<p>First, a quick refresher on ggplot and the grammar of graphics. The grammar of graphics upon which this package is based on defines various components of a graphic. Some of the most important are:</p>
<p>-<strong>The data</strong>: For using <code>ggplot2</code> the data has to be stored as a data frame or tibble.</p>
<p>-<strong>The geoms</strong>: They describe the objects that represent the data (e.g., points, lines, polygons, etc..). This is what gets drawn. And you can have various different types layered over each other in the same visualisation.</p>
<p>-<strong>The aesthetics</strong>: They describe the visual characteristics that represent data (e.g., position, size, colour, shape, transparency).</p>
<p>-<strong>Facets</strong>: They describe how data is split into subsets and displayed as multiple small graphs.</p>
<p>-<strong>Stats</strong>: They describe statistical transformations that typically summarise data.</p>
<p>Let’s take it one step at the time.</p>
<p>Essentially the philosophy behind this is that all graphics are made up of layers. The package <code>ggplot2</code> is based on the grammar of graphics, the idea that you can build every graph from the same few components: a data set, a set of geoms—visual marks that represent data points, and a coordinate system.</p>
<p>Take this example (all taken from <em>Wickham, H. (2010). A layered grammar of graphics. Journal of Computational and Graphical Statistics, 19(1), 3-28.</em>)</p>
<p>You have a table such as:</p>
<p><img src="img/table.png" /></p>
<p>You then want to plot this. To do so, you want to create a plot that combines the following layers:</p>
<p><img src="img/layers.png" /></p>
<p>This will result in a final plot:</p>
<p><img src="img/combined.png" /></p>
<p>Taking our crime data as an example, we would build up our plot as follows:</p>
<p>Load ggplot2 package</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="section.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
<p>Data:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="section.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crimes, <span class="fu">aes</span>(<span class="at">x =</span> crime_type))</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Geometry:</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="section.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crimes, <span class="fu">aes</span>(<span class="at">x =</span> crime_type)) <span class="sc">+</span> </span>
<span id="cb83-2"><a href="section.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Aesthetics:</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="section.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crimes, <span class="fu">aes</span>(<span class="at">x =</span> crime_type, <span class="at">fill =</span> last_outcome_category)) <span class="sc">+</span> </span>
<span id="cb84-2"><a href="section.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<p>And then you could add any facets (for example if we had more than one month of data) or any statistics (for example error bars) with facet and stats layers. One more thing I do want to show is tidying up your chart, you can add theme and clean up your labels and titles and colour scheme.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="section.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crimes, <span class="fu">aes</span>(<span class="at">x =</span> crime_type, <span class="at">fill =</span> last_outcome_category)) <span class="sc">+</span> </span>
<span id="cb85-2"><a href="section.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb85-3"><a href="section.html#cb85-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb85-4"><a href="section.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb85-5"><a href="section.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Crime Type&quot;</span>) <span class="sc">+</span> </span>
<span id="cb85-6"><a href="section.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Number of cases&quot;</span>) <span class="sc">+</span> </span>
<span id="cb85-7"><a href="section.html#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">type =</span> <span class="st">&quot;qual&quot;</span>, <span class="at">palette =</span> <span class="dv">3</span>, <span class="at">name =</span> <span class="st">&quot;Outcome&quot;</span>)</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>This is not the greatest graph you’ll ever see, but it illustrates the process. Do read up on ggplot2 for example in Hadley Wickham’s book R4DS <a href="https://r4ds.had.co.nz/data-visualisation.html">chapter on data visualisation</a>.</p>
<p>So how can we use this for spatial data? We can use the <code>geom_sf()</code> function to do so.</p>
</div>
<div id="activity-5-mapping-our-points" class="section level4" number="2.7.1.3">
<h4><span class="header-section-number">2.7.1.3</span> Activity 5: Mapping our points</h4>
<p>Using geom_sf is slightly different to other geometries, for example how we used <code>geom_bar()</code> above. First we initiate the plot with the <code>ggplot()</code> function but don’t include the data in there. Instead, it is in the geometry where we add the data. And second we don’t need to specify the mapping of x and y. Since this is in the geometry column of our spatial object. Like so:</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="section.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb86-2"><a href="section.html#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> crimes_sf)</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
<p>And here we have a map of each point in our data set, each recorded crime in June 2019 in Greater Manchester.</p>
<p>Would you call this a map though? While it is presenting spatial data, there is not a lot of meaning being communicated. Point maps generally can be messy and their uses are specific to certain situations and cases, usually when you have fewer points, but here, these points are especially devoid of any meaning, as they are floating in a graph grid. SO let’s give it a basemap.</p>
<p>We can do this by adding a layer to our graph object. Specifically we will use the <code>annotation_map_tile()</code> from the <code>ggspatial</code> package. This provides us with a static Open Street Map layer behind our data, giving it (some) more context.</p>
<p>Remember to load the package (and install if you haven’t already)</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="section.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggspatial)</span></code></pre></div>
<p>And then use the <code>annotation_map_tile()</code> function, making sure to place it before the geom_sf points layer, so the background map is placed first, and the points on top of that:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="section.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb88-2"><a href="section.html#cb88-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">annotation_map_tile</span>() <span class="sc">+</span></span>
<span id="cb88-3"><a href="section.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> crimes_sf)</span></code></pre></div>
<pre><code>## Zoom: 9</code></pre>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>So what you see above is what we can call a <strong>basemap</strong>. The term basemap is seen often in GIS and refers to a collection of GIS data and/or orthorectified imagery that form the background setting for a map. The function of the basemap is to provide background detail necessary to orient the location of the map. Basemaps also add to the aesthetic appeal of a map.</p>
<p>In the lecture and some readings these are described as <em>reference maps</em>. We often may want to use these reference maps as <strong>basemaps</strong> for our thematic and point maps. They may give us context and help with the interpretation. You can see above that you are seeing the <em>Open Street Map</em> Basemap. This is one option but there are others.</p>
<p>Anyway let’s leave out points for now, and move on to how we might map our lines and polygons.</p>
</div>
</div>
<div id="mapping-data-by-joining-it-to-sf-objects" class="section level3" number="2.7.2">
<h3><span class="header-section-number">2.7.2</span> Mapping data by joining it to sf objects</h3>
<p>What about our other two columnds, location, and LSOAs? Well to put these on the map, we need a geometry representation of them. We will learn in this section where you may find these, how to download them, turn them into sf objects, and how to link your data to them to be able to map them.</p>
<div id="activity-6-finding-shapefiles" class="section level4" number="2.7.2.1">
<h4><span class="header-section-number">2.7.2.1</span> Activity 6: Finding shapefiles</h4>
<p>In this section you are going to learn how you take one of the most popular data formats for spatial objects, the <strong>shapefile</strong>, and read it into R. The shapefile was developed by ESRI, the developers and vendors or ArcGIS. And although many other formats have developed since and ESRI no longer holds the same market position it once occupied (though they’re still the player to beat), shapefiles continue to be one of the most popular formats you will encounter in your work. You can read more about shapefiles <a href="https://en.wikipedia.org/wiki/Shapefile">here</a>.</p>
<p>We are going to learn here how to obtain shapefiles for British census geographies. In the class today we talked about the idea of neighborhouds and we explained how a good deal of sociological and criminological work traditionally used census geographies as proxies for neighbourhouds. As of today, they still are the geographical subdivisions for which we can obtain a greater number of attribute information (e.g., sociodemographics, etc.).</p>
<p>For this activity we will focus on the polygon (the LSOA) rather than the lines of the streets, but the logic is more or less the same. Remember above we talked about what is a census geography. You can read more about census boundary data <a href="https://census.ukdataservice.ac.uk/use-data/guides/boundary-data">here</a>. “Boundary data are a digitised representation of the underlying geography of the census.” Census Geography is often used in research and spatial analysis because it is divided into units based on population counts, created to form comparable units, rather than other administrative boundaries such as wards or police force areas. However depending on your research question and the context for your analysis, you might be using different units. The hierarchy of the census geographies goes from Country to Local Authority to Middle Layer Super Output Area (MSOA) to Lower Layer Super Output Area (LSOA) to Output Area:</p>
<p><img src="img/maps_geography_types.png" /></p>
<p>Here we will get some boundaries for Manchester. Let’s use the LSOA level, so that we can link back to our crime data earily. These are geographical regions designed to be more stable over time and consistent in size than existing administrative and political boundaries. LSOAs comprise, on average, 600 households that are combined on the basis of spatial proximity and homogeneity of dwelling type and tenure.</p>
<p>So to get some boundary data, you can use the UK Data Service website. There is a simple <a href="https://borders.ukdataservice.ac.uk/bds.html">Boundary Data Selector</a> tool which we can use.</p>
<p>When you get to the link, you will see on the top there is some notification to help you with the boundary data selector. If in the future you are looking for boundary data and you are feeling unsure at any point, feel free to click on that note “<strong>How to use Boundary Data Selector</strong>” which will help to guide you.</p>
<p>For now, let’s focus on the selector options. Here you can choose the country you want to select shapefiles for. We select “England.” You can also choose the type of geography we want to use. Here we select “Statistical Building Block,” as discussed above. And finally you can select when you want it for. If you are working with historical data, it makes sense to find boundaries that match the timescale for your data. Here we will be dealing with contemporary data, and therefore we want to be able to use the newest available boundary data.</p>
<hr />
<p><img src="img/boundary_selector_1.png" /></p>
<p>Once you have selected these options, click on the “Find” button. That will populate the box below:</p>
<hr />
<p><img src="img/boundary_selector_2.png" /></p>
<hr />
<p>Here you can select the boundaries we want. As discussed, we want the census lower super output areas. But again, your future choices here will depend on what data you want to be mapping.</p>
<p>Once you’ve made your choice, click on “List Areas.” This will now populate the box below. We are here concerned with Manchester. However you can select more than one if you want boundaries for more than one area as well. Just hold down “ctrl” to select multiple areas individually, or the shift key to select everything in between.</p>
<hr />
<p><img src="img/boundary_selector_3.png" /></p>
<hr />
<p>Once you’ve made your decision click on the “Extract Boundary Data” button. You will see the following message:</p>
<hr />
<p><img src="img/wait.png" /></p>
<hr />
<p>You can bookmark, or just stay on the page and wait. How long you have to wait will depend on how much data you have requested to download.</p>
<p>When your data is read, you will see the following message:</p>
<hr />
<p><img src="img/download.png" /></p>
<hr />
<p>You have to right click on the “BoundaryData.zip,” and hit Save Target as on a PC or Save Link As on a Mac:</p>
<hr />
<p><img src="img/save_link_as.png" /></p>
<hr />
<p>Navigate to the folder you have created for this analysis, and save the .zip file there. Extract the file contents using whatever you like to use to unzip compressed files.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="section.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For example,</span></span>
<span id="cb90-2"><a href="section.html#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span>(<span class="st">&quot;BoundaryData.zip&quot;</span>, <span class="at">exdir =</span> <span class="st">&quot;BoundaryData&quot;</span>)</span></code></pre></div>
<p>You should end up with a folder called “BoundaryData.” Have a look at its contents:</p>
<hr />
<p><img src="img/folder_contents.png" /></p>
<hr />
<p>So you can see immediately that there are some documentations around the usage of this shapefile, in the readme and the terms and conditions. Have a look at these as they will contain information about how you can use this map. For example, all your maps will have to mention where you got all the data from. So since you got this boundary data from the UKDS, you will have to note the following:</p>
<p>“Contains National Statistics data © Crown copyright and database right [year]
Contains OS data © Crown copyright [and database right] (year)”</p>
<p>You can read more about this in the terms and conditions document.</p>
<p>But then you will also notice that there are 4 files with the same name “england_oac_2011.” <strong>It is important that you keep all these files in the same location as each other!</strong> They all contain different bits of information about your shapefile (and they are all needed):</p>
<ul>
<li>.shp — shape format; the feature geometry itself - this is what you see on the map</li>
<li>.shx — shape index format; a positional index of the feature geometry to allow seeking forwards and backwards quickly</li>
<li>.dbf — attribute format; columnar attributes for each shape, in dBase IV format.</li>
<li>.prj — projection format; the coordinate system and projection information, a plain text file describing the projection using well-known text format</li>
</ul>
<p>Sometimes there might be more files associated with your shapefile as well, but we will not cover them here. So unlike when you work with spreadsheets and data in tabular form, which typically is just all included in one file; when you work with spatial data, you have to live with the required information living in separate files that need to be stored together. So, being tidy and organised is even more important when you carry out projects that involve spatial data. Please do remember the suggestions we provided last week as to how to organise your RStudio project directories.</p>
</div>
<div id="activity-7-reading-shapefiles-into-r" class="section level4" number="2.7.2.2">
<h4><span class="header-section-number">2.7.2.2</span> Activity 7: Reading shapefiles into R</h4>
<!-- ### **HOMEWORK 2** -->
<!-- Read Section 2.1 of the Geocomputation book linked above. Answer the following questions: -->
<!-- 1. What are some strengths/advantages of the sf package? -->
<!-- 2. What code do you need to transform a sf object into a sp object. -->
<!-- 3  What is simply a sf object? -->
<p>To read in your data, you will need to know the path to where you have saved it. Ideally this will be in your data folder in your project directory.</p>
<p>Let’s create an object and assign it our shapefile’s name:</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="section.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember to use the appropriate pathfile in your case</span></span>
<span id="cb91-2"><a href="section.html#cb91-2" aria-hidden="true" tabindex="-1"></a>shp_name <span class="ot">&lt;-</span> <span class="st">&quot;data/BoundaryData/england_lsoa_2011.shp&quot;</span></span></code></pre></div>
<p>Make sure that this is saved in your working directory, and you have set your working directory.</p>
<p>Now use the <code>st_read()</code> function to read in the shapefile:</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="section.html#cb92-1" aria-hidden="true" tabindex="-1"></a>manchester_lsoa <span class="ot">&lt;-</span> <span class="fu">st_read</span>(shp_name)</span></code></pre></div>
<pre><code>## Reading layer `england_lsoa_2011&#39; from data source `/Users/reka/Desktop/crime_mapping_textbook/data/BoundaryData/england_lsoa_2011.shp&#39; using driver `ESRI Shapefile&#39;
## Simple feature collection with 282 features and 3 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: 378833.2 ymin: 382620.6 xmax: 390350.2 ymax: 405357.1
## projected CRS:  OSGB 1936 / British National Grid</code></pre>
<p>Now you have your spatial data file. You can have a look at what sort of data it contains, the same way you would view a dataframe, with the <code>View()</code> function:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="section.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(manchester_lsoa)</span></code></pre></div>
<pre><code>## Rows: 282
## Columns: 4
## $ label    &lt;chr&gt; &quot;E08000003E02001062E01005066&quot;, &quot;E08000003E02001092E01005073&quot;…
## $ name     &lt;chr&gt; &quot;Manchester 018E&quot;, &quot;Manchester 048C&quot;, &quot;Manchester 018A&quot;, &quot;Ma…
## $ code     &lt;chr&gt; &quot;E01005066&quot;, &quot;E01005073&quot;, &quot;E01005061&quot;, &quot;E01005062&quot;, &quot;E010050…
## $ geometry &lt;POLYGON [m]&gt; POLYGON ((384850 397432, 38..., POLYGON ((382221.1 3…</code></pre>
<p>And of course, since it’s spatial data, you can map it using the geom_sf() function, as we did with our points:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="section.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb96-2"><a href="section.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> manchester_lsoa)</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Great, we now have an outline of the LSOAs in Manchester. Notice how the shape is different to that of the points in our crime data. Why do you think this is? Discuss and write your thoughts in the shared google doc.</p>
</div>
<div id="activity-8-data-wrangling-with-dplyr" class="section level4" number="2.7.2.3">
<h4><span class="header-section-number">2.7.2.3</span> Activity 8: Data wrangling with dplyr</h4>
<p>In order to map crimes to LSOAs we might want to take a step back and think about unit of analysis at which our data are collected. In our original dataframe of crimes, we saw that each crime incident is one row. So the unit of anlysis is each crime. Since we were looking to map each crime at the location it happened, we used the latitude and longitude supplied with each one, and this supplied a geometry each for each crime type.</p>
<p>However, when we are looking to map our data to LSOA level, we need to match the crime data to the geometry we wish to display.</p>
<p>Have a look at the manchester_lsoa object we mapped above. How many rows (observations) does it have? You can check this by looking in the Environment pane, or by using the <code>nrow()</code> function.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="section.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(manchester_lsoa)</span></code></pre></div>
<pre><code>## [1] 282</code></pre>
<p>You can see this has 282 rows. This means we have geometries for 282 LSOAs.</p>
<p>On the other hand, our crimes dataframe has 32058 rows, one for each crime (observation). So how can we match these up? The answer lies in thinking about what it is that our map using LSOAs as our unit of analysis will be able to tell us. Think of other maps of areas - what are they usually telling you? Usually we expect to see crimes per neighbourhood - something like this. So our unit of analysis needs to be LSOA, and for each one we need to know how many crimes occurred in that area.</p>
<p>To achieve this, we will wrangle our data using functions from the <code>dplyr</code> package. This is a package for conducting all sorts of operations with data frames. We are not going to cover the full functionality of dplyr (which you can consult in <a href="https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html">this tutorial</a>), but we are going to cover three different very useful elements of dplyr: the select function, the group_by function, and the piping operator.</p>
<p>First load the library:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="section.html#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>The <code>select()</code> function provides you with a simple way of subsetting columns from a data frame. So, say we just want to use one variable, lsoa_code, from the crimes dataframe and store it in a new object we could write the following code:</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="section.html#cb100-1" aria-hidden="true" tabindex="-1"></a>new_object <span class="ot">&lt;-</span> <span class="fu">select</span>(crimes, lsoa_code)</span></code></pre></div>
<p>We can also use the <code>group_by()</code> function for performing group operations. Essentially this function ask R to group cases within categories and then do something with those grouped cases. So, say, we want to count the number of cases within each LSOA, we could use the following code:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="section.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First we group the cases by LSOA code and stored this organised data into a new object</span></span>
<span id="cb101-2"><a href="section.html#cb101-2" aria-hidden="true" tabindex="-1"></a>grouped_crimes <span class="ot">&lt;-</span> <span class="fu">group_by</span>(new_object, lsoa_code)</span>
<span id="cb101-3"><a href="section.html#cb101-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-4"><a href="section.html#cb101-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Then we could count the number of cases within each category and use the summarise function to print the results</span></span>
<span id="cb101-5"><a href="section.html#cb101-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(grouped_crimes, <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb101-6"><a href="section.html#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="section.html#cb101-7" aria-hidden="true" tabindex="-1"></a><span class="co">#We could infact create a new dataframe with these results</span></span>
<span id="cb101-8"><a href="section.html#cb101-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-9"><a href="section.html#cb101-9" aria-hidden="true" tabindex="-1"></a>crime_per_LSOA <span class="ot">&lt;-</span> <span class="fu">summarise</span>(grouped_crimes, <span class="at">count =</span> <span class="fu">n</span>())</span></code></pre></div>
<p>As you can see we can do what we wanted, create a new dataframe with the required info, but if we do this we are creating many objects that we don’t need, one at each step. Instead there is a more efficient way of doing this, without so many intermediate steps clogging up our environment with unnecessary objects. That’s where the piping operator comes handy. The piping operator is written like <code>%&gt;%</code> and it can be read as “and then.” Look at the code below:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="section.html#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co">#First we say create a new object called crime_per_lsoa, and then select only the LSOA.code column to exist in this object, and then group this object by the LSOA.code, and then count the number of cases within each category, this is what I want in the new object.</span></span>
<span id="cb102-2"><a href="section.html#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="section.html#cb102-3" aria-hidden="true" tabindex="-1"></a>crimes_per_lsoa <span class="ot">&lt;-</span> crimes <span class="sc">%&gt;%</span></span>
<span id="cb102-4"><a href="section.html#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(lsoa_code) <span class="sc">%&gt;%</span></span>
<span id="cb102-5"><a href="section.html#cb102-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span></code></pre></div>
<p>Essentially we obtain the same results but with more streamlined and elegant code, and not needing additional objects in our environment.</p>
<p>And now we have a new object, <em>crimes_per_lsoa</em> if we have a look at this one, we can now see what each row represents one LSOA, and next to it we have a variable for the number of crimes from each area. We created a new dataframe from a frequency table, and as each row of the crimes data was one crime, the frequency table tells us the number of crimes which occurred in each LSOA.</p>
<p>Those of you playing close attention might note that there are still more observations in this dataframe (1671) than in the manchester_lsoas one (282). Why do you think that might be? Look back at how you answered the final question for the previous activity for a hint.</p>
</div>
<div id="activity-9-join-data-to-sf-object" class="section level4" number="2.7.2.4">
<h4><span class="header-section-number">2.7.2.4</span> Activity 9: Join data to sf object</h4>
<p>Our next task is to link our crimes data to our sf spatial object to help us map this. Notice anything similar between the data from the shapefile and the frequency table data we just created? Do they share a column?</p>
<p>Yes! You might notice that the <code>lsoa_code</code> field in the crimes data matches the values in the <code>code</code> field in the spatial data. In theory we could join these two data tables.</p>
<p>So how do we do this? Well what you can do is to link one data set with another. Data linking is used to bring together information from different sources in order to create a new, richer dataset. This involves identifying and combining information from corresponding records on each of the different source datasets. The records in the resulting linked dataset contain some data from each of the source datasets. Most linking techniques combine records from different datasets if they refer to the same entity (an entity may be a person, organisation, household or even a geographic region.)</p>
<p>You can merge (combine) rows from one table into another just by pasting them in the first empty cells below the target table—the table grows in size to include the new rows. And if the rows in both tables match up, you can merge columns from one table with another by pasting them in the first empty cells to the right of the table—again, the table grows, this time to include the new columns.</p>
<p>Merging rows is pretty straightforward, but merging columns can be tricky if the rows of one table don’t always line up with the rows in the other table. By using <code>left_join()</code> from the <code>dplyr</code> package, you can avoid some of the alignment problems.</p>
<p><code>left_join()</code> will return all rows from x, and all columns from x and y. Rows in x with no match in y will have NA values in the new columns. If there are multiple matches between x and y, all combinations of the matches are returned.</p>
<p>So we’ve already identified that both our crimes data, and the spatial data contain a column with matching values, the codes for the LSOA that each row represents.</p>
<p><img src="img/fn2187.png" /></p>
<p><strong>You need a unique identifier to be present</strong> for each row in all the data sets that you wish to join. This is how R knows what values belong to what row! What you are doing is matching each value from one table to the next, using this unique identified column, that exists in both tables. For example, let’s say we have two data sets from some people in Hawkins, Indiana. In one data set we collected information about their age. In another one, we collected information about their hair colour. If we collected some information that is unique to each observation, and this is the <em>same</em> in both sets of data, for example their names, then we can link them up, based on this information. Something like this:</p>
<p><img src="img/merge_logic_1.png" /></p>
<p>And by doing so, we produce a final table that contains all values, lined up <em>correctly</em> for each individual observation, like this:</p>
<p><img src="img/merge_logic_2.png" /></p>
<p>This is all we are doing, when merging tables, is we are making use that we line up the correct value for all the variables, for all our observations.</p>
<p>Why are we using <em>left</em> join though? There is a <a href="http://stat545.com/bit001_dplyr-cheatsheet.html">whole family of join functions as part of dplyr</a> which join data sets. There is also a right_join, and an inner_join and an outer_join and a full_join. But here we use left join, because that way we keep all the rows in x (the left-hand side dataframe), and join to it all the matched columns in y (the right-hand side dataframe).</p>
<p>So let’s join the crimes data to the spatial data, using left_join():</p>
<p>We have to tell left_join what are the dataframes we want to join, as well as the names of the columns that contain the matching values in each one. This is “code” in the manchester_lsoa dataframe and “lsoa_code” in the crimes_per_lsoa dataframe. Like so:</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="section.html#cb103-1" aria-hidden="true" tabindex="-1"></a>manchester_lsoa <span class="ot">&lt;-</span> <span class="fu">left_join</span>(manchester_lsoa, crimes_per_lsoa, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;code&quot;</span><span class="ot">=</span><span class="st">&quot;lsoa_code&quot;</span>))</span></code></pre></div>
<p>Now if you have a look at the data again, you will see that the column of number of crimes (n) has been added on.</p>
</div>
<div id="activity-10-mapping-our-data-at-polygon-level" class="section level4" number="2.7.2.5">
<h4><span class="header-section-number">2.7.2.5</span> Activity 10: Mapping our data at polygon level</h4>
<p>Now that we have joined the crimes data to the geometry, you can use this to make our map!</p>
<p>Remember our original empty map:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="section.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb104-2"><a href="section.html#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_sf</span>(<span class="at">data =</span> manchester_lsoa)</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>Well now, since we have the column (varaible) for number of crimes here, we can use that to share the polygons based on how many crimes there are in each LSOA. We can do this by specifying the <code>fill=</code> parameter of the <code>geom_sf</code> function.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="section.html#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb105-2"><a href="section.html#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_sf</span>(<span class="at">data =</span> manchester_lsoa, <span class="fu">aes</span>(<span class="at">fill =</span> count))</span></code></pre></div>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>We can add a basemap, and adjust the colour scheme, and even the opacity to see under our shape files.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="section.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb106-2"><a href="section.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_map_tile</span>() <span class="sc">+</span>  <span class="co"># add basemap</span></span>
<span id="cb106-3"><a href="section.html#cb106-3" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_sf</span>(<span class="at">data =</span> manchester_lsoa, <span class="fu">aes</span>(<span class="at">fill =</span> count), <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span> <span class="co"># alpha sets the opacity</span></span>
<span id="cb106-4"><a href="section.html#cb106-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient2</span>(<span class="at">name =</span><span class="st">&quot;Number of crimes&quot;</span>) <span class="co">#use scale_fill_gradient2() for a different palette and name the variable on the legend</span></span></code></pre></div>
<pre><code>## Zoom: 10</code></pre>
<p><img src="crime_mapping_textbook_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
<!-- And we can even add some interactivity! -->
<!-- ```{r} -->
<!-- tmap_mode("view") -->
<!-- tmap_last() -->
<!-- ``` -->
</div>
</div>
</div>
<div id="summary-1" class="section level2" number="2.8">
<h2><span class="header-section-number">2.8</span> Summary</h2>
<p>In this session we had a play around with some regular old crime data and discovered how we can use the sf package in R to assign it a geometry (both at point and polygon level), and how that can help us visualise our results. We covered some very important concepts such as projections and coordinate reference systems, and we had a play at acquiring shapefiles which can help us visualise our data. We had a think about units of analysis, and how that will affect how we visualise our data.</p>
<p>Make sure to complete the homework tasks available on Blackboard, and once you have done that, and read all the readings and watched all the videos, complete your homework quiz.</p>
<p>Next week we will spend a bit of more time discussing how to make good choices when producing maps.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="a-first-lesson-about-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="thematic-maps-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["crime_mapping_textbook.pdf", "crime_mapping_textbook.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
